### ISSUE TITLE
Error reading french airspace file with v7.25

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#1011]
XCSoar versions having and not having the problem
-------------------------------------------------

problem detected with v7.25, does not exist on v7.23

Expected behavior
-----------------

the airspace file should be read without error message

Actual behavior
---------------

error message during airspace load

![polerr](https://user-images.githubusercontent.com/69430537/186581629-de9f9ecb-4e81-4bbe-82cd-54eb7ee15c7c.png)

Steps to reproduce the behavior
-------------------------------

use french airspace file from

https://www.ffvp.fr/liens-utiles-telechargements

and store it in XCSoarData/Airspace directory. Use this file in airspace setup

Do you have any idea what may have caused this?
-----------------------------------------------

software change (airspace data consitency checks)

bug or feature?

Do you have an idea how to solve the issue?
-------------------------------------------

no

**Comment by lordfolken** [comment]
Feature. The file has an error.

**Comment by lordfolken** [comment]
Previously it would ignore it and not display the particular airspace.

**Comment by fraktal-sb** [comment]
so I will communicate this with the maintainer of the airspace file.

**Comment by lordfolken** [comment]
Please use the one provided in the download manager. 
That one points to the github repo of the french airspace:
https://github.com/XCSoar/xcsoar-data-content/blob/master/data/remote/airspace/country/France_Airspace.txt.json

The project located here. 
https://github.com/planeur-net/airspace

As far as i can see that file is error free.

**Comment by fraktal-sb** [comment]
but in https://xcsoar.org/download/data.html we have still the link to french airspace data

**Comment by lordfolken** [comment]
Good catch. I removed the links. Soaringweb does the better job of maintaining this list. 
https://github.com/XCSoar/website/commit/c2cdf7b2f9554a95a013c7be79c5c29017fc7233

**Comment by Blaubart** [comment]
I have the same problem with the airspace from Poland

**Comment by lordfolken** [comment]
Its hosted on soaringweb.org Want to take it up with john laibacher?

**Comment by Blaubart** [comment]
OK, I'll send him a message

**Comment by elgandoz** [comment]
Hey @lordfolken, we're getting this issue on the [Australia_HGPG_Siteguide.txt]().

The issues are all the powerlines crossing the valleys which are referenced using only 2 points:
```
AC Q
AN Powerline
AL SFC
AH 100 ft AGL
DP 36:41:33.64 S 146:54:35.88 E
DP 36:41:12.45 S 146:54:57.62 E
```

Given that this is valuable information, how can we draw a simple line?

**Comment by MaxKellermann** [comment]
> Given that this is valuable information, how can we draw a simple line?

Second answer to this question: you can draw simple lines using XCSoar's topography renderer. You already see lots of lines on your map (roads, rivers etc.).

**Comment by elgandoz** [comment]
@MaxKellermann  The topography renderer won't throw a warning on screen.

I get that a polygon is not a line, but the point is the safety aspect of flying, more than the semantic.

Winpilots OpenAir format defines the Q class for danger, which is what a powerline is.

Not having this type of warning on a free flying app would be a flaw IMHO.

**Comment by MaxKellermann** [comment]
> Winpilots OpenAir format defines the Q class for danger, which is what a powerline is.

But it has no definition for "lines", therefore it is impossible to represent a powerline with a Winpilot OpenAir file.

> Not having this type of warning on a free flying app would be a flaw IMHO.

Then you should get involved in the "free flying app" and implement the feature. It's free software, you have the freedom to fix all flaws that you see, and you don't need anybody's permission or good will for that. Never complain about flaws. Just do it.

**Comment by mlep** [comment]
> But it has no definition for "lines", therefore it is impossible to represent a powerline with a Winpilot OpenAir file.

Well, a Winpilot OpenAir file _can_ contain information about terrain: the file format ([http://www.winpilot.com/usersguide/userairspace.asp](http://www.winpilot.com/usersguide/userairspace.asp)) allows for this.

I think the exact issue is that this format separates the information into two files (airspace.txt and terrain.txt), but XCSoar does not support the terrain features at the moment.

**Comment by MaxKellermann** [comment]
> I think the exact issue is that this format separates the information into two files (airspace.txt and terrain.txt), but XCSoar does not support the terrain features at the moment.

And the WinPilot file format still doesn't support lines; it only supports polygons, and a line is not a polygon.

**Comment by elgandoz** [comment]
> Then you should get involved in the "free flying app" and implement the feature. It's free software, you have the freedom to fix all flaws that you see, and you don't need anybody's permission or good will for that. Never complain about flaws. Just do it.

I already did it in the past, and that's what I'm doing now.
I just found out, and I was just asking if there was a know way to have a line with the current implementation.
That's not a complaining.

**Comment by mlep** [comment]
> it only supports polygons, and a line is not a polygon.

My understanding is that "open polygons" (ie. `TO {string}`) are to be used for roads, borders, etc.

**Comment by MaxKellermann** [comment]
> My understanding is that "open polygons" (ie. `TO {string}`) are to be used for roads, borders, etc.

What exactly is an "open polygon"? Did they mean "polyline"? Because a polygon is never "open", by definition.

**Comment by mlep** [comment]
Well, that may depend on your definition of a polygon. For example, this page, hosted by a math department, defines closed and opened polygons: [https://www.math.utah.edu/IBIS/man/node41.html](https://www.math.utah.edu/IBIS/man/node41.html)

Anyway, the format allows drawing roads, etc. The issue is about a suitable implementation in XCSoar.

**Comment by MaxKellermann** [comment]
> Well, that may depend on your definition of a polygon. For example, this page, hosted by a math department, defines closed and opened polygons: https://www.math.utah.edu/IBIS/man/node41.html

This is documentation of some software, a copy of which just happens to be hosted by a math department of some university, but that does not mean this math department endorses the definition implied by this software manual.

Every math-related definition I could find on the net agrees with my description; i.e. there is no such thing as an "open polygon".

So let's not dilute the definition of "polygon", this only increases confusion, and distracts from the real problem, because we continue bikeshedding what a polygon is, when the (educated) rest of the world clearly agrees that a polygon must be closed.

The real problem is that the OpenAir format allows describing a **polyline** (which they mistakenly call "open polygon"), but XCSoar doesn't support that.

Also note that according to the OpenAir format specification, a polyline is declared with the `TO` command. The `AC` command, as discussed here, can *not* be used to describe a polyline, therefore no matter how you turn it, the data cited here is wrong.
