### ISSUE TITLE
Error with Airspace

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#1022]
I compiled the current version of XCSoar and I get this error with the french airspace:
"Not enough polygon points [84169] "AC P""

At line 84169 is the following written:
AC P
AN Axe 2
AL FL090
AH FL140
DP 44:12:00 N 004:59:00 E
DP 44:15:00 N 005:02:00 E

How could I solve the error??

**Comment by fraktal-sb** [comment]
see https://github.com/XCSoar/XCSoar/issues/1011

**Comment by Blaubart** [comment]
sorry, haven't seen that!! Thanks
