### ISSUE TITLE
Folders for waypoint details

### ISSUE THREAD

**Issue by abiweil** [XCSoar/XCSoar#1024]
XCSoar version 
all

<!--
Which XCSoar version are you using?
7.23 + 7.25
What should XCSoar do differently, what functionality should be added?
Arrange the waypoint detail files in subfolders of the XCsoardata-folder. 
Actuality its very difficult to get an overview over the files in the folder, if you have hundreds of airfield pictures in the main-folder. 

<!--
Please describe the feature you'd like us to add/change.
To introduce separate folders for the waypointdetails of different regions of the world

What are you trying to do, what is the use case for the suggestion?
Better overview
Easier changing from flying region to flying region.
Each waypoint-detail-file (for example airfield picture) can easily be found in a separate folder for the corresponding region

<!--
Please describe briefly what you're trying to do, that would be possible if
the suggested feature was implemented.
If I fly in the Alps, I want to select the pictures of the outlanding fields out of the folder for the Alps.
If I fly in Namibia, I want to select the airfield pictures out of the folder for Namibia.
If the details are separated in different folders, the picture files can much easier associated to the special region and easier be overviewed.

**Comment by lordfolken** [comment]
No info.

**Comment by abiweil** [comment]
I have no idea, why the issue has been closed. What means “no info”, there are several lines of infotext!

**Comment by DanD222** [comment]
I don’t see any text either, maybe it’s inside the section that´s commented out? All I see is the following text: “_XCSoar version
all_”

**Comment by abiweil** [comment]
Okay, I obviously did something wrong, some hours before, the text was still present. so I try to repeat it in a new issue.
