### ISSUE TITLE
Multiple USB devices with same VID:PID id nor working for CP2102

### ISSUE THREAD

**Issue by hjr** [XCSoar/XCSoar#1039]
XCSoar versions having and not having the problem
-------------------------------------------------
7.24, 7.25, 7.26 on Android

Expected behavior
-----------------
Plugged USB/serial converter show up in XCSoar the same way as in a USB diagnostics tool and are selectable as interface to devices .. even if they have the same VID:PID id.

Actual behavior
---------------
Does work fine for ie. the FTDI uarts, but not for CP2102 (10C4:EA60) ones.

Steps to reproduce the behavior
-------------------------------
Plug multiple USB/serial converter and see the listed devices from XCSoar compared to a USB diagnostics tool.

Do you have any idea what may have caused this?
-----------------------------------------------
Not really, the topic was expected to be resolved with issue #968.

Do you have an idea how to solve the issue?
-------------------------------------------
--

**Comment by hjr** [comment]
Pics of XCS and USB diagnostics when four USB converter are connected to the Android. 
![IMG_2266](https://user-images.githubusercontent.com/415029/188480077-7e97af45-3aa6-432d-af68-47e32f260a8a.JPG)
![IMG_2267](https://user-images.githubusercontent.com/415029/188480090-6ce93367-d7c2-4b53-86b1-69b064ee4bdc.JPG)

**Comment by MaxKellermann** [comment]
Do CP2102 devices have a serial number? (I can't reproduce because I don't have one.)

**Comment by lyusupov** [comment]
https://github.com/XCSoar/XCSoar/issues/966#issuecomment-1228363451

**Comment by MaxKellermann** [comment]
Thanks, @lyusupov, this is what I suspected - not a XCSoar bug then, and nothing XCSoar can fix.

**Comment by hjr** [comment]
Thanks!
