### ISSUE TITLE
Reach of the glider calculation is broken

### ISSUE THREAD

**Issue by bomilkar** [XCSoar/XCSoar#1068]
XCSoar versions having and not having the problem
-------------------------------------------------

This has been happening in pre-releases of 7.28 since September 26, 2022. The 7.27 release (and earlier) is still OK.

Expected behavior
-----------------

The "reach of glider" calculation marks the reachable area (given terrain, altitude, wind, reach mode, etc).
 A star-like shape is expected unless the terrain is really flat.

Actual behavior
---------------

The reachable area of the glider is always circular. It seems that the terrain information is not taken into account.

![circle3](https://user-images.githubusercontent.com/20871255/196139978-70941320-1851-48ac-8e8d-35b9612fc578.PNG)

Steps to reproduce the behavior
-------------------------------

Turn on Reach_Mode in Config->System-Glide_Computer->Route
Then replay a flight log so that a reachable area should be displayed. Try 7.27 to see how it's supposed to look.

Do you have any idea what may have caused this?
-----------------------------------------------

It might be related to recent changes made to src/Computer/RouteComputer .

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
Can't reproduce - I just made this screenshot with a577092dff2110827346ed927c2914e100515cb7
![2022-10-17-185537_606x509_scrot](https://user-images.githubusercontent.com/1443144/196237826-d6f2200a-4471-4928-847b-2673f521ffca.png)

**Comment by bomilkar** [comment]
After a "git pull" and starting from an empty PRF applying only minimal changes: Still the same symptom.
Can you share your PRF?
Here is mine:
[empty.zip](https://github.com/XCSoar/XCSoar/files/9808987/empty.zip)

**Comment by MaxKellermann** [comment]
> This has been happening in pre-releases of 7.28 since September 26, 2022. The 7.27 release (and earlier) is still OK.

This is wrong. 7.27 is *NOT* ok.
