### ISSUE TITLE
Android Emulated Directory Access

### ISSUE THREAD

**Issue by hdechelard** [XCSoar/XCSoar#1071]
XCSoar versions having and not having the problem
-------------------------------------------------

 XCSoar 7

Expected behavior
-----------------

 Find and copy files to XCSoarData directory

Actual behavior
---------------

 Emulated directory is not accessible by phone user

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------
![Screenshot_20221024-081728_XCSoar](https://user-images.githubusercontent.com/67298888/197418772-88f646ce-5357-44ed-bf63-b2204da652dd.jpg)

**Comment by MaxKellermann** [comment]
What is "Emulated directory"?
What does "XCSoar 7" mean? Is that the version having the problem or the version not having the problem? Please read properly what is asked from you before you submit a bug report.
I have no idea what your screenshot means and why you didn't post instructions how to reproduce your problem. I don't even know what your problem  is.

**Comment by MaxKellermann** [comment]
No reply
