### ISSUE TITLE
Open sector in the task point to the wrong way

### ISSUE THREAD

**Issue by posenery2004** [XCSoar/XCSoar#1072]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
Everything is missing in this bug report.
