### ISSUE TITLE
FLARM sound events

### ISSUE THREAD

**Issue by Mitkopeev** [XCSoar/XCSoar#1081]
XCSoar version
--------------

7.28

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

FLARM event sounds

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

Since FLARM events are present and are serving the function of visual warnings why not add sound warnings as well?
Adding sound notification will help pilots using mobile devices to setup custom sounds to FLARM events or use mobile devices as dedicated flarm monitors with sound alarm.

**Comment by lordfolken** [comment]
XCSoar doesn't conform to a FLARM certified device. See: https://www.flarm.com/wp-content/uploads/man/FTD-013-FLARM-Compatible-Certification-Specification.pdf

In the past the project's stance was specifically to _not_ become a replacement for a FLARM alert device, so not to tempt pilots to replace their Flarm displays with XCSoar.  

Infact XCSoar's FLARM support is only version 4, and even that only is rudimentary.
https://www.flarm.com/wp-content/uploads/man/FTD-012-Data-Port-Interface-Control-Document-ICD.pdf
