### ISSUE TITLE
driver for Becker AR62xx

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#1092]
Here is a driver published for the radio Becker AR62xx. What do think to implement it to the official repository?
https://github.com/eku60/XCSoar/tree/ar62xx_radio/src/Device/Driver

We testet the driver and it works fine.

**Comment by MaxKellermann** [comment]
Where's the protocol documentation?
There's a policy that new code to support commercial products will only be merged into XCSoar if the vendor publishes the protocol documentation non-discriminatory and for free. I think that conflicts with Becker's copyright policy, which is hostile towards their customers - or am I mixing up Becker with somebody else?

**Comment by Blaubart** [comment]
you are right, Becker dosen't allow to publish protocol documentation :-(

**Comment by MaxKellermann** [comment]
Okay then, no support for Becker in XCSoar. Sorry.
Don't buy Becker.

**Comment by Blaubart** [comment]
OK ;-)

**Comment by iltis42** [comment]
> Okay then, no support for Becker in XCSoar. Sorry. Don't buy Becker.

Yeah, that's also what i recommend everybody, hopefully they change their policy at times

**Comment by lordfolken** [comment]
Apossiblity is to install an air avionics  display, which has very good pulbic 3rd party documentation. They support becker afaik. And there is a good driver for the Air Avionics Display in XCSoar.
