### ISSUE TITLE
Unable to load CUP file 

### ISSUE THREAD

**Issue by Nastir93** [XCSoar/XCSoar#1097]
Hi, the app cannot locate a cup file I have downloaded. I moved it into the XCSoar data folder on my phone however under site files in system configuration, nothing is displayed at all. Would there be a reason for this?

**Comment by lordfolken** [comment]
Unfortunarley the xcsoardata is no longer useable in android12 and forward due to google security theater. Open the files app there you will find an xcsoar entry in the sidebar which you csn use to copyvfiles in.

**Comment by Nastir93** [comment]
All I can find in the files app is XCsoar data? Where exactly is this
xcsoar entry /sidebar you mention?

**Comment by lordfolken** [comment]
See #992
