### ISSUE TITLE
Plane Details: Creating a new Profile: the profile of the plane should be empty

### ISSUE THREAD

**Issue by hjr** [XCSoar/XCSoar#1131]
XCSoar versions having and not having the problem
-------------------------------------------------
Head revision of today. Linux desktop, sim mode.

Expected behavior
-----------------
Creating a new Plane configuration should present you an empty form to complete.

Actual behavior
---------------
The New button presents you a form that is entirely filled with the current active plane details.

Steps to reproduce the behavior
-------------------------------
1. Navigate to Config -> Plane
2. Have at least one active plane configuration
3. Press "New"

Do you have any idea what may have caused this?
-----------------------------------------------
Yes, it might be intended. It is a bit unexpected and let you uncertain, which field you changed, which not. In this case I would suggest to label the New button "Clone". May be having still a "New" button.

Do you have an idea how to solve the issue?
-------------------------------------------
Yes.

**Comment by hjr** [comment]
thx!

**Comment by lordfolken** [comment]
Yes thank you.
