### ISSUE TITLE
Errors writing to screen on Kobo Aura 2

### ISSUE THREAD

**Issue by PNich** [XCSoar/XCSoar#1165]
XCSoar versions having and not having the problem
-------------------------------------------------

V2.28 has problem
V2.27 and earlier do not

Expected behaviour
-----------------

No errors writing to screen

Actual behavior
---------------

When running program, text written to the screen gets corrupted.  Location of text is correct, but text itself is corrupted. 

Steps to reproduce the behaviour
-------------------------------
Replay any stored .igc file.  See attached mp4 file. Obvious in bottom right info box, but happens all over different pages

https://user-images.githubusercontent.com/95969204/228310800-3b10bef0-1eed-4527-ba55-5be317ca357d.mp4

 at different times

Do you have any idea what may have caused this?
-----------------------------------------------

Code update to support new Kobo device?

Do you have an idea how to solve the issue?
-------------------------------------------

No

**Comment by lordfolken** [comment]
Is this regardless of the infobox configured?

**Comment by lordfolken** [comment]
@XCSoar/kobo-team any ideas?

**Comment by ubx** [comment]
> Code update to support new Kobo device?
The Libra 2, which was introduced in v7.28, is currently the only suspect. I checked the code for differences between v7.28 and v7.27, focusing specifically on changes related to Kobo stuff, but did not find any problems.

Will it be the same without the Replay box?

**Comment by GeekGoneOld** [comment]
IIRC, there was some work done for the bit density of all devices recently (i.e. correcting old values of BPI).  I haven't looked, just going by memory.  If this is so, I would suggest we look at that.

Have you bisected to find what commit caused it to fail?  That would almost instantly point us to the heart of the problem.

**Comment by PNich** [comment]
Where can I find the latest Kobo build (7.28+) so I can test if the problem is unique to 7.28 or is present in everything after the 7.28 release? (I've downloaded intermediate builds before but can't find them now?)

**Comment by GeekGoneOld** [comment]
You say Aura 2.  Can you confirm that it is an N236.  Go to Nickel | More | Settings | About Kobo Aura.

If you can confirm it is an N236 (Bottom half of page 1 of About), I can help.  I have an N236 and a development environment set up.

**Comment by lordfolken** [comment]
Please try the latest build
You can download it from github actions, for example here:
https://github.com/XCSoar/XCSoar/actions/runs/4729556069
(you need to be signed in to github)

**Comment by PNich** [comment]
Yes they are N236’sOn 23 Apr 2023, at 06:33, GeekGoneOld ***@***.***> wrote:﻿
You say Aura 2.  Can you confirm that it is an N236.  Go to Nickel | More | Settings | About Kobo Aura.
If you can confirm it is an N236 (Bottom half of page 1 of About), I can help.  I have an N236 and a development environment set up.

**Comment by PNich** [comment]
Downloaded from the link thanks.  Tried 7.29 3fe7025 on two different N236’s.

 

On each device 7.29 3fe7025 worked correctly, but 7.28 showed the problem.
