### ISSUE TITLE
Some keys are partially obstructed on XCSoar keyboard

### ISSUE THREAD

**Issue by MikeBravo15** [XCSoar/XCSoar#1172]
XCSoar versions having and not having the problem
-------------------------------------------------

Which XCSoar version are you using when seeing the problem? Latest 7.28
Which XCSoar version is the last one you know that did not show the problem? No sure

Expected behavior
-----------------

All key should be accesible

Actual behavior
---------------

Space and "-"  sign are partially hiden behind other keys

Steps to reproduce the behavior
-------------------------------

Just try to rename XCSoar profile

Do you have any idea what may have caused this?
-----------------------------------------------

No

Do you have an idea how to solve the issue?
-------------------------------------------

No
![Screenshot_20230409-110948](https://user-images.githubusercontent.com/42399455/230783953-efe0d276-9d88-4fdb-af3d-e37e4aa64901.png)

**Comment by lordfolken** [comment]
So i traced the bug to here:
https://github.com/XCSoar/XCSoar/blob/a3e0dd9a725b6b9bee50dd45ec87ead5bc9ebdc9/src/Dialogs/TouchTextEntry.cpp#L201-L205

the keyboard_top variable is about 2x too large (the coordinates in xcsoar's ui toolkit start at the top left)

What weird is that editor_height is about the same height and works correctly. 
This leads me to conclude that the functions interpreting the rc are doing so differently.
