### ISSUE TITLE
Add SkyDrop2 bluetooth device

### ISSUE THREAD

**Issue by fhorinek** [XCSoar/XCSoar#1174]
My name is Fero and I am a developer from SkyBean. Our vario SkyDrop worked with your app when using a classic Bluetooth SPP profile.

During the chip shortages, the old module and also other SkyDrop components became unavailable, therefore we needed to change them.
Bluetooth on SkyDrop2 is HM-BT4502 and it does only support BLE.

Can you please add our device to your application?

The parameters for BLE are:

Service UUID
0000ffe0-0000-1000-8000-00805f9b34fb
Read characteristic UUID
0000ffe4-0000-1000-8000-00805f9b34fb
Write characteristic UUID
0000ffe9-0000-1000-8000-00805f9b34fb

Normally we transfer telemetry using LK8EX1, but we can also emulate DigiFly or BlueFly (selectable in the device).
We can also forward GPS data using standard NMEA sentences (if enabled).

If you need to test it on a device, let me know, and we can provide one.

**Comment by MaxKellermann** [comment]
If you want XCSoar to support your product, write a driver and submit your code in a pull request. The code you will write belongs in this source file: https://github.com/XCSoar/XCSoar/blob/master/android/src/BluetoothSensor.java
If you need help, you know where to ask.
If you ask on IRC, wait until you get a reply instead of leaving the channel after a few minutes. If you leave, you won't see replies.

**Comment by lyusupov** [comment]
@fhorinek 

> The parameters for BLE are: 
> Service UUID 0000ffe0-0000-1000-8000-00805f9b34fb

Your Service UUID does match to the one _(HMSoft HM-10 module)_ which is supported by XCSoar already 

https://github.com/XCSoar/XCSoar/blob/master/android/src/BluetoothUuids.java#L28

> Read characteristic UUID 0000ffe4-0000-1000-8000-00805f9b34fb
> Write characteristic UUID 0000ffe9-0000-1000-8000-00805f9b34fb

but the R/W UUIDs do not match to the XCSoar _(HMSoft HM-10 module))_ ones:

https://github.com/XCSoar/XCSoar/blob/master/android/src/BluetoothUuids.java#L34

**Comment by MaxKellermann** [comment]
So it seems this feature request is bogus because it is already supported, and no reply from @fhorinek in a month.
