### ISSUE TITLE
HGT Map support

### ISSUE THREAD

**Issue by XCNav** [XCSoar/XCSoar#1177]
XCSoar version
--------------

All Versions

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

HGT Map support

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

LXNAV Devices are using high definition HGT Maps. You can download them on LXNAV webpage. Even if LXNAV would make you pay for it, this would be a great alternative to the current open source maps.

**Comment by MaxKellermann** [comment]
You forgot to post the link to the file format specification, and you did not demonstrate the superiority of this file format and the data. You need to be very convincing for people to spend their free time on helping a commercial company earn money.

**Comment by lordfolken** [comment]
Our srtm maps are higher resolution than theirs. What's the point?

**Comment by lordfolken** [comment]
Maybe we should do another release so people see the new contrast settings. IMO map renderer is a lot more capable than is visible with current settings.

**Comment by lordfolken** [comment]
@XCNav what are you missing with current maps?

**Comment by XCNav** [comment]
> @XCNav what are you missing with current maps?

![InShot_20230417_010530045](https://user-images.githubusercontent.com/78668199/232348117-da62e413-8a6c-4f6e-a576-4ac1579d541e.jpg)

I am happy with the default XCSOAR maps. This would just be an alternative for another map source, as the .hgt maps are free to download ont the lx website 
The picture shows about the same area in the ALPS_highres.xcm and the LX HGT Map taken from a screenshot of the LX Website. It seems likebthere is a slightly higher resolution on LXSite and more details.

**Comment by lordfolken** [comment]
That screenshot looks strangley low res:

Here is: 
XCSoar (current master)
ALPS_highres.xcm
Terrain: Vibrant

![2023-04-17-012958_958x1056_scrot](https://user-images.githubusercontent.com/407371/232349408-c2c8ea9a-a451-4d55-a92c-0f5f37dfca2d.png)

**Comment by lordfolken** [comment]
I saw that now almost all of western europe and usa has dem1 data available. Current is dem3. 
http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org1.htm

**Comment by lordfolken** [comment]
https://github.com/XCSoar/mapgen/issues/59

**Comment by MaxKellermann** [comment]
You still didn't reply to my request for a link to the file format specification, and it looks like you won't ever. Without this, your feature request will never be implemented.
