### ISSUE TITLE
Long InfoBox values displayed too small

### ISSUE THREAD

**Issue by Scumi** [XCSoar/XCSoar#1193]
XCSoar versions having and not having the problem
-------------------------------------------------
Issue starts at 7bf77a3b380689f64f0ddfb4ea2dbace072f3115

Expected behavior
-----------------
Long infobox values taking all available space and are therefor shown with a normal size.

![InfoBox_normal_value_size](https://user-images.githubusercontent.com/26870072/234221047-e1327718-0a7b-4dd8-a71c-cb0e9bdea0df.png)

Actual behavior
---------------
Infobox values have a margin around them, which reduces the size of long values.

![InfoBox_small_value_size](https://user-images.githubusercontent.com/26870072/234221044-5121f2a6-4813-43da-b795-2719adcf9630.png)

Steps to reproduce the behavior
-------------------------------
Use infoboxes that can contain longer values (i.e. frequency infoboxes).

Do you have any idea what may have caused this?
-----------------------------------------------
7bf77a3b380689f64f0ddfb4ea2dbace072f3115

Do you have an idea how to solve the issue?
-------------------------------------------
Revert commit (quick fix) or improve logic.

**Comment by Scumi** [comment]
@lordfolken can you have a look?

**Comment by lordfolken** [comment]
Is this infobox frequency only?

**Comment by Scumi** [comment]
According to the linked PR, there could be other infoboxes as well. I need to check which infoboxes might handle "long" values.

**Comment by lordfolken** [comment]
I mean the calculation always was for "1234m" so not really long values. However this is unchanged... sinc ever.

**Comment by Scumi** [comment]
Okay, understood. Nevertheless, the issue starts with this commit for me.
I will check other infoboxes (if I find similar ones) and test a few commits "around" that one if that helps.

**Comment by lordfolken** [comment]
Whats strange here: It should overflow and not remain small.

**Comment by lordfolken** [comment]
Ok, so this is by design:

https://github.com/XCSoar/XCSoar/blob/b1309a96f7bd6707dc369f6264ffb5e8d5872b73/src/InfoBoxes/InfoBoxWindow.cpp#L108-L112

Should the value not fit in the width, the above code will select the small value (the one for the comments size font.

**Comment by lordfolken** [comment]
@Scumi does the above PR fix the issue for you?

**Comment by Scumi** [comment]
Yes, it does.
