### ISSUE TITLE
No package 'fmt' found

### ISSUE THREAD

**Issue by bomilkar** [XCSoar/XCSoar#1200]
XCSoar versions having and not having the problem
-------------------------------------------------

7.29 testing introduced the problem between April 23 and April 28, 2023

Expected behavior
-----------------

"make" should work.

Actual behavior
---------------

"make TARGET=UNIX" fails with
.
.
  BMP     output/data/icons/winpilot_landable.bmp
  BMP     output/data/icons/winpilot_marginal.bmp
  BMP     output/data/icons/winpilot_reachable.bmp
  BMP     output/data/icons/wrench.bmp
  GEN     output/UNIX/include/resource_data.h
  GEN     output/UNIX/resources.c
  UNTAR   boost_1_82_0.tar.bz2
Applying patch /home/ronald/XCS_devl/7.29_newP/XCSoar/lib/boost/patches/ublas_no_serialization.patch
Applying patch /home/ronald/XCS_devl/7.29_newP/XCSoar/lib/boost/patches/no_math_throw
Applying patch /home/ronald/XCS_devl/7.29_newP/XCSoar/lib/boost/patches/no_multiprecision
Now at patch /home/ronald/XCS_devl/7.29_newP/XCSoar/lib/boost/patches/no_multiprecision
Package fmt was not found in the pkg-config search path.
Perhaps you should add the directory containing `fmt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fmt' found
build/compile.mk:108: *** library not found: fmt.  Stop.

Steps to reproduce the behavior
-------------------------------

run "make TARGET=UNIX"

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
It's a new dependency. Install it.
