### ISSUE TITLE
Low res or missing Icon on Desktop versions of XCSoar (WIndows/Linux)

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#1211]
XCSoar version
--------------
7.29 (win64 / linux)

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

When alt-tabbing between applications, usually the application icon is shown.

Linux just shows a generic "application" icon, windows shows one that is of low resolution.
![image](https://user-images.githubusercontent.com/407371/236632667-002569a8-495b-40c1-89c6-94b5cc3ed978.png)

**Comment by MaxKellermann** [comment]
Which Linux build? SDL or X11/EGL?

**Comment by lordfolken** [comment]
```
Starting XCSoar XCSoar v7.32-Linux~git#326ecec41d
GLX config: RGB=8/8/8 alpha=8 depth=24 stencil=8
GL vendor: AMD
GL version: 4.6 (Compatibility Profile) Mesa 20.3.5
GL renderer: AMD SIENNA_CICHLID (DRM 3.49.0, 6.1.0-0.deb11.6-amd64, LLVM 11.0.1)
```

**Comment by MaxKellermann** [comment]
I still don't know

**Comment by lordfolken** [comment]
Two different problems. The xcsoarswift.ico in Data/bitmaps, didn't take modern windows icons into account.

For linux, we are missing a Desktop Entry file that would allow xcsoar be registered in menus of a desktop, such as gnome, both as a menu entry and an application icon.
