### ISSUE TITLE
Vario Gauge and Data displays within gauge scaling very badly

### ISSUE THREAD

**Issue by h4ckerle** [XCSoar/XCSoar#1218]
XCSoar versions having and not having the problem
-------------------------------------------------

XCSoar 7.31 on Windows, Linux

Expected behaviour
-----------------

Vario gauge scaling should be shown that numbers stay within box
Data Displays within Vario Gauge should be centred and big as shown in manual 
![image](https://github.com/XCSoar/XCSoar/assets/76652420/5bd47245-3a47-4f0e-ad4d-a706bf745dd3)
(Image from XCSoar Manual Section 7.1)

Actual behaviour
---------------
Vario gauge scaling is flowing out of box

The shown Data is at the bottom of the Gauge, not centered.
Data becomes illegible due to overlaying with other menu elements

100% Text Scaling
![image](https://github.com/XCSoar/XCSoar/assets/76652420/cb6a5d6f-cd62-40a4-a378-47c834b94aeb)

170% Text Scaling
![image](https://github.com/XCSoar/XCSoar/assets/76652420/2b5bf9d1-f2f3-4d5e-ab10-6c60553c57e1)

Steps to reproduce the behaviour
-------------------------------

Use screen resolution of 480x800
Set Infobox Geometry to 8 Bottom + Vario (Portrait)
Set Vario Gauge to Show MacReady On, Show gross On
(Only part of the issue: Set Text size to 170%)

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by jonpio** [comment]
This issue is NOT resolved, font sizes now ok but 3 lines of text not vertically centered, line 3 below vario ring
