### ISSUE TITLE
Turnpoints not shown

### ISSUE THREAD

**Issue by OBrown92** [XCSoar/XCSoar#1221]
We got some issues with a waypoint file. Many waypoints are not shown. Can someone debug the following file?
[waypoints.cup](https://www.soaringspot.com/de/download-contest-file/4226-27243) 

The Turnpoints 002-006 for example are missing.

**Comment by OBrown92** [comment]
They disappear after a restart of xcsoar. Btw. we are using the latest Android Version from playstore.

**Comment by MaxKellermann** [comment]
The invisible waypoints have no elevation, and your map file cannot provide a fallback value, therefore XCSoar discards the waypoints whose elevation cannot be resolved. This has nothing to do with a new "2022" column order.

**Comment by lordfolken** [comment]
I think this is mainly due to the asynchrpnous loading of the terrain. The fallback altitude is calculated before terrain elevation data is available. 
https://github.com/XCSoar/XCSoar/issues/900
