### ISSUE TITLE
Setting the system time on the OV using GPS.

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#1240]
It seems that XCSoar on the OpenVario does not set the system time using GPS if NTP is not synchronized.
Look at this thread:
https://forum.xcsoar.org/viewtopic.php?f=30&t=4230

**Comment by lordfolken** [comment]
This is really the ntp clients job. It should use both the GPS and ntp server as possible time sources.

Perhaps xcsoar should write the ntp clients config and keep it in sync with the device configuration.

**Comment by MaxKellermann** [comment]
How can a NTP client (= systemd-timesyncd) use the GPS? How does it know where the GPS is connected? How can systemd-timesyncd connect to the GPS while XCSoar is also connected to the GPS? None of this makes sense.

**Comment by lordfolken** [comment]
Then use a real ntp client, such as chrony, instead of the timesyncd stub.
We already use a separate daemon on openvario for variod and xcsoar is only networked in. 
So adding a network or serial connection for gps to that wouldn't be hard either.
A readonly connection is sufficient for chrony, so you can still use another application on top of it. 

your implementation is 
*  depending on DBUS yet another interface. 
*  hardcoded on running XCSoar as uid 0, why even when you are using dbus? (polkit?)
*  be racey, because there may be a lot of interaction on an openvario before xcsoar is launched, upsetting a lot of things that may depend on timestamps. 

In my opinion, this is a clear functional layer violation. A client application should never set the time on a system. (unless that is its purpose)

**Comment by Blaubart** [comment]
I will test the code at weekend

**Comment by MaxKellermann** [comment]
> Then use a real ntp client, such as chrony, instead of the timesyncd stub.

That's wrong. timesyncd is a real NTP client.

>  We already use a separate daemon on openvario for variod and xcsoar is only networked in.

What does "networked in" mean and how is it relevant to this problem?

>  So adding a network or serial connection for gps to that wouldn't be hard either.

How?

>  A readonly connection is sufficient for chrony, so you can still use another application on top of it.

What does "readonly connection" mean? Connection to what? On top of what? What other application?

> depending on DBUS yet another interface.

DBus is a fundamental daemon on the OpenVario operating system. Everything runs on it - systemd (systemctl!), timesyncd and its timedatectl client, networkd/networkctl, and even wpa_supplicant uses DBus. I don't like DBus, but we have to consider the fact it's there and many daemons use it. It's a reliable way to interact with timesyncd. How do you interact with chrony, what interface do you suggest?

> hardcoded on running XCSoar as uid 0, why even when you are using dbus? (polkit?)

I didn't decide that XCSoar runs as uid 0, and it doesn't matter. uid 0 is just a way to detect we're an OpenVario (or similar). It would be preferable for OpenVario to use a different uid, but that's not what it does currently, and once OpenVario changes this, we can adjust XCSoar. Then we can use polkit to give XCSoar permission to adjust the system clock. But ... what's your point here?

> be racey, because there may be a lot of interaction on an openvario before xcsoar is launched, upsetting a lot of things that may depend on timestamps.

True, but what's your solution to this? Using XCSoar to set the system clock in cases where we know we don't have a correct system clock setting is a strict improvement over what we had before. It's not perfect, it doesn't solve everything, but it's better than before. Let's talk about your solution which solves all these problems!

> In my opinion, this is a clear functional layer violation. A client application should never set the time on a system. (unless that is its purpose)

Half-agree, so ... let's talk about your solution!

**Comment by Blaubart** [comment]
Code doesn’t work. Ich used a fresh installed image and disconnect Wi-Fi. I started XCSoar and It was connected with GPS. After couple minutes I made a reboot and checked system time at shell. It was still set to 28.04.22.
