### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by Soaringseven** [XCSoar/XCSoar#1241]
Dear folks, during my last flights the distance calculator (former OLC classic) suddenly adds 100 km or more which hadn't been flown yet. After some time (30 min), the systems recalculates the distance back to the real level.  I use a Xiomi 9c Redmi. In the past, the same smartphone never showed problems with XCsoar. Is it a problem of my smartphone or of the new XCsoar-version? Best regards Holger

**Comment by MaxKellermann** [comment]
Nobody can know because you didn't post enough information. We need at least a NMEA/IGC file which can be used to reproduce the problem in replay. Upload one, but first verify that it can indeed be reproduced.

**Comment by Soaringseven** [comment]
Hi Max,

this is the igc-file produced by XC soar. The distance-skip of about 100 km
happens after km 170.


Mit freundlichem Gruß

Holger Linnartz
Bahnstr. 24a
D- 47929 Grefrath
0174-1730570
02158-4059069


Am Mo., 5. Juni 2023 um 22:51 Uhr schrieb Max Kellermann <
***@***.***>:

**Comment by MaxKellermann** [comment]
There's no IGC file.

**Comment by MaxKellermann** [comment]
No reply
