### ISSUE TITLE
Could not resolve host: api.weglide.org:Couldn't resolve host name

### ISSUE THREAD

**Issue by GuyCorbett170** [XCSoar/XCSoar#1256]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

WEGLIDE is disabled so app should not attempt to contact api.weglide.org

Actual behavior
---------------

When entering Task dialogue get Error message "Could not resolve host: api.weglide.org:Couldn't resolve host name"  

Steps to reproduce the behavior
-------------------------------

Build curent branch and run on Android with no internet connection.  Select TASK

Do you have any idea what may have caused this?
-----------------------------------------------

 May be change described as "net/client/WeGlide/ListDeclaredTasks: new library" 2 weeks ago

Do you have an idea how to solve the issue?
-------------------------------------------

I haven't yet worked out where this new library is called from but it should not be called unless WEGLIDE is enabled in Setup

**Comment by MaxKellermann** [comment]
Fixed in 7d57f9e5259f9f37e240eda6cf791653006771d7
