### ISSUE TITLE
Unable to download zlib

### ISSUE THREAD

**Issue by jirimaier** [XCSoar/XCSoar#1288]
XCSoar versions having and not having the problem
-------------------------------------------------
Since 22. 8. 2023, likely does not depend on XCSoar version

System information
------------------
Cross-compiling for Win64 on Linux

Steps to reproduce the behavior
-------------------------------
make TARGET=WIN64
The build will fail because it can't download zlib-1.2.13.tar.xz.

Expected behavior
-----------------
Existing zlib-1.2.13.tar.xz should be found and downloaded

Actual behavior
---------------
Fails to download zlib-1.2.13.tar.xz

Do you have any idea what may have caused this?
-----------------------------------------------
The file isn't available on either of the URL specified in libs.py:
'http://downloads.sourceforge.net/project/libpng/zlib/1.2.13/zlib-1.2.13.tar.xz'
'http://zlib.net/zlib-1.2.13.tar.xz'

Do you have an idea how to solve the issue?
-------------------------------------------
I found it on
https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.xz

**Comment by MaxKellermann** [comment]
A new zlib version was released and apparently, the zlib people delete old tarballs. You can fix this by updating to 1.3.
