### ISSUE TITLE
No flight log 

### ISSUE THREAD

**Issue by csibeszke95** [XCSoar/XCSoar#1290]
XCSoar versions having and not having the problem
7.39
-------------------------------------------------

 don't know, but I have had logs until 29.06.2023

System information
------------------

Samsung A40 Android version 11
One UI version 3.1
Google play software refreshment 1.06.2023.

Steps to reproduce the behavior
-------------------------------

My daughter cancelled xc soar, I have downloaded again, however no flight log anymore from July. 

Expected behavior
-----------------

I just wanted to see my flight logs

Actual behavior
---------------

No flight log at all in the xcsoar data/logs

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by kobedegeest** [comment]
Might be related to #992

**Comment by lordfolken** [comment]
If you dont select to keep the data when uninstalling.. then thats it. 
![Screenshot_20230825-082300](https://github.com/XCSoar/XCSoar/assets/407371/8353253c-a6b5-42d9-acc5-749c7f89b481)
