### ISSUE TITLE
Glide Advisor

### ISSUE THREAD

**Issue by spin888** [XCSoar/XCSoar#1302]
XCSoar version
--------------

 7.39 Android

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

  Please add a feature like Foreflight's GLIDE ADVISOR.  This feature provides a dynamic shape (e.g., circular shape) around your aircraft that shows you where you can glide to.  This would be tremendous to have for soaring.  Essentially, it gives you your glide distance projected on your map graphically so you can see where you can land nearby given changes in your altitude.  

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------
A GLIDE ADVISOR will tell soaring pilots where they can make it to in a glide. 

This would make cross-country soaring tremendously easier because you could look down at your map and see what alternates, turn points, and other landing areas you can make.  (See this video:  https://youtu.be/Z5BQnbIKqh4 )

**Comment by DanD222** [comment]
This feature is already implemented, please see section 4.12 “Glide range line” on page 44 of the manual: https://download.xcsoar.org/releases/7.38/XCSoar-manual.pdf

It’s also a good idea to enable the “Arrival height” information for landables (page 147)
