### ISSUE TITLE
Vario Gauge and Data displays within gauge scaling very badly, No vertical centering 

### ISSUE THREAD

**Issue by jonpio** [XCSoar/XCSoar#1304]
XCSoar versions having and not having the problem
-------------------------------------------------

System information
------------------

Steps to reproduce the behavior
-------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by lordfolken** [comment]
Empty issue?
