### ISSUE TITLE
Error while building for Android/IOS

### ISSUE THREAD

**Issue by MikcaelX** [XCSoar/XCSoar#1331]
Firstly I would want to apologize for opening a GitHub issue for my problem because the forum would be more appropriate for this topic, but it is unreachable for me ([screenshot](https://imgur.com/28AB2qf))
I'm new to this project and not familiar with the usage of make files

XCSoar versions having and not having the problem
-------------------------------------------------

Latest

System information
------------------

Ubuntu 20.04.2 (VM)

Steps to reproduce the behavior
-------------------------------

I have downloaded the source code using : 
`git clone https://github.com/XCSoar/XCSoar`

Then installed the following requirements : 
```
    make
    librsvg2-bin xsltproc
    imagemagick gettext sox
    git quilt zip
    m4 automake
    clang
```

And finally executed the following command : 
`﻿make TARGET=IOS64 ipa`

Expected behavior
-----------------

A .ipa file should be created and usable

Actual behavior
---------------

﻿

```
mikcael@mikcaelubuntu:~/XCSoar$ make TARGET=IOS64 ipa
./build/thirdparty.py ./output/IOS64/lib aarch64-apple-darwin
-miphoneos-version-min=10.0 -arch ar
m64 -target aarch64-apple-darwin" "-I./output/IOS64/include -DHAVE_POSIX -DHAVE_VASPRINTF -isystem /output/IOS64/lib/aarch64-apple-darwin/include -DEYE CANDY -DXCSOAR TESTING -isystem /include" "-st dlib=libc++" "clang" "clang++" ar "rcs" ranlib strip "windres"
Traceback (most recent call last):
File "./build/thirdparty.py", line 37, in <module>
from build.libs import *
File "/home/mikcael/XCSoar/build/python/build/libs.py", line 3, in <module>
from build.zlib import ZlibProject
File "/home/mikcael/XCSoar/build/python/build/zlib.py", line 4, in <module>
from build.makeproject import MakeProject
File "/home/mikcael/XCSoar/build/python/build/makeproject.py", line 7, in <module> class MakeProject (Project):
File "/home/mikcael/XCSoar/build/python/build/makeproject.py", line 22, in MakeProject def get_make_args(self, toolchain: AnyToolchain) -> list [str]:
TypeError: 'type' object is not subscriptable
make: *** [build/thirdparty.mk:31: output/IOS64/lib/stamp] Error 1
mikcael@mikcaelubuntu:~/XCSoar$

```
([screenshot here](https://imgur.com/a/JxxAkkO))

Do you have any idea what may have caused this?
-----------------------------------------------

No idea, but the same happen when trying to build for Android.

Do you have an idea how to solve the issue?
-------------------------------------------

No idea.

**Comment by lordfolken** [comment]
Please have a look in the respective workflow files in  .github/workflows/build-native.yaml , perhaps there you find the information that you need.
