### ISSUE TITLE
P and R airspace are not managed properly

### ISSUE THREAD

**Issue by delta217** [XCSoar/XCSoar#1341]
Hello,

I use XCSoar 7.41.
I have the same issue with my Galaxy S5 and S10 (Androïd 9).

Since the extended format is used in openair, with AC and AY lines, the P and R zones are considered as "unknown" by XCSoar.
Hence, they appear in cyan instead of the traditional red.

Thanks for your help, XCSoar is great anyway ! 

![Screenshot_20240201_2](https://github.com/XCSoar/XCSoar/assets/154979750/c7e29745-da80-4bfc-a7f1-c90cd806b5ce)

**Comment by lordfolken** [comment]
@ubx maybe one for you?

**Comment by llauner** [comment]
Similar to #1340

**Comment by lordfolken** [comment]
duplicate #1340
