### ISSUE TITLE
Forum: Performance is low was: No posts / replies possible 

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#1344]
![image](https://github.com/XCSoar/XCSoar/assets/407371/a3715dff-aa7d-45ba-9cce-135914d782c8)

The textbox isn't properly specified, and not accessible.

**Comment by lordfolken** [comment]
maintenance page set for the moment.

**Comment by lordfolken** [comment]
phpBB upgraded to 3.3.X
still looking at performance issues.

**Comment by paynterf** [comment]
Nice to know I'm not the only one seeing this ;)

**Comment by lordfolken** [comment]
It refuses to work with any smaller php memory limit than 512mb. The debug output suggests a maximum of 98mb usage. 
Phpfpm seems to be stuck for 5-7s due to memory unmap, according to strace. Possibly because the box us trashing due to 1gb of memory. 
@afp any ideas?

**Comment by paynterf** [comment]
Move it to another box with > 1GB temporarily, to rule in/out RAM as the culprit?

**Comment by lordfolken** [comment]
I deployed it in a local vm with 4gb of memory. Everything works, except that its very slow.

**Comment by paynterf** [comment]
Nice!  So definitely a RAM issue?

**Comment by lordfolken** [comment]
No still slow.

**Comment by lordfolken** [comment]
Andreas Pfaller sent me the following:

just for info: I fixed some issues with forum.xcsoar.org

+ Increased php memory limit in /etc/php/8.2/apache2/php.ini
+ enabled module log_forensic
+ modified /etc/apache2/sites-available/forum.xcsoar.org-ssl.conf
  - renabled SSL and forensic logging
  - added the "access-rules" include
+ added the required include files for the access-rules config to /etc/apache
+ patched phpbb (with the patch which was already present in 
  /root/xcsoar-forum-phpbb-session.diff on the server) to reduce
  memory used by phpbb ridiculous caching method. Because of this
  the first change in this list could probably be reverted, I have not
  tried it yet.

This last patch really fixes the performance.

**Comment by lordfolken** [comment]
```
just for info: I fixed some issues with forum.xcsoar.org

+ Increased php memory limit in /etc/php/8.2/apache2/php.ini
+ enabled module log_forensic
+ modified /etc/apache2/sites-available/forum.xcsoar.org-ssl.conf
  - renabled SSL and forensic logging
  - added the "access-rules" include
+ added the required include files for the access-rules config to /etc/apache
+ patched phpbb (with the patch which was already present in 
  /root/xcsoar-forum-phpbb-session.diff on the server) to reduce
  memory used by phpbb ridiculous caching method. Because of this
  the first change in this list could probably be reverted, I have not
  tried it yet.
```
