### ISSUE TITLE
Airspace list has poor text contrast

### ISSUE THREAD

**Issue by Turbo87** [XCSoar/XCSoar#1371]
XCSoar versions having and not having the problem
-------------------------------------------------

> Which XCSoar version are you using when seeing the problem?

v7.41 WIN64

> Which XCSoar version is the last one you know that did not show the problem?

I'm not sure, but I don't remember seeing this issue last year.

Steps to reproduce the behavior
-------------------------------

Click on an airspace

Expected behavior
-----------------

I expect the text to be the same color for all airspaces

Actual behavior
---------------

The airspace color is used for the text, which makes it very hard to read for some airspaces.

<img width="1062" alt="Bildschirmfoto 2024-03-07 um 23 10 27" src="https://github.com/XCSoar/XCSoar/assets/141300/d9e4c109-9064-4fe0-8d5a-c2da1bdfc405">

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by lordfolken** [comment]
I agree. Colored text should be antialiased or as in this case simply black.

**Comment by lordfolken** [comment]
This is a windows only bug. Linux / Android display black text.

**Comment by lordfolken** [comment]
@August2111 could you have a look?

**Comment by Turbo87** [comment]
Huh, indeed. I could've sworn I saw that on Android too but I must've dreamt that 😅

**Comment by August2111** [comment]
... but I found this issue in very old XCSoar versions too, the 1st I have checked was v6.8.17 ;-)
So I think the problem isn't so big, because up to now I saw only one system with a windows-openvario in a glider...

**Comment by lordfolken** [comment]
I guess it was well hidden as it almost looked like a feature.

While I no longer see windows based systems in gliders, I know that the VR e-sport users would surley be happy.
