### ISSUE TITLE
is it time to improve Circling Wind calculation?

### ISSUE THREAD

**Issue by bomilkar** [XCSoar/XCSoar#1388]
XCSoar version
--------------

7.42

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

The current implementation of the circling wind calculation has some room for improvement. The comments in src/Computer/Wind/CirclingWind.cpp suggest this already. For instance, it assumes “the pilot flies in perfect circles” and “with constant airspeed”. Also, the calculation of the wind bearing can be improved.

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

I have a prototype running which implements the following:
1. it uses changes in turn rate to validate the assumption of perfect circles.
2. it uses true airspeed to compensate for changes.
3. it uses an iterative fitting to determine the bearing of the wind.

1. to evaluate the level of perfection of the circle, it uses the track information from the GPS. This works reasonably well as long as the wind speed is small enough compared to TAS (maybe 1/3). GPS receivers are black boxes wrt their ability to cope with changes in track and ground speed: how quickly will the values in the GPRMC sentence follow the real movements of the ship? However, future implementation may use turn rate information from gyros of simple/inexpensive IMUs. That change will make sense as soon as IMUs have a better support in XCSoar and are more widely available.

2. my assumption is that airspeed information is available in many installations. So it uses ground_speed – airspeed instead of just ground_speed from the GPS reciever. However, the prototype works even if TAS is not available (or derived). In that case it lacks that compensation.

3. in an ideal case, the speed oscillates in a sine curve. So fitting the actual speed values of a given circle to a sine curve usually provides better results for the wind direction.

I’m running the prototype in Replay mode using files from the “NMEA logger” which I usually capture during my flights. So far results look promising.

How shall I proceed? Shall I post a PR? I would like to get your feedback, even though the implementation is far from final.

**Comment by lordfolken** [comment]
In general this sounds interesting. Open a dratft PR.
Please follow xcsoars git rules. Small building block changes that build with well crafted commit messages.  
https://xcsoar.readthedocs.io/en/latest/policy.html#code-style

**Comment by bomilkar** [comment]
Thanks for the feedback, @kobedegeest 

I also have doubts about what a GPS receiver can reliably deliver. As you said, it is a third order derivative and the quality of the results can vary greatly depending on operating conditions, brand and type. For this reason, I have started to analyze the replay results of different flights. Although it looks promising, there are still cases where I get unexpected results from CalcWind.

I don't buy your assumption "avg(v_x) = w_x and avg(v_y) = w_y in general i think whether you fly circle or ellipse or any other closed shape". The effect is that a perfect circle in the air is an ellipse on the ground. The shape of the ellipse can be used to determine the wind. That's the underlying principle of circling wind, I guess.

I remain convinced that you can distinguish between a (near) perfect circle and an arbitrary pattern (to move the center point while circling) based on the ship's rate of turn. Certain GPS receivers may not provide sufficient track data to derive a useful rate of turn. But even simple IMUs with their gyros should suffice. Fortunately, my algorithm doesn't care where the turn rate comes from.

**Comment by bomilkar** [comment]
One more point, which might also affect the ZigZag algorithm: ground speed and TAS might have different delays in the signal processing chain. In my case it seems to be around 2 sec, which I noticed looking at the InfoBoxes when I replayed a takeoff.
TAS comes 2 sec after VGND. While circling that translates to ~30° difference in heading.

**Comment by bomilkar** [comment]
I'm trying to get away with GPS (and optional airspeed) only. But I may not succeed.
A good percentage of Android phones have built in IMUs. But I have no clue how to get (raw) data from it. It should be possible, though,
I don't want to stick a ton of data into a kalman filter (with 10 - 15 dimensions). I'd rather use my physical understanding of the problem instead of brute force compute power.
For me it's not just the first few circles where I try to find the best climb rate. I adjust quite often. And I found the change of turn rate (even if it's 3rd order derivative from GPS) to be quite good to identify "perfect" circles.
I'll post a draft PR in the coming days. I just to run a few more flights with it. Unfortunately speeding up the replay doesn't work.
BTW: I really appreciate the discussion! Are you the author of the current implementation of CirclingWind ?

**Comment by bomilkar** [comment]
I'm submitting the code changes.
First draft PR #1390 is to compare the results of different wind algorithms. It is in a CSV format to load for processing after the replay of the nmea file.
Columns are:
1. time in seconds since 00:00 UTC
2. flight mode: 1 == circling, 0 == forward
3. wind speed in user units
4. wind.bearing in degrees
5. baro_altitude in user units

This PR is for analyzing results, not intended to include in production.

**Comment by bomilkar** [comment]
Got stuck with github (again).
I created a new branch bomilkar:new_circling_wind and added 4 commits:
ddcf81ee9acbf12764a3896678ef482b2a8264b2
37044ee2466591593765daa23cb6cb99aeec3c8c
cb566273a6d129da931b42dcaf8afdc05df727e1
1fb6a91da59ebf9fd129f0f7005ff898d33356b8

The PRs build on top of each other.
After the first commit I created PR #1390
Now that I'm at this point I can't create any more PRs (for any of the remaining commits).
And I can't figure out what's wrong! **_Any idea?_**

**Comment by bomilkar** [comment]
Just complete the 2nd attempt to submit the stuff.
#1391
To be safe, I included the 2 commits in one PR. (Had trouble with that on the first attempt.)
Any feedback is highly appreciated!

**Comment by bomilkar** [comment]
Thank you very much, @lordfolken !
Is there a good (and concise) description on how to use git and github together?

**Comment by bomilkar** [comment]
> I believe there is a mistake in your reasoning. You look at change in direction of track to determine quality of circle. You assume that this should be a constant. But track is Heading plus Wind. And indeed change in heading when flying nice circles is constant but that does not imply that change in track is constant just like your ground speed changes during a circle due to wind also the change in angle track changes. (Unless you do account for that somewhere and i missed it)

I'm aware of this. The changes should be small, not 0. And it works as long as wind_speed is sufficiently low. That's why I wrote "wind_speed < TAS/3" . That's what I confirm in my replays.
One way to account for this is to use turn_rate from a gyro. But gyros aren't widely available.
One other way would be to look at the max difference between ground_speed and TAS. That gives an indication if method is still valid. (Not yet implemented.)
The nice thing about the new algorithm: it need just GPS. Airspeed sensor is good to have. And just hoping the "pilot flies perfect circles" and "keeps constant speed" is addressed and no longer just an invalid assumption.

**Comment by bomilkar** [comment]
You can calculate the quality metric on paper using geometry and trigonometry, But that doesn't take into account what happens inside the GPS receiver. We discussed that earlier.
I have no flight logs for wind speeds higher than 35 km/h. That's how I determine "wind_speed < TAS/3". However, it doesn't mean it won't work at higher wind speeds.
Best is to replay various flight logs and review the results. I encourage you to do that if you have nmea files with air speed.

The quality number which is fed into Store has 6 distinct levels: 0 - 5. I translate the "roundness" of the circle (circle_quality_metric) and the fit to the cosine curve (min_fit_metric) into these 6 level. I have to admit, there is no elaborate theory behind that. And there should be more experiments to validate or improve that. Food for thought!

**Comment by bomilkar** [comment]
Do you have a testbench ready to use? That was one of the next things on my to-do-list and would be happy to use yours if you want to share.
The testbench should instantiate the DUT, pretty much the same way as in Computer.cpp together with Store. And a testvector generator, which should be able to generate deterministic and random pattern, mostly to see how it behaves in corner cases. It should also be able to generate pattern from an NMEA file. (But much faster than replay!) However, deterministic pattern will most likely not reflect what happens inside the GPS receiver. I guess it derives track and ground speed from the fixes (3rd order derivative...). But I don't think the manufacturers will share a spec. Maybe high precision GNSS receivers use other methods (like doppler) which might deliver much better track and speed results. There is no choice than to use NMEA files to simulate realistic scenarios.

If nothing remains from my experiments, I think at least the method to calculate the magnitude of wind speed should go into CirclingWind.cpp . It is indeed much better. In fact, it is good enough so that an additional fitting loop will probably not improve the result (beyond the noise level). BTW: look at CirclingWind2.cpp line 223. There is the TO DO note on that subject.

**Comment by bomilkar** [comment]
"you miss 50% of the gps fixes" that's very unlikely in any scenario. So the sampling rate is constant at 1 per sec.
I also noticed the results getting worse at lower wind speed. Strange. I need to figure out what happens. It's clear the wind bearing is meaningless at low speed (below 1 m/s). But above that it should work. Maybe a mistake in the code?

**Comment by bomilkar** [comment]
Consider this: average of angle == 180° if it's a full circle. No matter what.
You can compute w_x = mean(v_x), w_y = mean(v_y) but there is no information on the associated angle. Therefor w_x / w_y has nothing to do with a direction of the wind.

**Comment by bomilkar** [comment]
What exactly do you call "mean()" ?? Average, or Median, or what?

"w_y/w_x is tangens" is true, but only if w_y and w_x are orthogonal. Hence w_y and w_x must be vectors, not scalars.

Average is a scalar, not a vector.

Good luck if you want to deliver a proof. I'll be curious to see that.

**Comment by bomilkar** [comment]
a = g + w
thus g = a - w

You can multiply vec * scalar.
But you can't add vec + scalar
As stated before avg() is a scalar.

avg(a*cos(alpha) + wx) = a*avg(cos(alpha)) + wx
this is wrong.
Same for y.

Your calculation of avg(gx) and avg(gyx) are wrong. It should be a * x.
And what is gxy ??

**Sorry, but your proof doesn't hold.**

**Comment by bomilkar** [comment]
You're calling me stubborn, etc. I don't take that!
I stop here.

**Comment by lordfolken** [comment]
Why don't you guys plan a session together via some telefconferencing tool and start charting here on how the current or a new algorithm could be implemented.
I think the asynchronous format here, only leads to conflicts, while creating an idea together would work better.

**Comment by bomilkar** [comment]
Thanks @lordfolken for chiming in!
I agree that this platform is only partially suitable for facilitating a discussion like this. But I'm not convinced that a conference call would be better. I'm open to trying it, but ask for a certain amount of respect.
However, we should use github where it is good: when collaborating on actual code: If someone has an idea, they are welcome to implement it and put it up for discussion.

**Comment by bomilkar** [comment]
@lordfolken : how can I proceed?

After extensive tests I’m now happy with the new CirclingWind algorithm. I have tested:
1. the new algorithm on a testbench in various scenarios
2. replay in XCSoar of 5 flights with a totals of ~25 hours flight time, in various scenarios comparing results vs the old CirclingWind algorithm and vs ZigZag, with and w/o TAS input

The bottom line:
The new CirclingWind algorithm behaves more robustly than the old one, which manifests itself in 2 symptoms: 1. there are fewer "erratic spikes" and 2. the result is less susceptible to the courses, regardless of whether it is a headwind or a tailwind. (2nd was one my main motivators to rewrite the algorithm. With the old wind calculation I noticed quite often that it underestimated the wind on a tailwind course and overestimated the wind on a headwind course. It didn’t always happen but it was very annoying.)
Although I haven’t seen any cases where it produced worse results, but of course this new algorithm needs a lot more testing. BTW: I’ve created my own build and will fly with it.
I have not replayed any flights with wind speed over 40 km/h. And I have only tested it with one particular GPS receiver (Power FLARM). These are probably the most important tests still missing.

If you are interested I would like to share and discuss the results of the replays in a teleconference. Just let me know.

On a related topic: running both Circling and ZigZag wind calculations simultaneously doesn’t seem to be a good idea. There is one gliding-average unit which is fed by either Circling or ZigZag depending on the flight phase. But these 2 calculations’ results are different since they measure different winds: one measures the speed at which the thermal moves the other measures the speed at which the air in between thermals is moving. The first is usually slower compared to the second. Hence, the gliding-average unit’s input switches back and forth between “different” winds. The result is a mix of “apples and oranges”. We should rethink this. For me I draw the conclusion that I will not switch on both Circling and ZigZag at the same time.

**Comment by bomilkar** [comment]
Here is some insight related to the quality metrics discussion under #1391 . I copied some of the xcsoar.log files to a DropBox:
[xcsoar.log files](https://www.dropbox.com/scl/fo/djbd5a5e13hycrikv9i13/AOQHeh9hNp0TmrFQTY5Uads?rlkey=2w940gmribh20ox360024lkag&dl=0)
In there you find LogString() outputs from src/Computer/ConditionMonitor/ConditionMonitorWind.cpp (after the commit https://github.com/XCSoar/XCSoar/pull/1391/commits/bc40b2f437b57933fc30e84b2f60f2302098f5e5 ) which reflects what the pilot sees in the Wind InfoBox in 10 sec steps. (in addition to time and altitude)
Then there are the "CalcWind2 circling:" entries which come from the LogString() calls in src/Computer/Wind/CirclingWind2.cpp These give you some insight into the **quality metrics** and input into the gliding average unit.
The dates in the filenames reflect the date of the flight as posted on WeGlide.
The part "_noAS" stands for no TAS. I simply removed the lines containing airspeed data from the nmea file.
Hope that helps.
Let me know if you like to see anything else.
If you are interested in how the **quality metrics work at higher wind speed**, then look at 2023-07-17.

**Comment by bomilkar** [comment]
Good catch!
I misunderstood AbsoluteDegrees().
QM should never be negative.

**Comment by lordfolken** [comment]
> @lordfolken : how can I proceed?

First bring the PR up to shape. No codacy or other issues.

**Comment by bomilkar** [comment]
> First bring the PR up to shape. No codacy or other issues.

Will do.
Can I run Codacy alone? I don't want to waste CPU-cycles on builds while I'm iterating on Codacy issues.
Can you give me a hint how to get rid of issues like "struct/class member 'xxx' is never used" in hpp files?

**Comment by GuillermoHazebrouck** [comment]
I am also interested in this topic, but for a different project. It is true that you don't need this algorithm when there is barometric altitude, heading and airspeed available. If you have all that, you can make the corrections for the TAS and just solve a triangle. If you lack one of those, then you still might want to fall back on circling however, and even try to enrich the algorithm with whatever data that is still available.
I have actually implemented an algorithm based on the rate of turn and tested it in a simulation a few times a few years a go, and it seemed to give fairly good results, even when the circles were not perfect. What I do is scanning the history to find a sample where the rate of turn remains within certain bounds. The rate of turn I use is computed by taking the average course variation. The course is the one given by the GNSS, falling back to an own computation if the GNSS is not providing it. Then, I use homologous points in the trajectory to evaluate the drift and take the mean value over the sample. The algorithm is quite simple and robust, but it has obviously some pitfalls.
Another solution I was considering is to collapse the cycloid to a circle using a collapsing function and minimum squares. This would in theory help to better understand the quality of the data and to dismiss trajectories that are not well suited.
Based on my general experience I can tell that increasing the complexity of a program will not necessarily yield better results. If you are dealing with noisy data and you don't understand the nature of the noise or the behavior of the system, then you will not be able to improve the predictions. In this case, the best is to evaluate the input and only to produce an output when the data looks clean. You could evaluate this statistically for example. An algorithm that throws a value without evaluating the quality of the data is an "arrogant" algorithm, and you should try to avoid that. It is better to return "I don't know" than "trust me, this is the answer".

**Comment by bomilkar** [comment]
@GuillermoHazebrouck thanks for the feedback!
Several of the implementation details you mention sound familiar and are in my current version of the circling algorithm.
I've been testing it in simulations (a lot) and in flight (not as much as I would like to): the results are good and address issues which I had with the old algorithm.
Taking the rate of turn from the GNSS is a bit obscure, for reasons that have been described above. Therefore I'm currently testing the algorithm with the rate of turn from a gyroscope. Surprisingly enough it makes nearly no difference for the testcases I have tried so far. These testcases have wind speeds up to 22 km/h and TAS around 100 km/h.
You mention a different project. Which one is this?
Are you interested in looking deeper into this project here?
