### ISSUE TITLE
Possible null pointer dereference

### ISSUE THREAD

**Issue by Exadios** [XCSoar/XCSoar#139]
In src/Form/DataField/Prefix.cpp, PrefixDataField::GetAsDisplayString() it is possible that 's' is null.
    const TCHAR *s = DataFieldString::GetAsDisplayString();
    if (StringIsEmpty(s))

**Comment by MaxKellermann** [comment]
How can this happen?

**Comment by MaxKellermann** [comment]
Closing due to lack of feedback.

**Comment by Exadios** [comment]
I thought that this issue had been closed some time ago.

What feedback where you expecting?

**Comment by MaxKellermann** [comment]
#140 was closed two weeks ago, because it was the wrong approach to fix this bug report.
I was expecting feedback as in "answering my question".

**Comment by Exadios** [comment]
OK. But I will have to go over it again.

WRT XCSoar I'm presently working on a program termination and (what I am supposing to be) associated valgrind so I'll continue with that.
