### ISSUE TITLE
RMZ and class G do not show as filter option in Airspace list page

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1398]
XCSoar versions having and not having the problem
-------------------------------------------------

noticed in v7.40-android based on code likely still present in current version 7.42

System information
------------------

android 10

Steps to reproduce the behavior
-------------------------------

Open xcsoar
Go to airspace list dialoge/page
click on the type filter
see that RMZ and class G are not listed

Expected behavior
-----------------

RMZ and class G to be listed just like all other options that are configurable in the settings for airspace coloring.
Or to be included in the "Other" options but this one only lists Unknown's (but this naming not being consistent is probably different issue)

Actual behavior
---------------

RMZ and class G can not be used to filter the airspace list.

Do you have any idea what may have caused this?
-----------------------------------------------

static constexpr StaticEnumChoice type_filter_list[] = {
  { WILDCARD, _T("*") },
  { OTHER, _T("Other") },
  { RESTRICT, _T("Restricted areas") },
  { PROHIBITED, _T("Prohibited areas") },
  { DANGER, _T("Danger areas") },
  { CLASSA, _T("Class A") },
  { CLASSB, _T("Class B") },
  { CLASSC, _T("Class C") },
  { CLASSD, _T("Class D") },
  { NOGLIDER, _T("No gliders") },
  { CTR, _T("CTR") },
  { WAVE, _T("Wave") },
  { CLASSE, _T("Class E") },
  { CLASSF, _T("Class F") },
  { TMZ, _T("TMZ") },
  { MATZ, _T("MATZ") },
  nullptr
};
They are not in the hard coded list of filter options.

Do you have an idea how to solve the issue?
-------------------------------------------

add them to the list.

**Comment by ubx** [comment]
The latest release is v7.42. Please do not report issues for older versions.

**Comment by ubx** [comment]
Only facts are helpful to solve issues, not beliefs.

**Comment by lordfolken** [comment]
Indeed that list is hard coded in the GUI . :/

[src/Dialogs/Airspace/AirspaceList.cpp -L ](https://github.com/XCSoar/XCSoar/blob/689df5356b83ed418d058621cf2dd3b2f4d9125d/src/Dialogs/Airspace/AirspaceList.cpp#L150-L168

IMO this should draw on a central definition of airspaces, filter for airspaces that are acutally currenlty loaded and present those.

**Comment by lordfolken** [comment]
Another option would be to add the assert check https://github.com/XCSoar/XCSoar/blob/689df5356b83ed418d058621cf2dd3b2f4d9125d/src/Formatter/AirspaceFormatter.cpp#L29
for the UI as well.

**Comment by lordfolken** [comment]
![image](https://github.com/XCSoar/XCSoar/assets/407371/44d557b2-7ce4-48fc-8a78-24a6b28a77c9)

So this will update the list filter to what was missing. 

However a lot more work is needed to add all the extended airspace types now available from openaip.
