### ISSUE TITLE
make TARGET=ANDROID      did not work

### ISSUE THREAD

**Issue by hatietz** [XCSoar/XCSoar#144]
tietz@tietz-EX58-UD5:~/XCSoar$ make TARGET=ANDROID
./build/thirdparty.py ./output/ANDROID ANDROID arm-linux-androideabi arm-linux-androideabi "-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fpic -funwind-tables -target armv7a-none-linux-androideabi -gcc-toolchain /home/tietz/opt/android-ndk-r18-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -integrated-as" "-I./output/ANDROID/include -DHAVE_POSIX -DHAVE_STDINT_H -DHAVE_UNISTD_H -DHAVE_VASPRINTF --sysroot=/home/tietz/opt/android-ndk-r18-beta2/sysroot -isystem /home/tietz/opt/android-ndk-r18-beta2/sysroot/usr/include/arm-linux-androideabi -DANDROID -D__ANDROID_API__=21 -isystem ./output/ANDROID/lib/arm-linux-androideabi/root/include -DEYE_CANDY -DTESTING -DBIONIC -DLIBCPP_NO_IOSTREAM " "-Wl,--no-undefined -L/home/tietz/opt/android-ndk-r18-beta2/platforms/android-21/arch-arm/usr/lib -B/home/tietz/opt/android-ndk-r18-beta2/platforms/android-21/arch-arm/usr/lib -Wl,--fix-cortex-a8 -Wl,--no-warn-mismatch" /home/tietz/opt/android-ndk-r18-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/clang /home/tietz/opt/android-ndk-r18-beta2/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ /home/tietz/opt/android-ndk-r18-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar "rcs" /home/tietz/opt/android-ndk-r18-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib /home/tietz/opt/android-ndk-r18-beta2/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
Applying patch /home/tietz/XCSoar/lib/proj/patches/no_programs.diff
patching file src/Makefile.am
Hunk #1 succeeded at 1 with fuzz 2.

Now at patch /home/tietz/XCSoar/lib/proj/patches/no_programs.diff
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
Traceback (most recent call last):
  File "./build/thirdparty.py", line 140, in <module>
    x.build(toolchain)
  File "/home/tietz/XCSoar/build/python/build/autotools.py", line 96, in build
    build = self.configure(toolchain)
  File "/home/tietz/XCSoar/build/python/build/autotools.py", line 46, in configure
    subprocess.check_call(['aclocal'], cwd=src)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'aclocal'
build/thirdparty.mk:45: recipe for target 'output/ANDROID/lib/arm-linux-androideabi/stamp' failed
make: *** [output/ANDROID/lib/arm-linux-androideabi/stamp] Error 1

**Comment by MaxKellermann** [comment]
Install automake

**Comment by hatietz** [comment]
yes, it worked. You doing a very good job, Thank you.
Uuups habe Ihre Home Page gesehen. Hut ab vor Ihrer Konsequenz.
Schade, dass Sie nicht mehr fliegen,aber nachvollziehbar. Ich habe  es mit 60J noch angefangen.
