### ISSUE TITLE
Waypoint Details Dialog: Frequency Buttons should only be enabled when there is a frequency defined

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#1444]
![image](https://github.com/XCSoar/XCSoar/assets/407371/2d1e20b7-8241-4886-8a2d-2169804c03ec)

**Comment by DanD222** [comment]
My use-case is to set the frequency via the Alternates dialog, i.e. I want to set the frequency of an airport I’m close to, and don’t see much need to set a frequency of a far-away waypoint. 

At least not often enough to warrant moving the two buttons to the first page, and thus have a longer list to navigate through on the first page via a stick.

**Comment by lordfolken** [comment]
Thanks for your work @kobedegeest :-)
