### ISSUE TITLE
Start-Up Screen

### ISSUE THREAD

**Issue by hag3fe** [XCSoar/XCSoar#1453]
XCSoar versions having the problem
-------------------------------------------------

7.42 PC

Which XCSoar version are you using when seeing the problem?
-->7.42 PC

XCSoar versions not having the problem
<7.40 PC

Which XCSoar version is the last one you know that did not show the problem?
7.40

System information
Windows 10

Steps to reproduce the behavior
Start XCSoar 

Expected behavior
Button is visible and question for mode is coming up

Actual behavior
When starting XCSoar on the PC (Windows 10) the mask looks as shown in the picture.
After a click on the (invisible) button XCSoar starts. But there is no question "Fly | Sim"
Sometimes a strange graphic form is appearing. Same form appears for short time when shutting down

Do you have an idea how to solve the issue?
no

![Screenshot 2024-05-22 113502](https://github.com/XCSoar/XCSoar/assets/148999660/0ed6eced-c3e1-4e12-b7a6-aaf271298075)

**Comment by lordfolken** [comment]
I replaced both binaries (PC/WIN64) with working 7.42 editions.
