### ISSUE TITLE
Airspace list Type filter incorect

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1482]
XCSoar versions having the problem
-------------------------------------------------

As of #1349 

XCSoar versions not having the problem
-------------------------------------------------

System information
------------------

Steps to reproduce the behavior
-------------------------------

Use airspace file with extende type field as well as old abuse of AC field have some airspaces have CTR as type some as Class.
Go to airspace list.
For type chose "CTR"
Notice only the airspces with class CTR show up 

Expected behavior
-----------------

Have airspace show up regardless if CTR is defined in AC field or AY field. 
We probalby need to add an extra filter for the actual type and rename the current one to Class.

Actual behavior
---------------

The type filter only looks at the Class of the airspace not the type

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Add extra filter

**Comment by ubx** [comment]
> Use airspace file with extende type field as well as old abuse of AC field have some airspaces have CTR as type some as Class.

Please provide the two airspace files to reproduce the issue.

**Comment by lordfolken** [comment]
@kobedegeest can you test the linked pr?
