### ISSUE TITLE
Airspace coloring wrong when both AC and AY field present

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1483]
XCSoar versions having the problem
-------------------------------------------------
As of #1349 

XCSoar versions not having the problem
-------------------------------------------------

System information
------------------

Steps to reproduce the behavior
-------------------------------

Have airspace file with AC and AY field both valid inputs exampel AC C AY CTR
In settings pick some color and border for this class and some other collor border and pading for the type.

Expected behavior
-----------------

The color on the map of the airspace and the border and fill type is based on the airspace type. So it matches how they show up in list.

Actual behavior
---------------

For the border the settings of the Airspace type is used for the padding/filling the settings of the class is used.
When looking at list type menus with airspaces listed the coloring is solley based on type

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by fraktal-sb** [comment]
the following screencopys are taken from v7.42 and the rc0.7.43 on KOBO Glo HD.
TMZ is different (color) coded.
should we create a different issue for this or leave it here?
![v743v743](https://github.com/XCSoar/XCSoar/assets/69430537/89acd0d1-9dd0-47b6-b8fc-af66d4ba9e3d)

**Comment by fraktal-sb** [comment]
the airspaces 2023 and 2024 have been taken from https://www.daec.de/fachbereiche/luftraum-flugsicherheit-betrieb/luftraumdaten/
in both years we find
AC TMZ
AN TMZ-EDFH A0424 125.600
AH FL75
AL 4500ft MSL
DP 50:05:06 N 007:12:19 E 

so i will create a different issue
