### ISSUE TITLE
Android 14: not able to copy airspace and waypoint files into the XCsoar folder

### ISSUE THREAD

**Issue by TillBerthold** [XCSoar/XCSoar#1524]
XCSoar versions having the problem
On Android 14 it is not possible to copy something into Android/data/org.xcsoar/files because this folder is blocked from Android

 7.42

It worked on Android 13

System information
Android 14, Xiaomi 14

Expected behavior
Would like to be able to copy WP files and Airspace

**Comment by lordfolken** [comment]
are you using the files app from playstore, and the documents provider in the files app?

**Comment by lordfolken** [comment]
Also which airspace /waypoint files are missing from the  online repository (File manager)?

**Comment by TillBerthold** [comment]
I tried with different apps from play store and with the file app from the phone.
I need the waypoints from the local competition.

**Comment by lordfolken** [comment]
And you are using the documents provider "files app" in https://play.google.com/store/apps/details?id=com.marc.files
Then hamburger menu, and then xcsoar?

**Comment by TillBerthold** [comment]
I tied with the files app. With the app I can show the folder but can not copy anything to the xcSoar folder.
What do you mean with "Then hamburger menu, and then you use the xcsoar menu entry to manage files?"

**Comment by schonstudent** [comment]
Copy the file to the cache folder with your computer. After copy the file from the cache folder to the final folder.... Had the same issue...

**Comment by TillBerthold** [comment]
After all I managed with a windows computer. This is a very bad workaround. 
Is there a fix in sight? Can someone change the folder to a public location?

**Comment by schonstudent** [comment]
Looks like this is more an android14 security issue....

**Comment by TillBerthold** [comment]
It is because xcsoar is not following the android security policy. It is not the right path for the file folder like this.

**Comment by micheal813** [comment]
Yes, it would be great if this issue could be fixed. I shouldn't have to connect my phone to a PC to copy files to the XCSoar folder. I can't access my log igc files unless I connect it to a PC. There should be options for a custom folder that contain files like maps or task files or some other fix for this issue.

**Comment by TillBerthold** [comment]
There is no option to copy files to this folder.

**Comment by TillBerthold** [comment]
No this does not work on android 14.

**Comment by lordfolken** [comment]
Uploading 2024-08-07_17-48-03.mp4…

**Comment by jorgemarmor** [comment]
Newest Android versions are hardening apps folders. I think the only clean option would be to move the XCSoar folder from Android/data to Android/media, which is open and easy to handle without workarounds.

**Comment by lordfolken** [comment]
> Newest Android versions are hardening apps folders. I think the only clean option would be to move the XCSoar folder from Android/data to Android/media, which is open and easy to handle without workarounds.

Unfortunately this is a deprecated API call:
https://developer.android.com/reference/android/content/Context#getExternalMediaDirs()

I however see that whatsapp,telegram,nextcloud also use this path.

Nevertheless I made a PR with it and it seems to work. Please test: https://github.com/XCSoar/XCSoar/pull/1528

**Comment by jorgemarmor** [comment]
Sorry, not very used to this... How can I test it?

**Comment by lordfolken** [comment]
The GitHub action builds an apk you can use: 
https://github.com/XCSoar/XCSoar/actions/runs/10309426528 (artifacts at the bottom)

This should work with any android version that xcsoar supports. 6+. I tested 13/14.

**Comment by lordfolken** [comment]
You need to uninstall your current version as this one has a,different signing key. (Working on that)

**Comment by jorgemarmor** [comment]
Excellent. Installed and working. In this mode I can access to the foder with any app, without needing Shizuku. Great job!

**Comment by micheal813** [comment]
Thank you for the fix.

**Comment by lordfolken** [comment]
Merged in 7.43
