### ISSUE TITLE
Plane icon color in thermal assistant

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1526]
XCSoar versions having the problem
-------------------------------------------------
7.43-rc0

XCSoar versions not having the problem
-------------------------------------------------

System information
------------------
Android

Steps to reproduce the behavior
-------------------------------
In settings: Look> screen layout: set dark mode to on
Gauges > Flarm, Other : set thermal assistant to anything but off

Replay a flight (or fly) with a thermal 

Expected behavior
-----------------
Plane icon in the thermal assistant to be easy visible. Since the theraml assistant background is white expect the plane to be black

Actual behavior
---------------
With dark mode on the plane is collord white on a white background and can not be easily spotted during flight.

Do you have any idea what may have caused this?
-----------------------------------------------
In src\Look\ThermalAssistantLook.cpp 
ThermalAssistantLook::Initialise(bool small, bool inverse)
plane_pen.Create(width, inverse ? COLOR_WHITE : COLOR_BLACK);

Probably the dark mode sets this inverse to true causing the plane to be colored white

Do you have an idea how to solve the issue?
-------------------------------------------
Remove the inverse check and always have the color black.

**Comment by lordfolken** [comment]
Well the gauge should be dark in dark mode. But there doesn´t  seem to be any config as of yet.

**Comment by lordfolken** [comment]
Lets do it this way: lets remove the inverse check for now as you suggested.

Then we make a new ticket for gauges in general.
* There should only one gauge implementation serving both purposes.
* The placement of the gauges should be able to avoid infoboxes
* flarm gauge config should be on the gauges setup page
*
