### ISSUE TITLE
PG landing zone CUP style is not handled correctly

### ISSUE THREAD

**Issue by acollign** [XCSoar/XCSoar#1539]
XCSoar versions having the problem
-------------------------------------------------

local build of commit a7770

System information
------------------

Ubuntu Noble Numbat

Steps to reproduce the behavior
-------------------------------

The steps below assume a local build was produced under `output/UNIX`.

- go to the root folder with `cd output/UNIX`
- create a data folder with `mkdir data`
- in that folder, create a file `user.cup` with the following content
```
name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc,userdata,pics
"PG Take off",,,463.228N,641.856E,1588M,20,,,,,"PG Take off"
"PG Landing Zone",,,464.836N,642.918E,689M,21,,,,,"PG Landing Zone"
```
- From `output/UNIX` folder, run XCSoar as follows `bin/xcsoar -datapath=data`
- Click `Sim`
- Open `Nav > Waypoint List`
- Click on `PG Landing Zone`
- Click on `Right Arrow`
- Click on `Edit`

Expected behavior
-----------------

Waypoint Type is PG Landing Zone.

Actual behavior
---------------

Waypoint Type is Turnpoint 

Do you have any idea what may have caused this?
-----------------------------------------------

I believe the issue comes from the function `ParseStyle` in `Waypoint/WaypointReaderSeeYou.cpp` which incorrectly maps `Waypoint::Type::PGLANDING;` to CUP style `22` instead of `21` as documented in the specification [0].

Do you have an idea how to solve the issue?
-------------------------------------------

I am happy to open a PR to change the mapping if that makes sense. That would be the patch (without tests)

```
diff --git a/src/Waypoint/WaypointReaderSeeYou.cpp b/src/Waypoint/WaypointReaderSeeYou.cpp
index b0c24344bf..48dbb49461 100644
--- a/src/Waypoint/WaypointReaderSeeYou.cpp
+++ b/src/Waypoint/WaypointReaderSeeYou.cpp
@@ -168,7 +168,7 @@ ParseStyle(std::string_view src, Waypoint::Type &type)
   case 20:
     type = Waypoint::Type::PGTAKEOFF;
     break;
-  case 22:
+  case 21:
     type = Waypoint::Type::PGLANDING;
     break;
   }
```
[0] https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf

**Comment by acollign** [comment]
Thanks for fixing this issue.

**Comment by lordfolken** [comment]
Thanks for reporting and pinpointing. Fixed prereleases can ve downloaded feom https://download.xcsoar.org/testing
