### ISSUE TITLE
No more .apk file generated under github actions?

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1554]
XCSoar versions having the problem
-------------------------------------------------

XCSoar versions not having the problem
-------------------------------------------------
https://github.com/XCSoar/XCSoar/actions/runs/10335074006 is one of the latest where there still is an apk genarated.

System information
------------------
Github

Steps to reproduce the behavior
-------------------------------
Look at the artifacts in the recent actions and notice no .apk file.

Expected behavior
-----------------

Actual behavior
---------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by lordfolken** [comment]
Its beign built but named XCSoar-debug.apk. 
The PR step uses the same variable as the normal file.
            make -j$(nproc) TARGET=ANDROID DEBUG=${{ env.DEBUG }} USE_CCACHE=y V=2 \
            output/ANDROID/bin/${{ matrix.target_bin }}-debug${{ matrix.target_ext }}
