### ISSUE TITLE
compile out of the box: master (commit b45fe171bc11b6eabee474bc7978d98c786f147a)

### ISSUE THREAD

**Issue by ThHanika** [XCSoar/XCSoar#157]
Hi, Since I wanted to dedicate myself to my "pull request" again and want to test the usability of my patch, I have cloned pure from the master repository xcsoar and compiled. Unfortunately
With the current master version no working xcsoar for Linux (Debian) can be produced. The presentation is not OK.
commit b45fe171bc11b6eabee474bc7978d98c786f147a
![bildschirmfoto vom 2018-12-22 16-53-55](https://user-images.githubusercontent.com/41737282/50376204-59f24500-060a-11e9-8427-173564ab8159.png)

**Comment by Turbo87** [comment]
can you use `git bisect` to check what commit introduced these issues for you?

**Comment by ThHanika** [comment]
OK this is the bad one:
67a9a193fa319029dc95b4f4c22c5e9d38a9884f
![bildschirmfoto vom 2018-12-22 19-45-30](https://user-images.githubusercontent.com/41737282/50377715-9c278080-0622-11e9-9ce3-f46f315163a1.png)


this is the last good one:
faf7e212cc3e736cba25b98107098069d3eaf3e9
![bildschirmfoto vom 2018-12-22 19-52-45](https://user-images.githubusercontent.com/41737282/50377749-32f43d00-0623-11e9-967b-aa59210a61aa.png)

**Comment by Turbo87** [comment]
sounds like your system does not support GLSL 🤔

**Comment by ThHanika** [comment]
It seems YES:
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
**OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00**
OpenGL ES profile extensions:

**Comment by Turbo87** [comment]
interesting, then I'm out of ideas. maybe @MaxKellermann know more about this.

**Comment by rawtaz** [comment]
@ThHanika What command should one run to check the GL stuff like you did above? It never hurts to include commands with the corresponding output ;)

**Comment by ThHanika** [comment]
This commandline:

glxinfo | grep "OpenGL"

**Comment by ThHanika** [comment]
**thomas@Dell-Thomas:~$ glxinfo | grep "OpenGL"**
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
thomas@Dell-Thomas:~$

**Comment by ThHanika** [comment]
Is it working on other OpenGL Version?

**Comment by MaxKellermann** [comment]
I have no such problem with the amdgpu driver and a Radeon RX 480.

**Comment by ThHanika** [comment]
Please check your OpenGL Version with following command and make it public:

glxinfo | grep "OpenGL"

**Comment by MaxKellermann** [comment]
```
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.27.0, 4.20.6-heron, LLVM 7.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by ThHanika** [comment]
OK, it is not the INTEL-driver... 

Version of OpenGL ES GLSL ES 3.xx ?
Which version is used in Android, Openvario and Linux?

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.9, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by ThHanika** [comment]
OK I installed **ubuntu-18.04.1-desktop-amd64** 

OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 7.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 18.2.2
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

### **this works!!!!!**

**Comment by ThHanika** [comment]
It seems, it is a mesa version problem

**Comment by ThHanika** [comment]
Bin auf XUbuntu gewechselt: Version 18.04.1 = geht!!!

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

**Comment by ThHanika** [comment]
OK Closed, it is not a xcsoar development problem.
