### ISSUE TITLE
Startup profile selection menu

### ISSUE THREAD

**Issue by NotYourBest** [XCSoar/XCSoar#168]
I have an OpenVario running XCSoar 7.0 preview, set-up to portrait mode, however the profile selection menu on startup initializes to landscape. After selection it switches to portrait orientation; this also happens when "Default" is selected. 
The problem seems to occur irregardless of the device screen orientation setting and the XCSoar setting.

**Comment by MaxKellermann** [comment]
The orientation is a setting of your profile, but before you have selected a profile, no settings are available.

**Comment by ThHanika** [comment]
You could try, you can do that with start-parameter of xcsoar: (-480x800 is the suitable parameter for openvario 7 "display). However I do not know which impact that has, if a touchdisplay is used. In any case, the display orientation must be reset in openvario.prf with this start parameter.

**Comment by ThHanika** [comment]
OK, an additional startup parameter is needed and developed.

**Comment by NotYourBest** [comment]
> The orientation is a setting of your profile, but before you have selected a profile, no settings are available.

That I understand, but is it possible to have the device select the system default orientation for this start-up screen? On a phone or tablet this is easy to overcome by manually rotating the device, but is not so much true for buit-in applications.

Just checked on android with v6.8 and v7, where it follows the device rotation properly.. I'll have a look at the OpenVario settings

**Comment by MaxKellermann** [comment]
XCSoar does already use the system default. But is the system default really the one you wish to have? I don't know anything about OpenVario, I've never seen one. How does one specify the "system default" on an OpenVario?

**Comment by NotYourBest** [comment]
The OpenVario sets the uboot framebuffer to rotate to the selected setting. It looks like that is the system default after system startup. (shell is also in that orientation from start-up) Changing the XCSoar start parameter, as ThHanika mentioned, doesn't play nice.

The strange thing is that all other XCSoar screens are rotated correctly when orientation "default" is selected.

**Comment by kedder** [comment]
This might be related to regression described in #351.

**Comment by MaxKellermann** [comment]
Is this fixed now?

**Comment by lordfolken** [comment]
@NotYourBest can you please check with current release?

**Comment by NotYourBest** [comment]
Can confirm it has been fixed.

**Comment by lordfolken** [comment]
yeah! /close
