### ISSUE TITLE
Display ICAO in CUP files

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#171]
Currently the ICAO code of the airfield. (Field 2 in a cup file) is not visible to xcsoar.

A great way would be to 
- [x] display it in the waypoint details
- [x] make it searchable in the waypoint search
- [x] display it in the waypoint results lists along with the airfield name like: Zurich (LSZH)

**Comment by lordfolken** [comment]
WIP https://github.com/XCSoar/XCSoar/pull/219

**Comment by elgandoz** [comment]
Another neat enhancement would be to query/diplay the weather info for that ICAO code using the already built functionality (currently broken in 7 preview14), from the viewpoint panel.
