### ISSUE TITLE
Flight download doesn't work with IMI Erixx logger

### ISSUE THREAD

**Issue by kicune** [XCSoar/XCSoar#175]
Due to the change in the newer version of IMI Erixx firmware (version 1.2 onwards, authored in 2015) it is not currently possible to download flights from the device (the request to download the list of flights fails).

The problem is caused by the buffer size in COMM_MAX_PAYLOAD_SIZE in the file src/Device/Driver/IMI/Protocol/Types.hpp, which currently has the value of 1024B. 

The new correct value should be 2048.

**Comment by kicune** [comment]
For details and discourse of the topic see also in my previous pull request, that I was not able to get merged: https://github.com/XCSoar/XCSoar/pull/61

**Comment by DanD222** [comment]
Change committed to v6.8.x branch https://github.com/XCSoar/XCSoar/commit/458ec04ab8a6b2cf1df3fcfed03ce3e960c5fbed
