### ISSUE TITLE
Builds are broken in debian stable

### ISSUE THREAD

**Issue by Turbo87** [XCSoar/XCSoar#192]
It seems that between 6412cdf373f59f627f78fd8751c098ae7d45ea91 and 439cd89c103b325f9f88338641c677ae1cd475cd the CI builds started failing.

From the build log:

```
output/UNIX/dbg/driver.a(KRT2.o): In function `KRT2Device::Send(unsigned char const*, unsigned int, OperationEnvironment&)':
/root/project/src/Device/Driver/KRT2.cpp:181: undefined reference to `KRT2Device::CMD_TIMEOUT'
```

/cc @MaxKellermann

**Comment by kerel-fs** [comment]
Commit 439cd89c103b325f9f88338641c677ae1cd475cd changed the variable in question.

**Comment by MaxKellermann** [comment]
This was already bugged, but the bug now materializes because the compiler chose to refer to the variable by reference, not by value after that commit.

**Comment by MaxKellermann** [comment]
Actually, I just found out that this is a compiler bug, see https://en.cppreference.com/w/cpp/language/static
> If a static data member is declared constexpr, it is implicitly inline and does not need to be redeclared at namespace scope. This redeclaration without an initializer (formerly required as shown above) is still permitted, but is deprecated.

**Comment by Turbo87** [comment]
@MaxKellermann so CI won't be fixed because it's a compiler bug?

**Comment by MaxKellermann** [comment]
I don't understand the question. Maybe that answers your question: XCSoar doesn't need to be fixed because it isn't broken.

**Comment by Turbo87** [comment]
well, XCSoar's CI is broken, and IMHO that needs fixing. I think https://github.com/XCSoar/XCSoar/commit/439cd89c103b325f9f88338641c677ae1cd475cd shouldn't have been merged yet until we could update CI to use a compiler without that bug.

**Comment by MaxKellermann** [comment]
CI is a useful tool to measure correctness and detect errors, but if the tool turns out to be flawed, we don't need to listen to it. Therefore I disagree that it shouldn't have been merged. A broken tool shouldn't be able to delay development.

**Comment by kerel-fs** [comment]
Fixed in master.
