### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by Symbian9** [XCSoar/XCSoar#203]
https://www.xcsoar.org/ returns "Error 403"

> ### Forbidden
> 
> You don't have permission to access / on this server.
> 
> ***
> 
> Apache/2.4.25 (Debian) Server at www.xcsoar.org Port 443

**Comment by mongrelion** [comment]
It's not down. It loads over here.

**Comment by Symbian9** [comment]
> It's not down. It loads over here.

For me it still unavailable and returns "Error 403"

![pic.1](https://i.imgur.com/6YhUi1l.png)

Also just tested http://www.xcsoar.org/ using "Site24x7" and result is next:  ***"This url is forbidden."***

- http://www.site24x7.com/public/t/results-1558444840827.html

**Comment by hor63** [comment]
Could it be that your provider/company/router... blocks the access to the IP address?
First week of May the site was indeed down due to a provider change on rather short notice.
But it is up since.

**Comment by hor63** [comment]
Try:
`ping xcsoar.org`

Output for me is: 

> Pinging xcsoar.org [18.184.238.205] with 32 bytes of data:

If ping or nslookup shows a different address your name server still has an outdated IP address or a man-in-the-middle tries to intercept and manipulate traffic.

**Comment by Symbian9** [comment]
> Try:
>
> `ping xcsoar.org`

Here is output:

```
$ ping xcsoar.org
PING xcsoar.org (18.184.238.205) 56(84) bytes of data.
```

**Comment by hor63** [comment]
Seems to be specific for you. The site is up running and reachable.

**Comment by Symbian9** [comment]
BTW, could you create mirror as:

- https://xcsoar.github.io

By creating repo

- https://github.com/xcsoar/xcsoar.github.io

Also, please, upload binary as assets to releases

- https://github.com/xcsoar/xcsoar/releases

**Comment by Plantain** [comment]
Clearly this is not some ISP blocking as his screenshot shows a successful
SSL connection and a 403 served from XCsoar.org. I suspect the new website
suffers from the same overzealous banning problems as the forum.

**Comment by lordfolken** [comment]
I have now corrected the webserver config. Only forum.xcsoar.org is now being filtered. @Symbian9 could you validate and close this bug report if you are able to access the site?

**Comment by lordfolken** [comment]
I have created a new issues for the releases. This is planned.

**Comment by Symbian9** [comment]
> could you validate and close this bug report if you are able to access the site?

Yes, it is working now!
