### ISSUE TITLE
InfoBox Sets Copy then Paste don't seem to overwrite destination infobox

### ISSUE THREAD

**Issue by be-adairing** [XCSoar/XCSoar#214]
When wanting to change the infoboxes positions using the InfoBox Sets Config screens the paste function does not overwrite the selected infobox. 

Test Case:
Navigate to 
* Config -> System -> Look -> InfoBox Sets -> {any infobox set}
* Select an infobox
* press Copy
* select another infobox
* press Paste
* Press Yes when asked to overwrite

The destination infobox does not change.

Tested in:
XCS7 on Android & XCS6 on Android, Mac and Linux

**Comment by kerel-fs** [comment]
The Copy-Paste feature for Infoboxes can be used to copy-paste a _complete set_ of Infoboxes into another Infobox set.

Example usage:
- Config -> System -> Look -> InfoBox Sets
- Select the Infobox Set you want to copy
- Press Copy
- Press Close
- Select the Infobox set where you want to paste the selected infoboxes
- Press Paste
- Press Yes when asked to overwrite

I didn't know this feature yet and didn't find a description about it in the documentation.


Possible solutions to improve the user experience:
- Automatically close the Infobox view and go back to the Infobox Set selection view when "Copy" was pressed to indicate that you should select a target Infobox Set now
- Rename the "Infobox paste" modal to "Infobox Set paste"
- Replace "Overwrite?" by a more descriptive text, e.g. "Overwrite all Infoboxes in this set?"
- Describe this feature in the manual
