### ISSUE TITLE
add sections to developer manual for sending pull request via github

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#221]
The manual needs a section on how to create git branches, rebase and send a pull request.

**Comment by bobmorane06** [comment]
yes! :-) I just made a change to the code and I don't know how to upload it. I'd rather not send the files that I modified, I prefer to use the proper git mechanism (I never used git). If someone gives me a hand and I'm able to do it, I can add a section to the manual

**Comment by lordfolken** [comment]
https://github.com/XCSoar/XCSoar/blob/master/doc/policy.rst This has been added in the new developer documenation. 
Complete Documentation is here: https://xcsoar.readthedocs.io/en/latest/
