### ISSUE TITLE
Compilation issues.

### ISSUE THREAD

**Issue by Vitalhb** [XCSoar/XCSoar#228]
Linux flavor on development machine: Ubuntu 18.04
Issues: errors stop the building process.

It would be very helpful if any experienced XCSoar developer could review and update the development manual. My sugestion is that the person starts with a fresh installation of linux and follow step by step the current manual.

Thanks for the great software!

**Comment by lordfolken** [comment]
Hi!

You gotta be a lot more detailed than that.

First of all Debian is the build target not Ubuntu. 
Logs, packages you installed, and didn't install..  What worked, what didn't. 
There is https://github.com/XCSoar/XCSoar/blob/master/ide/provisioning/install-debian-packages.sh

Which will install the packages needed. 
There is a vagrant box in https://github.com/XCSoar/XCSoar/tree/master/ide/vagrant
And there is my unofficial docker container: 
https://github.com/XCSoar/XCSoar/tree/master/ide/vagrant

If you feel the documentation is inadequate, please update it. The developer is you.

**Comment by MaxKellermann** [comment]
Closing due to lack of feedback from submitter.
