### ISSUE TITLE
zoom in / zoom out using pinch gesture

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#233]
Hello,

In many mobile apps pinch gesture is a quite common gesture to zoom in / zoom out.
Maybe it could be added to XCSoar (I'm personally using it on Android) both for panorama mode and normal mode.

Kind regards

**Comment by lordfolken** [comment]
XCSoar already supports gestures for zooming and other things. Multitouch is probably not implemented, and the current gesture is better for operating in a aircraft in violent conditions.
