### ISSUE TITLE
lock screen paraglider

### ISSUE THREAD

**Issue by fakucatriel** [XCSoar/XCSoar#286]
I now tested this successfully on my Kobo mini, it prevents exactly what @pqueiros described: That the risers trigger all sort of Inputs before take off. Until now I have not managed to unlock the screen unintentionally. The new menu item looks like this:

![Screenshot_20190604_212425](https://user-images.githubusercontent.com/20615486/58908034-ccb23100-870f-11e9-89c9-04c2f17d2616.png)
and after pressing the button you see
![Screenshot_20190604_212444](https://user-images.githubusercontent.com/20615486/58908048-d8055c80-870f-11e9-9ee3-a3b85d7c8580.png)
The current version of my implementation can be found here: https://github.com/nico-krais/XCSoar/tree/v6.8.11_patched

I based this on the v6.8.11 tag since this is the current release and I have that in production. 

As mentioned above this is probably as far as I can go without some directions from a more experienced developer.

If this feature is of interest, I can prepare a merge request. Let me know if specific work should be done before.

If someone is interested in the meantime, I uploaded the version I use on my Kobo mini: https://github.com/nico-krais/XCSoar/releases/tag/v6.8.11_patched - WITHOUT ANY SORT OF WARRANTY, THIS IS BARELY TESTED, ASSUME THAT IT WILL DESTROY YOUR DEVICE AND AT THE VERY LEAST HAVE A FULL BACKUP OF YOUR SD CARD

_Originally posted by @nico-krais in https://github.com/XCSoar/XCSoar/issues/134#issuecomment-498812511_

**Comment by lordfolken** [comment]
This has been implemented in preview15 https://github.com/XCSoar/XCSoar/commit/cf33335b3
