### ISSUE TITLE
logbook

### ISSUE THREAD

**Issue by adrianoellero** [XCSoar/XCSoar#288]
what about to add an automatic logbook feature to fill-up EASA FCL.050 logbook?
I am willing to contribute on software development...

**Comment by lordfolken** [comment]
XCSoar lives from its contributors. If you want a feature you have to be willing to implement it yourself.

First you need a dev environment. You can either use [vagrant](https://www.vagrantup.com/) with our vagrant file in `ide/vagrant`, or use our [Dockerfile](https://github.com/XCSoar/XCSoar/tree/master/ide/docker) 

For how to to do contributions, please have a look at  the dev [manual](https://download.xcsoar.org/releases/6.8.11/XCSoar-developer-manual.pdf)

There is already a logbook feature, maybe that one can be extended to support EASA FCL.050. Btw a description to what that format entails would also be great.

**Comment by lordfolken** [comment]
Are you still interested in contributing this? If so please reopen the issue, or even better provide a pr even in draft.
