### ISSUE TITLE
screen lag when select an analogue vario infobox, or barogram

### ISSUE THREAD

**Issue by aa11bb22cc33dd44** [XCSoar/XCSoar#297]
screen lag when you select an analogue vario infobox, or barogram

**Comment by kerel-fs** [comment]
Hi @aa11bb22cc33dd44,
please provide more details on your issue and consider writing complete sentences.

https://berthub.eu/articles/posts/anonymous-help/

**Comment by aa11bb22cc33dd44** [comment]
Hello
The problem occurs in Kobo Glo HD. When I add infobox with analog vario or barogram - screen does not respond to touch. CPU load 24%-30%. When I remove the analog vario infobox, everything returns to normal and CPU load does not change.
