### ISSUE TITLE
ANDROID: missing correct development configuration with commits after 2018-07-19   

### ISSUE THREAD

**Issue by ThHanika** [XCSoar/XCSoar#302]
Hello masters, can you please setting the right install- and setting-scripts in 
/ide/provisioning/

I am only able to make a xcsoar-android.apk with the last 
commit e87d79bc324f9708eaf85f617aea28a606feeed5 from 2018-07-19

**Comment by lordfolken** [comment]
i have recently updated the ide-provisioning scripts and the resulting vagrant box is able to build android.  
Have a look at #296

**Comment by lordfolken** [comment]
can you describe your build environment?

**Comment by ThHanika** [comment]
The System is Debian 9 (Stretch) a VM VirtualBox system.
also a host-system with xubuntu 18.04.1 using java8.
Installation of develope packets via /ide/provisioning.

**Comment by lordfolken** [comment]
Can you try #296

**Comment by lordfolken** [comment]
#296 should fix this. Otherwise reopen.
