### ISSUE TITLE
MapGen does not work

### ISSUE THREAD

**Issue by sl0m0ZA** [XCSoar/XCSoar#334]
I have been trying for almost a week to generate a map of Utah, USA. All I get is 

Error: Generation failed!

(http://mapgen.xcsoar.org/status?uuid=cdb4f47d75cf969c03ab3f4d0123ba0e6406f34b)

**Comment by lordfolken** [comment]
I'm on it. Broken infrastructure behind mapgen.

**Comment by lordfolken** [comment]
Please use the pregenerated map until then: 
http://download.xcsoar.org/maps/US_UTAH_R9N_HighRes.xcm

**Comment by lordfolken** [comment]
- [ ] install new hardware
- [x] install os
- [x] install zfs / zfs share
- [x] configure bonding nic
- [] configure vlan
- [x] install cluster software (opennebula)
- [ ] configure storage in opennebula
- [ ] add dmz vlan to switch
- [ ] add vlan to opennebula
- [ ] reimport vm from backup
- [ ] reconfigure frontend firewall for vlan
- [ ] any mapping for firewall

**Comment by lordfolken** [comment]
Currently processing 140 maps of backlog.
