### ISSUE TITLE
Map Orientation per (configurable) Page

### ISSUE THREAD

**Issue by kxmm** [XCSoar/XCSoar#335]
"Currently, you can choose the orientation for pre-flight or ascent when viewing the map (Map Display -> Orientation). It would be better if this could be set per page (Appearance -> Pages) as another option alongside Central, Infoboxes, and Bottom."

**Comment by lordfolken** [comment]
Bitte mach einen PR vorschlag.

**Comment by lordfolken** [comment]
What this enhancement want's is a per page orientation possiblity. 
I.e. page 1 north, page 2 track, page 3 (auto-> circling/glide)

Basically extend the following dialog, with an orientation setting per map entry:
![image](https://github.com/XCSoar/XCSoar/assets/407371/6a9c8517-fb31-48a5-8b75-ec16dac1904b)
