### ISSUE TITLE
XCSoar beta - Android

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#358]
Hello,

Is there a simple method to install latest beta of XCSoar (without compiling it).
I'm not looking for a Play Store distribution but a .apk file could be fine.
Ideally this kind of distribution should use an other configuration file (or an other folder) than the "production" ready version.

Kind regards

**Comment by lordfolken** [comment]
There is the xcsoar-testing version on the play store.

There is a also a preview version here: http://download.xcsoar.org/nightly_builds/7.0_preview14~git%23923cf10d/ANDROID/

Its also already 3 months old.. so ymmv. 

All of these use the same datadir per default. The linux version allows you to specifiy another datadir:
```bash
-> % ./output/UNIX/bin/xcsoar --help
Free storage 2945160 KB
Starting XCSoar XCSoar v7.0_preview14-Linux~git#ecaf5aba53
Usage: ./output/UNIX/bin/xcsoar 
  -datapath=      path to XCSoar data can be defined
```

**Comment by scls19fr** [comment]
XCSoar-testing for Android on Play Store is from April 2019 according
https://play.google.com/store/apps/details?id=org.xcsoar.testing&hl=fr

I wonder if you couldn't use Github Action to automatically create a beta release when tagging a new release on Github.

**Comment by elgandoz** [comment]
There is a pull request open for this but has never been merged: https://github.com/XCSoar/XCSoar/pull/253

**Comment by MaxKellermann** [comment]
> There is a pull request open for this but has never been merged: #253

Because it's marked "work in progress" [WIP], i.e. not ready for merging.

**Comment by elgandoz** [comment]
The aforementioned PR has been now merged, without further changes. You can now find nightly builds at http://download.xcsoar.org/.

For Android specifically you can install the apk from `/nightly_builds/{version}/ANDROID/bin/XCSoar-debug.apk`.

Despite the latest version does work on my phone, this is great news, especially to check the most up to date manual.

**Comment by bobmorane06** [comment]
that's very cool. ++

**Comment by elgandoz** [comment]
The nightly builds apparently have stopped uploading since 03/07/2020.
