### ISSUE TITLE
XCSoar 7 Android vs. Singleboard pc

### ISSUE THREAD

**Issue by GLDRLS** [XCSoar/XCSoar#360]
Hi all,

I now use xcsoar7 with a raspberry pi 3b + and touchscreen

In xcsoar7 I missed the option to change the text entry.
The Android version is still providing this feature.
Is it a bug for Linux users?

Also and much more important, When I tap I to the landscape the features "map elements on this location" did not open except I touch in to a airspace.
But airfields or other waypoints are not shown.
This feature also in Android works fine.

I tried the same on stefly's openvario with touchscreen and "his" software
But the problems are the same.

All xcsoar versions are 7.0 preview 14

**Comment by CazYokoyama** [comment]
What do you mean "change the text entry"? On menu -> config -> system -> setup -> weather -> pc_met_username, we have keyboard screen. Don't you have it?
I have it. My XCSoar is self built on rpi4b+ and touchscreen from master branch as of today,  c300c375115e8c4821c0e9932a255c5e6e57f535.

**Comment by GLDRLS** [comment]
![Screenshot_20200308_082138](https://user-images.githubusercontent.com/60045004/76158448-24098580-6116-11ea-9747-9e2fa6a02edb.jpg)

The upper one is in use but the lower one I want to use. 
Normally it's easy to change 
Config - > look - > language, input

In xcsoar7 (singleboard version) are only 4 points to choose 
![IMG_20200307_160140](https://user-images.githubusercontent.com/60045004/76158575-7f884300-6117-11ea-8d68-fd8203d32f7b.jpg)
This picture shows an openvario with his "official" software

![Screenshot_20200308_083619_org xcsoar testing](https://user-images.githubusercontent.com/60045004/76158626-fcb3b800-6117-11ea-8228-21ce5bcf9e45.jpg)

This picture shows the same side on Android 




But much important would be this side
![Screenshot_20200308_084036_org xcsoar testing](https://user-images.githubusercontent.com/60045004/76158664-967b6500-6118-11ea-9cc7-8411ced3d3a1.jpg)
He is not proper working on my raspberry /openvario

**Comment by CazYokoyama** [comment]
Sorry, I don't find the screens above in my xcsoar.

**Comment by mihu-ov** [comment]
> I tried the same on stefly's openvario with touchscreen and "his" software
> But the problems are the same.
> 
> All xcsoar versions are 7.0 preview 14

Can you point me to "his" software? To my knowledge there is no Openvario image with XCSoar 7.0-preview14.

**Comment by GLDRLS** [comment]
Yes,  it's my fault
Stefly - >
Version: xcsoar7_preview10
Date : Apr 15 2017
Git : 4e2485d

**Comment by MaxKellermann** [comment]
So this bug report is about a version that is 3 years old?

**Comment by GLDRLS** [comment]
No,
Maybe I wrote it confusing, I'm using the version 7.0 preview 14 git#72ba7ac89f

**Comment by MaxKellermann** [comment]
So that's 4 months old.

**Comment by GLDRLS** [comment]
Is this good or bad?
And which libinput library or source do you recommend?

**Comment by MaxKellermann** [comment]
Old versions are bad.
What does `lsinput` say?

**Comment by GLDRLS** [comment]
ouput lsinput

/dev/input/event0

bustype  :  BUS_USB
vendor    :  0x461
product   :  0x22
version    :  256
name      : "NHD Newhaven Display "
phys        :  "usb-3f980000.usb-1.1.2/input0"
uniq         : ""
bits ev      : EV_SYN EV_KEY EV_AB EV_MSC
