### ISSUE TITLE
No display of pdf/jpg files possible in XCSoar V 6.8.12 with Android 10 Smartphone

### ISSUE THREAD

**Issue by Buzz33** [XCSoar/XCSoar#361]
With Android Version 8-10 the XCSoar V 6.8.12 (from Google Play Store) does not open pdf or jpg files. 
Version 6.8.11 works!

(On Older Android-Versions (from Version 6 down? Not sure) the XSoar V 6.8.12 works.)

Tested with several Samsung Galaxy Smartphones (e.g.  Note 10+)

Also see newer Issue #390!

**Comment by lordfolken** [comment]
I will close this one then, as #390 is better described. Thanks for researching this.

**Comment by Buzz33** [comment]
Thanks!
