### ISSUE TITLE
ANDROID: Permissions not in one go v6.8.13

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#377]
Hallo, 

Concering @v6.8.13
Observed on Android 7 and Android 8 devices:

If you install XCSoar.apk (6.8.13b) from the website, upon first launch XCSoar asks correctly for storage permissions. Once granted the dialog disappears and you are returned to your last application. XCSoar needs then be accessed from the notifications, after which it asks for location permissions. Once granted, you have to yet again access it from notifications and then it runs fine.

While not breaking, its highly confusing.

I have added a screen recording to document the issue:

![ScreenRecord-20200412-233615](https://user-images.githubusercontent.com/407371/79080710-7b9fa000-7d17-11ea-8334-3624f31ce7e9.gif)

Expected Behavior:
 - Launch XCSoar
 - Be asked for Storage Permission 1/2
 - Be asked for location Permission 2/2
 - Start XCSoar

**Comment by dernatsch** [comment]
I decided to look into this a bit and noticed where this behavior is caused.
When the permission dialog is opened the Method onPause() of the XCSoar class is called. A few calls follow that end up [here](https://github.com/XCSoar/XCSoar/blob/master/src/Android/Main.cpp#L289-L294), where `exit(0)` causes the application to close, apparently because the event subsystem is not initialized.

**Comment by lordfolken** [comment]
Thanks for looking into this. That what you describe may be an additional problem.

As for the permissions:
So you can call for all the permissions at once described here:
https://stackoverflow.com/questions/40169809/how-to-ask-and-accept-all-permissions-in-only-one-confirm-alert-dialog-in-androi

The requestPermissions function can take an array of permissions:
https://developer.android.com/reference/android/support/v4/app/ActivityCompat#requestPermissions(android.app.Activity
```java
int PERMISSION_ALL = 1; 
String[] PERMISSIONS = {Manifest.permission.READ_CONTACTS, Manifest.permission.WRITE_CONTACTS, Manifest.permission.SEND_SMS, Manifest.permission.ACCESS_FINE_LOCATION};

if(!hasPermissions(this, PERMISSIONS)){
    ActivityCompat.requestPermissions(this, PERMISSIONS, PERMISSION_ALL);
}
```
We currently request one after the other here in the requestAllPermissions function defined here:
https://github.com/XCSoar/XCSoar/blob/bc1dab4e72a0550f12772a46ff6db7d84ab5f0a2/android/src/XCSoar.java#L236

**Comment by dernatsch** [comment]
@lordfolken Thanks for the input!
I opened PR #392

**Comment by lordfolken** [comment]
Closing this as its fixed in code.
