### ISSUE TITLE
30s average Needle is not inverted by setting "Invert Info boxes"

### ISSUE THREAD

**Issue by condoratberlin** [XCSoar/XCSoar#397]
Inverting the infoboxes gives them a black background. The current climb needle is inverted to white then, but the 30s average needle (trinagle) is not and can barely be seen as shown here:
![XCSoar_Vario_black_30s_average_Needle](https://user-images.githubusercontent.com/49398997/81606170-e1dd1880-93d2-11ea-9809-efd37ee4edab.png)

**Comment by lordfolken** [comment]
https://github.com/XCSoar/XCSoar/blob/719cedbf614b037c75081fa86f7be3735fb0daf4/src/Gauge/GaugeVario.cpp#L295

Seems to be the code for selecting the color of the needle. 

I don't understand the notation form there, but the one for the varioneedle defined above: 
https://github.com/XCSoar/XCSoar/blob/719cedbf614b037c75081fa86f7be3735fb0daf4/src/Gauge/GaugeVario.cpp#L278
Seems more logical too me.

**Comment by condoratberlin** [comment]
For the vario needle and the average needle the same method is used. the average bool value divides between the two needles.
For the vario needle it works correct.

**Comment by condoratberlin** [comment]
I think the difference is in the canvas methods:
https://github.com/XCSoar/XCSoar/blob/719cedbf614b037c75081fa86f7be3735fb0daf4/src/Gauge/GaugeVario.cpp#L301-L304
For the vario needle the following method is used
https://github.com/XCSoar/XCSoar/blob/351928bdfb56bfd7237a1abe8711c18171827f3d/src/Screen/OpenGL/Canvas.cpp#L209-L239
where an brush and pen are used depending on number of Points. and if a brush is not hollow.
The method used for the average needle is:
https://github.com/XCSoar/XCSoar/blob/351928bdfb56bfd7237a1abe8711c18171827f3d/src/Screen/OpenGL/Canvas.cpp#L156-L167
where only a pen is used. But the only the brush is inverted.

**Comment by condoratberlin** [comment]
When inserting a 
`canvas.SelectWhitePen();`
in addition to canvas.SelectWhiteBrush
https://github.com/XCSoar/XCSoar/blob/351928bdfb56bfd7237a1abe8711c18171827f3d/src/Gauge/GaugeVario.cpp#L295-L297 
the average needle will be in white.
![XCSoar_Vario_white_30s_average_Needle](https://user-images.githubusercontent.com/49398997/81662633-26ea6480-943e-11ea-8cb8-9f32dfa7db87.png)
I will make some more tests an create a pullrequest.

**Comment by condoratberlin** [comment]
Ok, I will create a patch for the v6.8. branch. Is it possible to combine both pill requests or does it have to be another pull request?

**Comment by lordfolken** [comment]
Thank you two for all the effort!
