### ISSUE TITLE
Xcsoar 6.8.13 on Kobo mini returns to FLY/SIM mode selection screen when FLY mode is selected

### ISSUE THREAD

**Issue by GuyHerr** [XCSoar/XCSoar#405]
When running in simulation mode all config screen are accessible but the application restarts the fly mode startup screen when using the replay.
In FLY mode, after loading all the files, the application restarts immediately and showing the fly mode start screen again. It is endless looping back to FLY/SIM selection mode screen.
The sceen display is used in Landscape mode.

Attached is a crash file.
[core.zip](https://github.com/XCSoar/XCSoar/files/4641358/core.zip)

**Comment by MaxKellermann** [comment]
Outdated version.
