### ISSUE TITLE
XCtracer driver to XCSOAR 6.8...

### ISSUE THREAD

**Issue by lele70** [XCSoar/XCSoar#422]
Dear Developers,

could you please add to the release 6.8... release for Android, the XCTRACER driver to connect the XCTracer vario/vario-FLARM to the phone as available on the 7.0 preview?
On my phone (Galaxy Note3 Android5 the 7.0pre15 doesn't work)
Thank you for your support.
Really nice app.
ciao

**Comment by MaxKellermann** [comment]
No.
