### ISSUE TITLE
Kobo : battery level in the launcher

### ISSUE THREAD

**Issue by xbug42** [XCSoar/XCSoar#457]
XCSoar version
--------------
6.8.15 on Kobo

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------
Display the battery level somewhere in the Kobo launcher (the menu with the FLY / SIM and Nickel / Tools / Network / System / Poweroff options)

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------
I would like to have a quick and simple way to know the battery level without starting XCSoar

**Comment by lordfolken** [comment]
Should be possible. You could try to implement something here: https://github.com/XCSoar/XCSoar/blob/master/src/Kobo/System.cpp
