### ISSUE TITLE
airspace warning dosen't work

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#463]
I tested airspace warnings and I only get a quiet "Plopp" if I was pretty close to an airspace. I made a record of the sound, see attached file.

I use OpenVario with XCSoar 7.0_preview_15
[Warnings.mp3.zip](https://github.com/XCSoar/XCSoar/files/5012277/Warnings.mp3.zip)

**Comment by lordfolken** [comment]
Does your OV produce correct sound otherwise?

**Comment by Blaubart** [comment]
yes

**Comment by kedder** [comment]
For the reference, we are discussing this issue on Openvario project as well: https://github.com/Openvario/meta-openvario/issues/98

**Comment by Blaubart** [comment]
I don't know what I did wrong, but today it works perfectly with Condor! Sorry, it seems to be a user problem.
