### ISSUE TITLE
Black screen with Oppo Reno2z Android 10 Color OS V7

### ISSUE THREAD

**Issue by Adrienglide** [XCSoar/XCSoar#466]
Hello,

It seems that XC Soar is not working with the latest version of Android (10, Color OS V7) or with the OPPO Reno 2z that I'm currently using.

When I try to start a flight or a sim, there is a few flash and then the screen goes dark.

I would like to know if you have any information about this problem?

Thank you in advance

Adrien

XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
This cannot be solved until a developer has such a device.

**Comment by groundhogxc** [comment]
@Adrienglide, can you try again with V 7.2? There was a change in the OpenGL graphics code that solved other issues. Other than that, at least a *lot* more info would be needed, but really a device like Max wrote.

**Comment by Adrienglide** [comment]
Hello,

At first, thank you for keeping me in touch.

I just downloaded the new version and it works perfectly for the display,
no more black screen!

I'm not able to fly until May so I don't know if the flying data from the
GPS are consistent.

I am currently in Ireland and I am not able to download the Irish high
resolution map. The downloading start but never end and doesn't seems to be
working. Hopefully I already have the French map that I need for my flights.

Adrien Bérardan

Le mar. 6 avr. 2021 à 22:34, groundhogxc ***@***.***> a
écrit :

**Comment by lordfolken** [comment]
@Adrienglide the downlaod issue for android 10 has been fixed.
