### ISSUE TITLE
Google play repot bug url incorrect 

### ISSUE THREAD

**Issue by r0w4n** [XCSoar/XCSoar#469]
Google play store "about this app" description:

"Report problems in our bug tracker: http://bugs.xcsoar.org/newticket" 

Should either or both update url or 301 redirect to the github issues page

**Comment by lordfolken** [comment]
We should add the playstore description to git like others are doing. https://bugs.xcsoar.org/ takes you to the issues page.

**Comment by lordfolken** [comment]
and maybe switch to fastlane for publishing the apps to the playstore. https://fastlane.tools/

**Comment by MaxKellermann** [comment]
Updated.
