### ISSUE TITLE
Support for RASP Poland direct maps download 

### ISSUE THREAD

**Issue by aggsystems** [XCSoar/XCSoar#482]
XCSoar version
--------------
6.8.16

Would you like add RASP Poland weather maps direct download?

Currently only Germany, UK and some other countries has possibility download RASP maps

I'm owner of www.fcst.pl RASP for Poland from last 4 years.
As a glider pilot I'm using XCSoar software and I have to convert manually data and download it into XCSoar as xcsoar-rasp.dat file. In new version I can see that some countries exept Poland has possibility direct download into XCSoar. 
It would be helpful for Polish glider if our service would be able share data for XCSoar 
IF it's possible, please let me know, what I have to do from my side (any api or webservice?)

**Comment by lordfolken** [comment]
In master you can add your source here:
https://github.com/XCSoar/XCSoar/blob/master/src/Weather/Rasp/Providers.cpp
That way Poland would be select-able through the list. 

In a future setup i'd like to provide it through https://github.com/xcsoar/xcsoar-data-repository

I did a sample implementation: Care to extend it?
https://github.com/lordfolken/xcsoar-data-repository/tree/rasp

**Comment by dingetje** [comment]
@lordfolken did you abandon your sample implementation? I couldn't find it

**Comment by lordfolken** [comment]
xcsoar-data-repository has been replaced by xcsoar-data-content. But the new strutucture should make it easier to add new datatypes.

**Comment by lordfolken** [comment]
@dingetje the rasps are available in the xcsoar-data-content repository. But currently xcsoar doesn't read them. If someone would take up the work in the linked PR, it could be factored out.

**Comment by dingetje** [comment]
@lordfolken is the xcsoar-data-content repository already in use for other data types in a release? The amount and tone of comments from Max in your PR do not sound promising.

**Comment by lordfolken** [comment]
yes, most other things are already supplied by the repository (maps,airspaces,waypoints). (Its not my pr its @Developer66 ) but i think we could separate out the rasp feature that was written, as this is mostly extension of existing stuff.

**Comment by lordfolken** [comment]
@aggsystems I have now all the things ready. The Linked PR moves all the rasp defintions to the repository. 
What i need from you is a stable link to a download dat file for your rasp site. 
Examples are here:
https://github.com/XCSoar/xcsoar-data-content/tree/master/data/remote/rasp/region

**Comment by lordfolken** [comment]
https://github.com/XCSoar/xcsoar-data-content/issues/288
