### ISSUE TITLE
Map/infobox render issues on Raspberry Pi 4 when rotated to portrait

### ISSUE THREAD

**Issue by bhudson225** [XCSoar/XCSoar#504]
XCSoar versions having and not having the problem
-------------------------------------------------

v7.0 preview 15
Separate issues found in latest stable release (6.8.x), although display rotation code has since been overhauled

Expected behavior
-----------------

XCSoar rotates all elements when display orientation is changed within config menu or through modification of default.prf

Actual behavior
---------------

When display orientation is changed to portrait on Raspberry Pi 4 using Mesa KMS, map elements and infoboxes change flicker to different orientations and aren't legible.

See photos: https://photos.app.goo.gl/Y63mNzXyBFXzpUUw6

Static elements, such as background of FLARM radar, are not affected. Similarly, menus respect portrait orientation properly and can be used normally.

These issues are not present in landscape (default) orientation and full functionality has been achieved.

Steps to reproduce the behavior
-------------------------------

Standard compilation of XCSoar on Raspberry Pi 4 with MESA-KMS mode enabled. Run from command line (not X) using either landscape or portrait command line boot flags.

Latest build of Raspberry Pi OS is used, and both included graphics drivers as well as V3D/VC4/kmsro drivers from the latest Mesa stack (20.3.1) have been tested.

Do you have any idea what may have caused this?
-----------------------------------------------

Potentially conflicting rotation algorithms during the render of the dynamically updating parts of the code, but I don't have a solid understanding of that part of the code.

Alternatively, this could be an issue with the Raspberry Pi graphics driver, although functionality in landscape and testing with multiple versions indicates a possible XCSoar incompatibility issue.

Do you have an idea how to solve the issue?
-------------------------------------------

I am currently looking at how XCSoar translates different aspects of the render to apply rotation in the hopes of finding a cause of the error.

**Comment by bomilkar** [comment]
Yes, I ran into this issue some time ago:
https://forum.xcsoar.org/viewtopic.php?f=30&t=3741&start=15#p21522
My workaround for the time being: "make USE_FB=y ...". This may help pinning down the real issue. However, I haven't been able to identify it. But I believe it's in the Pi4 OS because the USE_FB=y doesn't seem to affect the rendering algorithm. Right??
