### ISSUE TITLE
The app closes at startup

### ISSUE THREAD

**Issue by nachoprc** [XCSoar/XCSoar#507]
Hello!
When I start Xcsoar on the cell phone the application closes suddenly.  And it shows me the following error message...

"Xcsoar has crashed recently.
How embarrassing, we're terribly sorry! Please submit the bug report and include the file from the 'crash' directory http://bug.xcsoar.org/newticket
After you report, well fix it ASAP"
I attach the file

[tophat.log](https://github.com/XCSoar/XCSoar/files/5752949/tophat.log)

I wish someone can help me. 
Thanks

**Comment by MaxKellermann** [comment]
You're not using XCSoar, you're using a fork called "TopHat" which is not supported by this project. Can't help.
