### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [XCSoar/XCSoar#513]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by lordfolken** [comment]
@MaxKellermann We should switch to Fastlane appstore deployment. That way we would have the stuff here in the repo, and could contribute. Would you support an initative in that direction?

**Comment by MaxKellermann** [comment]
I have no idea what that means.

**Comment by lordfolken** [comment]
@mondlicht-und-sterne please provide some and submit a pr.

**Comment by Korb** [comment]
Screenshots missing:

![Screenshot_2023_0304_204212](https://user-images.githubusercontent.com/3509797/222920822-e8832b57-3358-48f4-b229-401d38773dab.jpg)

https://f-droid.org/packages/org.xcsoar/
