### ISSUE TITLE
Cross section axis texts overlap

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#516]
XCSoar versions having and not having the problem
-------------------------------------------------

Which XCSoar version are you using when seeing the problem?
v7.0_preview15

Which XCSoar version is the last one you know that did not show the problem?
v7.0_preview15
(not comparable to previous versions i.e. 6.8.17 due to different cross section layout)

Expected behavior
-----------------

Axis texts should not overlap (better readability); see screenshots and "idea how to solve the issue"

Actual behavior
---------------

Texts overlapp (see screenshot SS_140.png)

Steps to reproduce the behavior
-------------------------------

select text scale = 140% in configuration/language/text setup

Do you have any idea what may have caused this?
-----------------------------------------------

text font size is hardcoded in src/Look/ChartLook.cpp

Do you have an idea how to solve the issue?
-------------------------------------------

the attached patch corrects the problem by calculating a new font size using text scale factor from the configuration

see the screenshots from KOBO in the attachment:

The patch file "patch.txt" contains the proposed source code (git diff)

ss_100.jpg shows the texts at 100% text scale factor
ss_140.png shows the problems using 140% text scale factor
correct.png shows the cross section with the patched software

![ss_100](https://user-images.githubusercontent.com/69430537/105164776-d8857d80-5b15-11eb-8471-a8b7eb4f472c.jpg)
![SS_140](https://user-images.githubusercontent.com/69430537/105164792-dd4a3180-5b15-11eb-8b34-fc4f53c627f4.png)
![Correct](https://user-images.githubusercontent.com/69430537/107072397-591ace00-67e6-11eb-9f15-620d5b96eae3.png)

[patch.txt](https://github.com/XCSoar/XCSoar/files/5841832/patch.txt)

**Comment by lordfolken** [comment]
Can you make it a PR?

**Comment by fraktal-sb** [comment]
- issue description changed (last graphic updated with green boxes to clearify the change)
- updated  topic "versions having and not having the problem"
