### ISSUE TITLE
Problem loading some tsk files

### ISSUE THREAD

**Issue by vicb** [XCSoar/XCSoar#542]
XCSoar versions having and not having the problem
-------------------------------------------------

XCSoar 6.8 has the issue on Android

Behavior
-----------------

[Archive.zip](https://github.com/XCSoar/XCSoar/files/6111825/Archive.zip) contains 2 task files 
ok.tsk load correctly,
ko.tsk fails to load  (nothing happens when the file is selected).

Steps to reproduce the behavior
-------------------------------

1) Copy the two task files to the `XCSoarData` folder on the android phone
2) Navigate to: Nav > Task > Manage > Browse
3) When ok.tsk is selected, you can see the task and load it,
4) When ko.tsk is selected, you can not see the task and can not load it.

Do you have any idea what may have caused this?
-----------------------------------------------

May be there is a limit on the number of waypoints per task ?

Both files are generated with flyxc.app (I am the developper - https://github.com/vicb/flyxc)

**Comment by MaxKellermann** [comment]
Your task files do not specify a type. The default type is "FAI", which is limited to 13 points. Do you really want to have FAI tasks?
The type "RT" (racing) is limited to 30 points.

**Comment by vicb** [comment]
Thanks for your answer @MaxKellermann 

I have a few follow up questions for you:

1) How to declare the task type ? Is it a type attribute on `<Task>` ?

i.e. `<Task type="FAI/RT">` ?

2) Is there a type of tasks without any (or >30) waypoint limit ?

3) Is the tsk file format documented somewhere ?

4) Does CUP files have the same limitation when imported in XCSoar (i.e. 30 waypoints) ?

Thanks !

**Comment by MaxKellermann** [comment]
The file format is not documented, unfortunately. The whole task engine was rewritten in 2009, and while some of the code is really excellent, the I/O code has very bad error handling and the format is undocumented. Much of that is very obscure, and would have been different if I had designed it.

1. `<Task type="rt">` https://github.com/XCSoar/XCSoar/blob/1d0e12cee0c400044e9b6fa3d29ca7f4acbe1ba5/src/Task/Deserialiser.cpp#L289-L290
2. no
3. no
4. yes, it all leads to the same task code, just with different callers

**Comment by vicb** [comment]
Thanks a lot for the info and the blazing fast answer.

I have one last question for you: out of curiosity why is there a 30 waypoint limit ? Is this from any existing competition rule or an arbitrary limit ?

Thanks

**Comment by MaxKellermann** [comment]
> I have one last question for you: out of curiosity why is there a 30 waypoint limit ? Is this from any existing competition rule or an arbitrary limit ?

I have no idea, I didn't write any of this. If nothing else, there needs to be some limit - what if a task has one billion task points... but no idea about 30.

**Comment by vicb** [comment]
I agree there should be a limit but devices shouldn't have problem handling a few hundreds waypoints. I was just curious about the rationale.
Anyways thanks a lot for your help. I have updated flyxc.app to generate race tasks and will release in a few days.

**Comment by MaxKellermann** [comment]
You are very welcome to submit documentation for the task file format; the code is in https://github.com/XCSoar/XCSoar/blob/master/src/Task/Deserialiser.cpp and https://github.com/XCSoar/XCSoar/blob/master/src/Task/Serialiser.cpp

**Comment by vicb** [comment]
I'd love to contribute that (will probably need some help with some details).

Where should the documentation go (what folder / format) ?

**Comment by MaxKellermann** [comment]
The documentation is currently written in LaTeX, it's here: https://github.com/XCSoar/XCSoar/tree/master/doc/manual/en
There's `XCSoar-developer-manual.tex`, and I suggest you write the task file documentation in a new file, maybe called `task_format.tex` (like `input_format.tex` and other files we already have).
(These days, I'd use [Sphinx](https://www.sphinx-doc.org/) and not LaTeX for documentation, but LaTeX was already used even before I joined the project. I'd support a switch to Sphinx.)

**Comment by MaxKellermann** [comment]
Text, I guess. I have never used XSD, but I think it's only a syntactic description, not with human-readable documentation?

**Comment by MaxKellermann** [comment]
I've added a commit to show an error message when loading an invalid task, instead of refusing to load it.

**Comment by vicb** [comment]
> I have never used XSD, but I think it's only a syntactic description, not with human-readable documentation?

XSD is XML so it can have comments.
Also XSD can be used to validate generated tracks - could be a good unit test to know when the format changes.

I think that XSD could at least be a good starting point and then we'll see if making a text documentation for the file makes sense.
