### ISSUE TITLE
Airspace problem

### ISSUE THREAD

**Issue by marti10123** [XCSoar/XCSoar#551]
Hello
Please, i don't understand what happenning.

I installed well xcsoar on android 8.0
When i have selected french map and cup, everything works well

I have a problem with the airspace, look at the picture, i jave an error .
What can i do?
Thanks
![Screenshot_20210325-145655_XCSoar](https://user-images.githubusercontent.com/81371492/112487442-9d513600-8d74-11eb-9846-ebc40385088d.jpg)

**Comment by MaxKellermann** [comment]
The airspace file is broken. There must not be a  `:` between the coordinates and the `N`/`E`.

**Comment by marti10123** [comment]
Thanks a lot 😊

Le jeu. 25 mars 2021 à 15:31, Max Kellermann ***@***.***> a
écrit :
