### ISSUE TITLE
Infobox labels too small on XCSoar version 7

### ISSUE THREAD

**Issue by DanD222** [XCSoar/XCSoar#552]
XCSoar version
--------------

v7.0_preview18

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

I find the infobox labels hard to read on XCSoar version 7 due to their small size. I feel that the infobox space could be better utilised to make the labels larger / taller in height.

I'm OK with the infobox label size as it is on v6.8 (even if it means some of the text is cropped - at least it doesn't require special effort to read it).

v7.0_preview18
![v7](https://user-images.githubusercontent.com/48011765/112512642-d9e05a00-8d93-11eb-9521-0fe9ebce8ec9.jpg)

v6.8.17
![v6](https://user-images.githubusercontent.com/48011765/112512594-cf25c500-8d93-11eb-8117-dc5dadb48eb6.jpg)

**Comment by MaxKellermann** [comment]
XCSoar 7 auto-sizes those fonts so they fit a certain amount of text.
XCSoar 6.8 doesn't do that at all; it just uses some random scaling factor which is bad most of the time. Just look at how badly the text is truncated in most boxes and how bad the layout looks. Yes, the font is bigger, but that comes at a price.

Maybe the 7 algorithm needs some fine tuning.

What device are you using, what is the physical display size (in mm)? How large is the text (in mm)? How large was the text in 6.8? What size do you want it?

**Comment by MaxKellermann** [comment]
I implemented a change which hopefully improves the problem for your specific case.

**Comment by DanD222** [comment]
Much better now.. thanks again!

![v7_0](https://user-images.githubusercontent.com/48011765/112629355-85d98200-8e34-11eb-9afe-d9a7633cc2f4.jpg)

**Comment by MaxKellermann** [comment]
And much better than v6.8!
