### ISSUE TITLE
Some observation zones in Task manager:Turn Points dialog are too big/overlapping 

### ISSUE THREAD

**Issue by MikeBravo15** [XCSoar/XCSoar#553]
XCSoar v7.0 Android

Expected behavior
-----------------

Observation zones, displayed next to task turnpoins do not overlap the zone of other waypoints

Actual behavior
---------------

Observation zones are way too big and different types are not in uniform scale

![Screenshot_20210326-172400](https://user-images.githubusercontent.com/42399455/112666757-cb11aa00-8e5c-11eb-95cf-3d4f9883b950.png)

**Comment by MaxKellermann** [comment]
The list renderer uses only the reference points for calculating the bounding rectangle, but since the arc is not part of the boundary (it's just the line), it's not considered for the bounding rectangle.
