### ISSUE TITLE
Bug trying to download maps and waypoints

### ISSUE THREAD

**Issue by gruendling** [XCSoar/XCSoar#559]
XCSoar versions having and not having the problem
-------------------------------------------------

 7.1
6.8

Expected behavior
-----------------

 Download Map Files from repository
![Screenshot_20210401_190654_org xcsoar](https://user-images.githubusercontent.com/63117349/113330068-a2872580-931e-11eb-82b3-31981d49649c.jpg)

Actual behavior
---------------

 throws Java error above see picture. 

Steps to reproduce the behavior
-------------------------------

 Huawei P30 Pro running android 10

Do you have any idea what may have caused this?
-----------------------------------------------

 no 

Do you have an idea how to solve the issue?
-------------------------------------------

 no

**Comment by lordfolken** [comment]
Duplicate #549
