### ISSUE TITLE
Waypoint Editor reversing latitiude and longitiude

### ISSUE THREAD

**Issue by CptFrikadel** [XCSoar/XCSoar#562]
XCSoar versions having and not having the problem
-------------------------------------------------
Latest versions (7.0 and 7.1) seem to have the issue. Not sure when this started.

Expected behavior
-----------------
Entered latitude and longitude remain the way they were entered.

Actual behavior
---------------
The entered northing and easting gets swapped. I.e. entering N51.00000, E009.00000 will end up as N009.00000, E51.0000
Opening the `Location` widget and pressing `OK` swaps them back around. 

Steps to reproduce the behavior
-------------------------------
`Config` -> `Config` -> `Waypoints Editor` -> `New` or `Edit` -> `Location` -> enter lat/lon -> `OK` -> observe lat/lon being swapped.

Do you have any idea what may have caused this?
-----------------------------------------------
Not yet

Do you have an idea how to solve the issue?
-------------------------------------------
Not yet

**Comment by lordfolken** [comment]
And saves it wrong too.. darn.
