### ISSUE TITLE
Undesirable .prf file format change in 7.4-Android

### ISSUE THREAD

**Issue by Bre901** [XCSoar/XCSoar#587]
I tried sending this thought the mailing list, but apparently to no avail

Since version 7.4 (at least on Android) XCSoar doesn't accept the "\\" anymore before the plane name in the path to the .xcp polar file

PlanePath="%LOCAL_PATH%\\Polars\\JS3-15-FXB.xcp" doesn't work, it has to be: PlanePath="%LOCAL_PATH%\\Polars/JS3-15-FXB.xcp"

This means that I had to make a new version of my Condor task converter (CoTaCo - https://condorutill.fr/index.php)

Fortunately, the previous versions apparently supported both the "\\" and "/", so that my fix is backwards compatible

Was that change made on purpose ?
If yes, can someone please explain me why as I really don't see what improvement it would bring...

**Comment by lordfolken** [comment]
Reproducible on UNIX target:

PlanePath="%LOCAL_PATH%\polars\hb-198823323.xcp" results in:
Failed to open '/home/folken//.xcsoar/polars\hb-198823323.xcp': No such file or directory

This seems to happen only when one uses subdirs and modifies the prf directly. (which is the purpose of CoTaCO)

Using forward slashes it doesn't work either:
Failed to open '%LOCAL_PATH%/polars/hb-198823323.xcp': No such file or directory

The only thing that works is as @bre901 stated: 
PlanePath="%LOCAL_PATH%\polars/hb-198823323.xcp" results in:
