### ISSUE TITLE
Request confirmation on pressing "Revert task"

### ISSUE THREAD

**Issue by VladimirVLF** [XCSoar/XCSoar#590]
After defining a task in XCSoar on my smartphone I accidentally touched the "Reverse task" button and did not notice it.
Then I sent task declaration to my logger.
Luckily I looked at the declaration in my logger (which I usually don't do) and found that my task is reversed.
After going back and forth with XCSoar and the logger, I realized that my task in XCSoar is reversed, which is not noticeable at a glance, since task legs still look the same no matter task direction.

It would be a good idea to ask for a confirmation when pressing the "Reverse task" button when defining a task, to avoid this kind of unfortunate situations.

**Comment by MaxKellermann** [comment]
Is this about Revert Task or Reverse Task?

**Comment by lordfolken** [comment]
I think he meant reverse. @VladimirVLF please provide a pr for inclusion.

**Comment by MaxKellermann** [comment]
No reply.
