### ISSUE TITLE
Aircraft symbol with current position not shown on map

### ISSUE THREAD

**Issue by phoebusb** [XCSoar/XCSoar#598]
XCSoar 7.5. Android 10 running on SONY Xperia H8314 

XCSoar versions having and not having the problem
7.5 does not show the aircraft symbol on the map after startup, although the GPS is ready and GPS parameters, distances etc. are shown on the map. It looks like it's not rendering the aircraft icon only ...
7.4 compiled yesterday did not have that problem

Expected behavior
-----------------
As soon as GPS is ready my position using the aircraft symbol should be visible on the map
Same behaviour in SIM mode

Actual behavior
---------------
Everything looks good, but no symbol is shown, i.e. your position relative to the map is not known

Steps to reproduce the behavior
-------------------------------
install 7.5 and start it

Do you have an idea how to solve the issue?
-------------------------------------------
I guess one of today's (30.4.) commits ...

**Comment by MaxKellermann** [comment]
e38dd5c0653cb65a74a6343de5637d0c87d3bb47
