### ISSUE TITLE
Untranslated InfoBoxes strings / i18n / fr

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#608]
Hello,

the following infoboxes are not translated into french (XCSoar v7.6 Android) :

- Active Radio Frequency
- Contest distance
- Contest speed
- Standby Radio Frequency
- Thermal time

Oddly, 
- Contest distance (Distance On-Line Contest)
- Contest speed (Vitesse sur circuit "OLC") 

was translated in XCSoar-testing (which is currently numbered v7.2-Android)

Kind regards

**Comment by Scumi** [comment]
> Oddly,
> 
>     * Contest distance (Distance On-Line Contest)
> 
>     * Contest speed (Vitesse sur circuit "OLC")
> 
> 
> was translated in XCSoar-testing (which is currently numbered v7.2-Android)

This is linked to #575, which happened after the version you mentioned.

**Comment by scls19fr** [comment]
InfoBoxes layout are partially translates into french also. I can provide PR if someone point me to file to édit.

**Comment by scls19fr** [comment]
I have found https://hosted.weblate.org/translate/xcsoar/translations/fr/
