### ISSUE TITLE
Kobo Clara HD not anymore supported (touchscreen not working)

### ISSUE THREAD

**Issue by wolkenjaeger** [XCSoar/XCSoar#611]
XCSoar versions having and not having the problem
-------------------------------------------------

6.8.17

Expected behavior
-----------------

Touchscreen input shall work

Actual behavior
---------------

Touchscreen inputs are not working. However, the physical button works to turn Kobo on and off.

Steps to reproduce the behavior
-------------------------------

Install Kobo 7.6 on a Kobo Clara HD

Do you have any idea what may have caused this?
-----------------------------------------------

Kobo Clara HD is not defined in the source code. 

Do you have an idea how to solve the issue?
-------------------------------------------

Add relevant definitions in the source code, maybe it is just a driver issue during boot. I am able to help with basic testing.

**Comment by MaxKellermann** [comment]
This can be analyzed only if a developer has a Kobo Clara HD.

**Comment by lpojzl** [comment]
@MaxKellermann: Max, I bought Kobo ClaraHD just for XCsoar. As it's currently not working, I am open for a 1/2 year loaner to you. Are you willing to have a look at the ClaraHD related issues? It would be great having it working before next season. ;-)
The device would come flashed with latest Kobo software and XCsoar build installed, together with non-intrusive serial2usb cable for console debugging.
![ClaraHD](https://user-images.githubusercontent.com/67234454/130317565-d1c7d0da-dfef-40b4-a78a-0e6030786a57.jpg)

**Comment by sepi** [comment]
I also have the same issue on the Clara HD with the the 7.x versions. Will see if I can debug somehow. For now, version 6.8.11 works ok.

**Comment by fagat73** [comment]
Hello,
Any news regarding this issue ? I've installer the latest XCSoar 7.20 version on my Kobo Clara HD and the touch screen not working anymore.
Thank you.

**Comment by MaxKellermann** [comment]
@fagat73 of course not. If there were news, you would be able to read them here. No developer has a Kobo Clara HD, and there cannot ever be any progress until a developer has one.

**Comment by fagat73** [comment]
I've got the Kobo but I'm not a developer on the projet. Anyway let me know if I can be of any help with resolving this issue.

**Comment by lordfolken** [comment]
You can organize a crowd funding for a device for @MaxKellermann that way the project can support the platform. Without hardware it will be very difficult.

**Comment by MaxKellermann** [comment]
You can help by either
- becoming a developer and solve the issue, or
- donating a Kobo Clara HD to the XCSoar project

Just owning a Kobo Clara HD is not helpful at all, if you're not using it to analyze the problem and submit the fix to this project.

**Comment by fagat73** [comment]
OK let me know how i can donate to the XCSoar project and i'll do

**Comment by MaxKellermann** [comment]
My address can be found on the [XCSoar imprint](https://xcsoar.org/imprint.html). If one day a Kobo Clara HD spawns at my doorstep, I'll take care for this issue.

**Comment by wolkenjaeger** [comment]
@fagat73 did you send a device to @MaxKellermann ? If not, I can do it.

**Comment by fagat73** [comment]
Hi. Not yet. I’m looking for a second hand one. And it’s not yet Christmas :) if you got one please do. And thank you.

**Comment by wolkenjaeger** [comment]
I will do so.
