### ISSUE TITLE
Display OGN traffic in XCSoar

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#615]
Hello,

It could be nice if XCSoar could display OGN traffic either on map or on a similar screen than XCSoar FLARM display.
Of course it won't be as reliable as a connection to a FLARM device as it will require 4G or 5G connection but it could be a really useful feature.

Kind regards

**Comment by MaxKellermann** [comment]
OGN is illegal in Europe, it violates the GDPR (and maybe other laws) by recording people's location without their explicit consent. I will not contribute any minute of my free time towards such a bad thing.

I promothe the usefulness of live tracking, and I was the one who invented the most efficient live tracking protocol for pilots to date, but one with explicit consent. OGN aims towards a good thing, but is ignorant of people's rights.

**Comment by scls19fr** [comment]
I'm not involved in OGN dev but I can only say, technicaly, that OGN APRS message have stealth and no-tracking flag.
OGN data usage rules are available at https://www.glidernet.org/ogn-data-usage/
@snip can probably say more about the legal aspect of this project (which have been rewarded General Aviation (GA) Safety Award from EASA) https://www.easa.europa.eu/newsroom-and-events/news/easa-announces-winners-first-ga-safety-award

**Comment by MaxKellermann** [comment]
Does that mean that OGN *only* ever tracks people who have explicitly consented to being tracked?
GDPR does not allow opt-out. Tracking must be explicitly opt-in.

Internal OGN features do not matter here. What matters is the explicit and informed decision of each and every person who is being tracked.

When I was still flying, my FLARM did not have a button which allowed me to consent to being tracked by OGN.

**Comment by Plantain** [comment]
You can already do this via OGN Viewer - https://play.google.com/store/apps/details?id=com.meisterschueler.ognviewer

**Comment by scls19fr** [comment]
Thanks @Plantain I know OGN Viewer but I don't think it's very safe to switch from app to app during flight.
Moreover with "fat fingers" XCSoar can be stopped unintentionally and so IGC recording quite "easily".

**Comment by Plantain** [comment]
Read the description. You can setup the TCP Server in OGN Viewer then it
shows on the XCSoar Flarm radar

**Comment by scls19fr** [comment]
Thanks @Plantain

**Comment by scls19fr** [comment]
Not sure if I should reopen this issue... as it's related or open a new one.

`xcsoar-flarm.txt` seems to only provide a key/value store with 
- key being FLARM id
- value being CN

Maybe an other format should be implemented to provide also (when known)
- registration
- aircraft_model
- comment

I also noticed that XCSoar display a radar on map (bottom left) very often... even when no traffic is shown.
This is quite disturbing

**Comment by elgandoz** [comment]
> I also noticed that XCSoar display a radar on map (bottom left) very often... even when no traffic is shown.
This is quite disturbing

In order to hide that specific overlay go to `Config > System > Gauges > FLARM, Other > FLARM radar` and set it to `Off`

**Comment by lordfolken** [comment]
The gauge is now only visible if there is traffic within 4 km.

**Comment by DanD222** [comment]
I believe the "Manage" button in XCSoar Devices can be used to set the parameters of a device with a FLARM driver; certainly distance filters, I also think some or both of the Stealth/No Track flags, but I don't have a device to check this on.

**Comment by lordfolken** [comment]
For the flarm spec:
I have a branch that is waiting, with a full flarm protocol (v9) implementation, 
https://github.com/XCSoar/XCSoar/pull/1964 testers welcome.

**Comment by lordfolken** [comment]
Implemented for v7.45 via XCSoar Cloud OGN ingest and client traffic display.

OGN traffic is shown on the map, in the traffic list, and in what-is-here using the same FLARM traffic UI as device traffic. Own-ship filtering by FLARM id is included.

- #2671 — Cloud: OGN traffic ingest and client integration
- #2728 — Tracking: Filter OGN ownship by FLARM id (follow-up, #2693)

Closing as done.
