### ISSUE TITLE
Some Alternate infoboxes are missing

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#616]
Hello,

Currently using XCSoar 7.6

The following infoboxes are missing for alternates :
- Alternate 2 GR (glide ratio)
- Altitude difference to alternate 1
- Altitude difference to alternate 2

Kind regards

**Comment by lordfolken** [comment]
I believe this is implemented in 
https://github.com/XCSoar/XCSoar/commit/02fb01d884a71cbd5b97401fbd95466dc1dcd508
