### ISSUE TITLE
OUDIE2 Lite bluetooth

### ISSUE THREAD

**Issue by K-Factor-1961** [XCSoar/XCSoar#636]
I discovered that with last version of OUDIE 2 Lite, if you want to install XCsoar it is impossible to activate the internal bluetooth device to connect the unit to an external device. 
It seems that it is possible to activate bluetooth (on com5) only by seeyou mobile application and when you go out the application, the bluetooth device is swutched off.
Which may be the solution?

**Comment by MaxKellermann** [comment]
XCSoar doesn't run on the Oudie. Not supported.
