### ISSUE TITLE
Pan menu locking up Task editor

### ISSUE THREAD

**Issue by johnthomas22** [XCSoar/XCSoar#637]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
This bug report is empty.

**Comment by johnthomas22** [comment]
Apologies, It appeared to have pasted the screen shot I provided and I added some description of the problem. Will have another try.
