### ISSUE TITLE
Program crashes on KOBO with 7.7 while terrain (Israel all formats) is used

### ISSUE THREAD

**Issue by orengt** [XCSoar/XCSoar#654]
XCSoar versions having and not having the problem
-------------------------------------------------
XCSoar 7.7 on KOBO Aura Edition 2 with bluefly vario ver 1.2

Expected behavior
-----------------
Program shouldn't crash

Actual behavior
---------------
When I activate Israel's terrain file as soon as GPS is detected the program crashes, going back to home page. 

Steps to reproduce the behavior
-------------------------------
Turn on 
Load terrain file
Turn on GPS
Wait satellites to be detected
...

here is a link to crash log from my device:
https://drive.google.com/file/d/1SqvjdIGVQ-IIv4RNVeF_Zgk3Oq5N4GmK/view?usp=sharing

Do you have any idea what may have caused this?
-----------------------------------------------
When using it without terrain file it looks to be ok, however I didn't use it for a whole flight yet.

Do you have an idea how to solve the issue?
-------------------------------------------

Nop

**Comment by lordfolken** [comment]
Would you mind providing your default.prf?

**Comment by MaxKellermann** [comment]
Duplicate of https://github.com/XCSoar/XCSoar/issues/650

**Comment by orengt** [comment]
Hi Philipp,

I don't know if it's still relevant since I saw the issue was closed as
duplicate of #650, however attached are to prf files as requested by .
Oren.prf is the one I used when the crash occurred and also the default.prf.
Thanks,

Oren


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lordfolken** [comment]
@orengt i think the duplicate comment is an error. However Max fixed the issue already.

**Comment by MaxKellermann** [comment]
Right. This bug is fixed, but the duplicate is wrong.

**Comment by orengt** [comment]
Thanks for the quick solution.
Do you have any idea when it'll be available for KOBO?
Oren

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MaxKellermann** [comment]
The next release will contain the fix, but I have uploaded an experimental pre-release build here for you to test: http://max.kellermann.name/download/xcsoar/kobo/KoboRoot.tgz

**Comment by orengt** [comment]
Thanks Max, I tried it for a  few hours at home, it looks fine.
I'll test it on fly Sat I hope.
Thanks alot.
Oren

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MaxKellermann** [comment]
Here's the final release with the fix: https://download.xcsoar.org/releases/7.9/KOBO/KoboRoot.tgz

**Comment by orengt** [comment]
Thanks Max.
It works like a charm, I tried the patch in flight during the weekend and
now the installation you just sent, both works OK.
Oren

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
