### ISSUE TITLE
New dependency to libcares

### ISSUE THREAD

**Issue by hjr** [XCSoar/XCSoar#666]
XCSoar version
--------------
#HEAD

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------
Our dev manual does not mention the dependency to libcares. I am not sure which we it should be resolved e.g. for Linux, but a simple "make" does end on link level missing this library.

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------
Please add the necessary hint to get this library dependency resolved.

**Comment by lordfolken** [comment]
We have all the dependencies needed in the provisioning script: https://github.com/XCSoar/XCSoar/blob/e7db3c374c7f3abd4f3d425052719f6cbab35324/ide/provisioning/install-debian-packages.sh#L42
