### ISSUE TITLE
Height above takeoff info box error

### ISSUE THREAD

**Issue by tr55717** [XCSoar/XCSoar#675]
XCSoar versions having and not having the problem
7.11 has problem-------------------------------------------------

Expected behavior
Info box HEIGHT ABOVE TAKEOFF should read 0 when on ground-----------------

Actual behavior
Info box reads negative by 200 feet or more, see photo. Appears that an offset QFE value has crept in.---------------

Steps to reproduce the behavior
Select FLY. In sim mode the info box reads 0 correctly at start on the ground-------------------------------

Do you have any idea what may have caused this?
No. Only noticed it recently when using REPLAY of igc file. See photo of problem on two different devices.
![P1070400](https://user-images.githubusercontent.com/88211981/127708499-f218a3e5-235a-40d1-9120-c00390fe9065.JPG)
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
Ouch. The underlying code for this InfoBox doesn't make any sense at all. It shows the altitude relative to the configured home waypoint, and has nothing to do with takeoff. This just happens to be correct if you're at your home airport (or launched from there).
