### ISSUE TITLE
Keyhole for AAT task

### ISSUE THREAD

**Issue by Exadios** [XCSoar/XCSoar#69]
This issue replicates [Ticket 1687](https://bugs.xcsoar.org/ticket/1687) here on github.

**Comment by kerel-fs** [comment]
#148 addresses this issue.

**Comment by Exadios** [comment]
As I messaged you previously I have your branch on this subject. I've not yet had a chance to have a close look, test, etc. But it is on my list of things to do.

Since it's mostly addressed, I'm going to close this issue.

**Comment by Exadios** [comment]
To be addressed by the pull request that will, soon, replace [url=https://github.com/XCSoar/XCSoar/pull/148]#148[/url].

**Comment by kerel-fs** [comment]
Great! Note that you don't have to create a new Pull Request but can force-push the updated commits to the original `Exadios:ticket_1687_on_master` branch and re-open the old Pull Request. This way we don't "loose" the initial discussion which should simplify review.

**Comment by Exadios** [comment]
OK, Thanks for the tip.

**Comment by Exadios** [comment]
> Great! Note that you don't have to create a new Pull Request but can force-push the updated commits to the original `Exadios:ticket_1687_on_master` branch and re-open the old Pull Request. This way we don't "loose" the initial discussion which should simplify review.

So, how do I re-open the Pull Request? I have pushed the branch but can see no way to re-open. I suspect I do not have sufficient privilege to do this.

**Comment by kerel-fs** [comment]
Indeed, seems that you need special privileges to re-open the Pull Request (on the other hand, you can close it yourself, so I don't fully understand the underlying logic yet).

So, I'll re-open it.

**Comment by kerel-fs** [comment]
Oops, didn't re-open the PR but this issue instead. I've as well no permission to re-open #148. Probably you should comment there and ask cirrus to re-open the PR.

**Comment by Exadios** [comment]
OK. Thanks.

**Comment by lordfolken** [comment]
Are you guys going to submit a new PR?

**Comment by lordfolken** [comment]
There is a new ticket #938 does this cover this here?

**Comment by lordfolken** [comment]
#938 implements this.
