### ISSUE TITLE
7.13 loading 

### ISSUE THREAD

**Issue by Richardr773** [XCSoar/XCSoar#697]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by MaxKellermann** [comment]
This bug report is empty.
