### ISSUE TITLE
SkyLines' "Show nearby traffic" option not persistent and not working

### ISSUE THREAD

**Issue by elgandoz** [XCSoar/XCSoar#708]
XCSoar versions having and not having the problem
-------------------------------------------------
Since its introduction in the stable channel with **6.8** to the current release (**7.17**)

The first implementation landed in **6.8_beta1**, which I couldn't test.

Commit: [94e08b8](https://github.com/XCSoar/XCSoar/commit/94e08b82930db35001aaff31327ec83721e68a6a)

**NB**: the value is not saved since 6.8 (first release in the stable) but I couldn't verify the actual functionality since SkyLines endpoint has changed since then.

Expected behaviour
-----------------
When setting SkyLines' "Show nearby traffic" to _On_, I should be able to see other SkyLines account nearby.
After restarting XCSoar, the configuration should persist as is.

Actual behaviour
---------------
No tracking from nearby.
Upon restart the value is back to _Off_.

Steps to reproduce the behaviour
-------------------------------
Saving the value:
- Go to Config > System > Setup > Tracking.
- In the SkyLines section, set "Track friends" to _On_, the set the below "Show nearby traffic" field to _On_.
- Close and then Quit XCSoar, then start it again.
- If you go in the same dialog, now the "Show nearby traffic" is back to _Off_, while the rest is unchanged.

Show nearby traffic:
- Create a test SkyLines account, or use a friend's one. Set the tracking on a secondary phone via XCSoar / [SkyLines tracker app](https://play.google.com/store/apps/details?id=ch.luethi.skylinestracker), or any other working way.
- Verify the correct functioning of the tracker by visiting https://skylines.aero/tracking and check that your track is present and updated.
- Open your own XCSoar, and set "Track friends" and "Show nearby traffic" to _On_, and check the map: you won't find any Skylines position.
- If then you _follow/befriend_ that account from within Skylines, its position appear correctly.

Do you have any idea what may have caused this?
-----------------------------------------------
Not really, possibly the value is not set correctly and therefore is not read and saved.

Do you have an idea how to solve the issue?
-------------------------------------------
I had a look into the code, I have no experience in C++ and the tracking implementation is out of my possibilities, although I would love to know how it could get fixed.

**Comment by elgandoz** [comment]
Also it would be helpful having in the field's _Help_  how far is "nearby".

**Comment by elgandoz** [comment]
@MaxKellermann thanks for the fix, the option persist now, although "Show nearby traffic" doesn't actually work.

**Comment by MaxKellermann** [comment]
Don't mix two things in one bug report. That's confusing.
