### ISSUE TITLE
Time zone not working on xcsoar 7.18 for kobo.

### ISSUE THREAD

**Issue by marck302** [XCSoar/XCSoar#724]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by GrantHeaney** [comment]
Kobo Glo HD, just tested it, seems to be working for me. 
Menu   configuration/system/Time
Use GPS time set to on, can change UTC offset to anything i like.

**Comment by MaxKellermann** [comment]
This bug report is empty.
