### ISSUE TITLE
XCSoar v7.16 and Android 10, display slowness

### ISSUE THREAD

**Issue by dbsonic1** [XCSoar/XCSoar#727]
XCSoar versions having and not having the problem
-------------------------------------------------
Which XCSoar version are you using when seeing the problem? v7.16 and Android10
Which XCSoar version is the last one you know that did not show the problem? v7.16 and Android11 on another phone.

Expected behavior
-----------------
Expecting reasonably quick responsive display behavior while zooming in or flipping pages.

Actual behavior
---------------
After approx 30 mins to 1 hour into a flight, the display becomes unusable.  very slow and can take several minutes to zoom out or flip a page.

Steps to reproduce the behavior
-------------------------------
v7.16 and Android10 on Pixel 1 phone, fly 30mins and it will happen.  I saw it all summer over 20 flights.

Do you have any idea what may have caused this?
-----------------------------------------------
I don't know.  The Pixel stopped getting OS update at least 1 year ago and is stuck on Android 10.    This would suggest that the OS is static and a newer XCSoar version injected a bug/performance issue?  Phone can't be rooted so I can't upgrade to Android 11. 

Do you have an idea how to solve the issue?
-------------------------------------------
No, it is hard to reproduce.  It will not do it if I just turn on XCSoar and let it sit.  I have wiped the phone clean of all apps and has become a dedicated flight computer with nothing else running, using internal sensors only.  Even that didn't help.  Still happens with a raw/basic setup.
One thing I noticed is that in the end June timeframe it would really hang.  The screen would change colors to like cyan and yellow and essentially hang.  It seems with an update around early July it got better in that sense but still had all the slowness to this day(tested about 2 weeks ago).  I have another, newer phone running XCSoar Android 11 and it works fine.

**Comment by MaxKellermann** [comment]
You're using an old version. Update to the latest before reporting a bug.

**Comment by dbsonic1** [comment]
Okay, I'll update to v7.18 and report back.

**Comment by MaxKellermann** [comment]
And try to reproduce it with replay or simulator.

**Comment by dbsonic1** [comment]
None of the replay attempts below seemed to recreate the issue.  It seems the only way would be to take a flight and capture a log to give to you.

v7.18 replay of flight upon which issue was observed
v7.16 replay of flight upon which issue was observed
v7.16 replay of flight upon which issue was observed and heated device to 120+ F
v7.16 replay of flight upon which issue was observed and cooled device to 40ish F
v7.16 replay of flight upon which issue was observed in cockpit with power supply applied. 
v7.16 fly mode in cockpit but not moving(sitting on ground)

**Comment by lordfolken** [comment]
I will close this issue for now. If you find a way of how to reproduce the problem, then please reopen.
