### ISSUE TITLE
Program Freezing - Android or BLE problem?

### ISSUE THREAD

**Issue by skydogbri** [XCSoar/XCSoar#73]
Recently I've been experiencing problems with XCSoar freezing in mid flight. Sometimes the program just stops working and the screen stays static - eventually I get a popup to say XCSoar has stopped responding. Other times some of the data boxes lose their data for several seconds, the screen icon disappears, then they come back on again. I'm running XCSoar on a Motorola (Lenovo) Moto G4 phone and have been using this for ages like this. Recenty I paired it with XCTracer on BLE and first flights showed no issue, but now this has started. I thought it might have been a conflict with AirWhere which is also connected by BLe to the phone but I tried with AirWhere completely disabled (and a full reboot of the phone) but the problem persists.

Anyone have similar experience or can suggest a way to cure this?

**Comment by Turbo87** [comment]
Haven't played around yet, but without using BLE XCSoar seems to run fine for me

**Comment by skydogbri** [comment]
Follow up info: he flight deck sat on my windowledge all morning, happily transmitting strings of data to XCSoar my phone - both XCTracer and Airwhere over BLE.

I then took it out to my car and after less than 2 minutes the connection was lost to both devices. XCSoar showed no connection to either unit. I started up LK8000, but that failed to connect. However both XCTracer and Airwhere are still visible in the Bluetooth connections page on my phone, but neither XCSoar nor LK8000 will connect.

XCTracer has perfectly complete tracklog from leaving my house to coming back, so it's generating and recording data ok. All the normal vario tones have always been working and the recordings have been fine, even when the phone has been misbehaving.

Restarting the phone and both devices once again connect quickly and are transmitting data.

Anyone have any experience of these kinds of problems? Is it an issue with the phone? But why does it only disconnect once I start recording?

**Comment by iltis42** [comment]
I have the same issue with XCSoar running latest version 6.8.10 on my WayteQ android device.
Especially if do many interactions and zoom in and out onto the map, after a while i see exacly the same issue. If i don't touch the screen a lot, maybe just enter some waypoints to navigate to, and not use screen zoom function, XCSoar survives 8 hours and even more.
Before XCSoar freezes completely, is see some slowness, e.g. any menu opens after several seconds or even minutes, then XCSoar freezes completely and i need to kill the app and relaunch.
This problem feels like there is some slight memory leak in the map redisplay esp. when you alter the scale, and finally XCSoar runs out of memory causing the problem described. 
Propose to debug esp. screen handling as described maybe with valgrind.

**Comment by lordfolken** [comment]
Is this still the case with v6.8.13 ?

**Comment by kilomikesierra** [comment]
It seems to be solved in v6.8.13

The problem occurd on in v.6.8.11 on every flight after eight hours fligttime.
It was reproducible in the Replay Mode (config page 2) with the IGC file created by the FLARM logger. (I discribed this several times in the XCSoar forum under the issue "Program freeze after eight hours flighttime".)

With v.6.8.13 it is possible to replay several long IGC files on five different Android Mobiles without any problem.
