### ISSUE TITLE
Airspace reading error !

### ISSUE THREAD

**Issue by doramail** [XCSoar/XCSoar#738]
Which XCSoar version are you using when seeing the problem? PC & Android Version 7.19
Which XCSoar version is the last one you know that did not show the problem? PC & Android version 7.18

Expected behavior
-----------------

Expected behavior should be no error message displayed about airspace files when program starts.
Airspace should display normally.

Actual behavior
---------------

After the update of the PC version & Android versions, I got this message displayed when launching the program.

![image](https://user-images.githubusercontent.com/8641447/135711896-ed47a529-f7b6-4bb5-9930-d38a65d80809.png)

No airspaces displayed.

Steps to reproduce the behavior
-------------------------------

Just load the program with the french airspace file.

Do you have any idea what may have caused this?
-----------------------------------------------

There should be an issue about the DC values but I do not know more. 

Do you have an idea how to solve the issue?
-------------------------------------------

Unfortunately no.

**Comment by MaxKellermann** [comment]
This just means that your airspace file is broken. Previously such errors were ignored silently, which can cause problems because some airspaces may be missing; it's always better to fix the airspace files than ignoring the existence of those airspaces.

**Comment by MaxKellermann** [comment]
Duplicate of https://github.com/XCSoar/XCSoar/issues/722

**Comment by doramail** [comment]
OK, thank you for your super fast answer, I am always impressed with your fast reaction to issues we may send you. 
I have corrected the original airspace so, now there are no more errors. 
Best regards.

**Comment by doramail** [comment]
Super, OK, thank you for the info.
Best regards.
