### ISSUE TITLE
Kobo Version 7.19 compile errors at Debian 11 (meson)

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#741]
XCSoar versions having and not having the problem
-------------------------------------------------

OK 7.18
NOK 7.19

Expected behavior
-----------------

compile should end without errors

Actual behavior
---------------

see the attached copy of messages when compilig KOBO version

Steps to reproduce the behavior
-------------------------------

make -j5 TARGET=KOBO DEBUG=n  output/KOBO/KoboRoot.tgz

[7.19.err.txt](https://github.com/XCSoar/XCSoar/files/7277473/7.19.err.txt)

Do you have any idea what may have caused this?
-----------------------------------------------

missing librarys

Do you have an idea how to solve the issue?
-------------------------------------------

adding "meson" did not resolve the problem

**Comment by MaxKellermann** [comment]
Does `/home/josef/XCSoar/output/KOBO/lib/bin/armv7a-a8neon-linux-musleabihf-gcc` exist?

**Comment by schmidi** [comment]
Try the fixes from the following PR: https://github.com/XCSoar/XCSoar/pull/739

**Comment by fraktal-sb** [comment]
/home/josef/XCSoar/output/KOBO/lib/bin/armv7a-a8neon-linux-musleabihf-gcc
exists
![Bildschirmfoto zu 2021-10-04 13-34-11](https://user-images.githubusercontent.com/69430537/135845595-cb72c0db-6eba-4dca-97b1-19603407760b.png)

**Comment by fraktal-sb** [comment]
Compile OK with change in meson.py (https://github.com/XCSoar/XCSoar/pull/739)
