### ISSUE TITLE
No Airspace display after installation 7.19

### ISSUE THREAD

**Issue by ConstantGordon** [XCSoar/XCSoar#744]
Since the installation of XCSOAR 7.19 on my Samsung S10e I do not have a display of the airspace anymore.
Upon startup a warning appears:
No center [8091] "DC 0.05"

I did not have this issue before.

**Comment by ConstantGordon** [comment]
Valid comment! I will try and fix my files!

**Comment by Blaubart** [comment]
Hi,

I had this error, too. I could solve it with the fixed airspace for France. Unfortunately the airspace of Luxembourg and Belgium has the same error. Does someone knows how to fix the airspace?

**Comment by lordfolken** [comment]
These files have to be fixed at the source.
https://soaringweb.org/Airspace/BE/HomePage.html has 2 contacts: john laibacher himself. He seems to know the problem. He is also hosting the file directly so he has the most influnce. Please contact him. 
https://www.lvzc.be/index.php/secretariaat-2 seems to be the author.

**Comment by lordfolken** [comment]
From the looks of it, the (old) french file seems to be append to the Belgium file.
