### ISSUE TITLE
XCSoar/python/test/test_xcsoar.py should probably be updated to Python 3

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#758]
Hello,

I don't know exactly what is the purpose of https://github.com/XCSoar/XCSoar/blob/master/python/test/test_xcsoar.py
But it should probably be updated to Python 3

Pinging @TobiasLohner

Kind regards

**Comment by scls19fr** [comment]
This file should probably also be renamed because `test_...py` are often used as filename for unit tests (automatically detected by tools such as [nosetests](https://nose.readthedocs.io/en/latest/) or [pytest](https://docs.pytest.org/)

**Comment by roscosoarer** [comment]
If this is associated with the SkyEcho interface I am interested.  SkyEcho outputs Garmin format GLD-90 (ADSB protocol)) that needs to be converted into NMEA messages   I currently do this by running XC-Guide and WiFi that into my Samsung table through <config> < devices> localhost  but this is clunky and unreliable and often requires XCSoar to be restarted [=bad in-flight log].   A simpler interface would be great.  I'm watching with interest.
![Localhost IMG_20221108_111920_094820857](https://user-images.githubusercontent.com/67410740/202584954-9e9c68bb-d7ef-44c2-bb8f-352415b1e65d.jpg)

**Comment by lordfolken** [comment]
implemented by f5a478f6e5e66f3eb028a90a44823ab0345a5aa1
