### ISSUE TITLE
Developer documentation - confusion between xcsoar.readthedocs.io and XCSoar Developer manual

### ISSUE THREAD

**Issue by scls19fr** [XCSoar/XCSoar#759]
Hello,

On https://github.com/XCSoar/XCSoar, the following paragraph

> Compiling from source
> Please read the current Developer's Manual for detailed build instructions.

point to https://xcsoar.readthedocs.io/en/latest/

but it leads to confusion between this website and "XCSoar Developer manual" available at https://download.xcsoar.org/releases/7.19/XCSoar-developer-manual.pdf

Maybe it should be named differently or information be merged in the same document.

Kind regards

**Comment by lordfolken** [comment]
You are correct. 
[] The main readme should be updated (point to compile instructions in docs/
[] The secitions that have been created in doc/built.rst should be removed from the development manaual
[] The container build method is missing from the rsts and only describe here: ./ide/docker/readme.md
