### ISSUE TITLE
Traffic-Circuits on airspace-file are not displayed and Error 959 on startup XCSoar

### ISSUE THREAD

**Issue by Dimowelle** [XCSoar/XCSoar#767]
Currently I use Version 7.20
Last Version that works well: version till June 2021 - I think. 

Expected behavior
-----------------
Traffic circuits should be displayed on moving-map as configured at "other airspaces" (german: Standortdatei/Weitere-Luftraeume)

Actual behavior
---------------
Starting XCsoar/Loading Airspaces (Luftraumdatei) leads to error:
Bad radius [959} "Dahlemer Binz"

Steps to reproduce the behavior
-------------------------------
Editing the txt-File and deleting the traffice-circuit of Dahlemer-Binz gives the same error to the next Airport, ...
Disabling the airspace-file in the configuration gives no error at starting XCsoar, but of course no display of traffice-circuits :-(

Do you have any idea what may have caused this?
-----------------------------------------------
Maybe some new features on XCSoar-Updates

Do you have an idea how to solve the issue?
-------------------------------------------
Analyze new features on airspaces, that leads to the error 959 starting XCSoar.

**Comment by Dimowelle** [comment]
ftp://j900480@192.168.178.3/Platzrunden.txt

**Comment by Dimowelle** [comment]
I dont know howto attach, so I copy&paste.
Maybe you can locate the problem and have

**Comment by lordfolken** [comment]
Hmm. I'm not sure what to do here.. 

The person who wrote this file didn't understand the standard:
http://winpilot.com/usersguide/userairspace.asp

*  AH string        ;     string = Airspace Ceiling
*  AL string        ;     string = Airspace Floor

Example:
```
Bohmte-Bad Essen 

AC O
AN 10/28 
AH 700 ft
AL 580 m, UL(PPR), MOGAS
```
* Mixing units is always dangerous. 
* So in this case the floor is above the ceiling.
* The text string ", UL(PPR), MOGAS" is not valid. This belongs in a cup waypoints file... or at tleast in the AN (name tag)
* The name "bad essen" needs to be prefixed with a * as its a comment. 

There is issues throughout the file. I suggest you rework it from the ground up.

**Comment by Dimowelle** [comment]
Hi, 

thank you for the advice with the standard.
I fixed the failures in the file and now it works :-)

But I think, the file is a very old version.
I have to search for a new version with actual datas ... 

Thank you
Matthias
