### ISSUE TITLE
Build fails for target UNIX at v6.8.10.

### ISSUE THREAD

**Issue by Exadios** [XCSoar/XCSoar#81]
Source file src/Screen/X11/TopWindow.cpp fails to build due to missing header.

**Comment by Turbo87** [comment]
on what platform? seems to work fine for me 🤔

**Comment by Exadios** [comment]
Hi Tobias;

I'm building on a standard issue Debian 9 ("stretch") using g++ v6.3.0 and its headers.

But rather than focusing on what might be different with our platforms I would like to make the following argument in favor of merging this pull.

I direct your attention to https://github.com/XCSoar/XCSoar/blob/v6.8.x/src/Screen/X11/TopWindow.cpp, line 60 - fprintf(...... So stdio.h is required. In your case it must be included as a result of a side effect. In my case it is not.

By leaving out the include here the source is dependent on the particular details of (presumably) the build environment. That is the omission of the include is a failure waiting to happen. On the other hand having the include here is quite natural in the circumstances and, if it redundant, it will be ifdefed out.

**Comment by Exadios** [comment]
One other thing I should mention is that I run make with DEBUG=n and GREEN_MENU=n

**Comment by kerel-fs** [comment]
Issue was fixed on the master in 2015 by Max, see https://github.com/XCSoar/XCSoar/commit/a09fa72bc0938ae0261c375415d83e6a0911f8f1

Please base all your development on the `master` branch. If you think something should be backported, rebase those exact commits.

**Comment by Exadios** [comment]
So, it seems that I cannot reproduce the problem. I must have had some sort of finger problem here. This issue is closed.
