### ISSUE TITLE
Error in make Ubuntu 20.04.3

### ISSUE THREAD

**Issue by urb31075** [XCSoar/XCSoar#810]
I create VMWare virtual PC and installed the Ubuntu Server 20.04.3, installed all updates.

urb@bildhost:~/XCSoar$ uname -a
Linux bildhost 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I clone  https://github.com/XCSoar/XCSoar.git  and  compiled according to the instructions  https://xcsoar.readthedocs.io/en/latest/build.html

(I get error: Unable to locate package liblua5.4-dev.  Instead of this package, i installed the package liblua5.3-dev)

When i run make, i get error:
 CXX     output/UNIX/dbg/src/io/MapFile.o
g++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?
g++: error: unrecognized command line option ‘-fcoroutines’
make: *** [build/compile.mk:108: output/UNIX/dbg/src/io/MapFile.o] Error 1

**Comment by MaxKellermann** [comment]
Your GCC version is too old. Ironically, the 2020 version of Ubuntu doesn't have a C++20 compiler.
