### ISSUE TITLE
Duplicate Waypoints on short waypoint files

### ISSUE THREAD

**Issue by reuti1697** [XCSoar/XCSoar#816]
The waypoints  apperar twice.
It is a normal *.cup - File. Exportet from Strepla für LX9000

XCSoar versions having and not having the problem
-------------------------------------------------

Having:
XCSoar v7.19 (debian)
XCSoar7 v.20-Android
It's the same behavior an Windows 7.21-PC

Having not:
XCSoar 7.18 (debian)

Expected behavior
-----------------

A waypoint corresponds to a waypoint in the CUP-File

Actual behavior
---------------

2 identic waypoints corresponds to 1 waypoint in the CUP-File

Steps to reproduce the behavior
-------------------------------
* Load the attached file as the sole file
* Open the waypoint list via for example the guesture

Do you have any idea what may have caused this?
-----------------------------------------------

No Idea

Do you have an idea how to solve the issue?
-------------------------------------------

No. Sorry

**Comment by reuti1697** [comment]
[WP-Reuti-Test.txt](https://github.com/XCSoar/XCSoar/files/7780947/WP-Reuti-Test.txt)

**Comment by MaxKellermann** [comment]
You did not specify the latest version which does not have the problem.

**Comment by reuti1697** [comment]
I'm sorry, I can't quite tell. I always use the latest version of Google Play.
I only noticed the error last week when I was creating new waypoint files. At first I thought there was something wrong with the waypoint files. But they seem correct to me. Thanks for your help and especially thanks for the great program. I love it. Can I do something for you? Peter.

**Comment by reuti1697** [comment]
[Test.pdf](https://github.com/XCSoar/XCSoar/files/7792367/Test.pdf)

**Comment by lordfolken** [comment]
So i tested several versions and it seems to be connected to the search short name search feature, introduced in v7.19
https://github.com/XCSoar/XCSoar/commit/6099befc0be5ce821b792e0ed61c1fc8bfa2ec72

* This happens with cup files that have field 2 (shortname) defined. 
* The particular file here has only few waypoints, so all the waypoints appear without searching.
* You can also trigger it when you use another filter criteria like direction, waypoints with shortname defined appear twice. 
* We knew it happens when 

Some potential approaches:
  * Seperate the name / shortname searches and use different fields in the "Select Waypoiint" Dialog
  * Find a way to eliminate duplicates in the radix tree. 
  *

**Comment by MaxKellermann** [comment]
See https://github.com/XCSoar/XCSoar/pull/743

**Comment by scls19fr** [comment]
I'm also facing same issue when selecting type Landable for example

![Screenshot_2022-05-07-08-17-19-57_943b36a15770a48ab82837a5cf06e5e4](https://user-images.githubusercontent.com/109167/167241570-ea557194-d05f-44c4-8f64-13faaa26638b.jpg)
![Screenshot_2022-05-07-08-16-59-30_943b36a15770a48ab82837a5cf06e5e4]

But not when filtering by distance

(https://user-images.githubusercontent.com/109167/167241580-2afc3909-e974-4d09-a1d3-3ddebdc5dda5.jpg)

**Comment by scls19fr** [comment]
I don't know if that's related but removing waypoints file(s) in config and waypoints are still present on the map as if XCSoar was silently loading waypoints whereas I explicitely ask for no waypoints (or there is a kind of cache). Maybe it could explain why they are displayed twice.

**Comment by scls19fr** [comment]
![Screenshot_2022-05-07-08-36-03-75_943b36a15770a48ab82837a5cf06e5e4](https://user-images.githubusercontent.com/109167/167242172-fe764b73-e97a-4e76-aee1-ac0cb2658e94.jpg)

![Screenshot_2022-05-07-08-36-10-14_943b36a15770a48ab82837a5cf06e5e4](https://user-images.githubusercontent.com/109167/167242180-4b804d1a-6890-4d11-bc26-62054585e5ea.jpg)

**Comment by yo7ckp** [comment]
I gave up the Waypoint Code
