### ISSUE TITLE
cannot load 

### ISSUE THREAD

**Issue by pby51** [XCSoar/XCSoar#817]
XCSoar versions having and not having the problem
-------------------------------------------------

Expected behavior
-----------------

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by pby51** [comment]
I cannot download the map from Ireland high res. By restarting XCsoar I get a error code "No center(262)'DC 0.05'".
my phone is a samsung A12  Android version 11 last updat 1 November 2021.

**Comment by lordfolken** [comment]
The "No center" is a problem with the airspace file. 
The 404 for the IRE (and all other airspaces i fixed with the recent commits in https://github.com/XCSoar/xcsoar-data-content
thx for reporting.

**Comment by pby51** [comment]
Are you saying that there are corrections available?
How can I get them in the xcsoar 7?

Van: Philipp Wollschlegel ***@***.***>
Verzonden: dinsdag 28 december 2021 21:08
Aan: XCSoar/XCSoar ***@***.***>
CC: pby51 ***@***.***>; State change ***@***.***>
Onderwerp: Re: [XCSoar/XCSoar] cannot load (Issue #817)


The "No center" is a problem with the airspace file.
The 404 for the IRE (and all other airspaces i fixed with the recent commits in https://github.com/XCSoar/xcsoar-data-content<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXCSoar%2Fxcsoar-data-content&data=04%7C01%7C%7C6729f8a933144eaa096308d9ca3dc21f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637763188856403648%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j26e5Agms33BCBQoturODGUffS8RgxiveXXlAo61Phw%3D&reserved=0>
thx for reporting.

-
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXCSoar%2FXCSoar%2Fissues%2F817%23issuecomment-1002263579&data=04%7C01%7C%7C6729f8a933144eaa096308d9ca3dc21f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637763188856413641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BOK8xN9TtDs6L8FeF0EPVAzt13tKdoxZB4a%2BNzWB0go%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXCNG7GKKTWLQLC7LN6KFIDUTIKKJANCNFSM5K4K3ITA&data=04%7C01%7C%7C6729f8a933144eaa096308d9ca3dc21f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637763188856423637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XJ3jACe2cryLnR9eeJgsY%2Fwhk85Xr1CAL0MXLJjdCHk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6729f8a933144eaa096308d9ca3dc21f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637763188856423637%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b4QpBdeN1JaxoOycg6LRmtc%2BOuBJk9cBZIXaAPRqRZU%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6729f8a933144eaa096308d9ca3dc21f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637763188856433645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=12FCMYKsYjt4jnNEXybMfos3ZPwEAzMvwgDghhZCQqc%3D&reserved=0>.

**Comment by lordfolken** [comment]
I don't know what airspace file you are using. 
The center message is an error in the airspace file and has no relation to the map.

**Comment by pby51** [comment]
Ok, but I cannot download the IRE map, how can I make this work

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Philipp Wollschlegel ***@***.***>
Verzonden: Thursday, December 30, 2021 3:49:38 PM
Aan: XCSoar/XCSoar ***@***.***>
CC: pby51 ***@***.***>; State change ***@***.***>
Onderwerp: Re: [XCSoar/XCSoar] cannot load (Issue #817)


I don't know what airspace file you are using.
The center message is an error in the airspace file and has no relation to the map.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXCSoar%2FXCSoar%2Fissues%2F817%23issuecomment-1003061364&data=04%7C01%7C%7Ca235778905884bd2176b08d9cba39b09%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764725816011303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=waJ38i39lo0j2%2B52LgRRhUGjNeM9fmJWdsfuKrcdyVA%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXCNG7C427BJIPYYPRPNIK3UTRWQFANCNFSM5K4K3ITA&data=04%7C01%7C%7Ca235778905884bd2176b08d9cba39b09%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764725816021281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x15MNIRwXM5UebJqWXwNU7o%2FD2UFoKtgJK7K6cz9eaM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca235778905884bd2176b08d9cba39b09%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764725816021281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZInKVSziJa6G%2F9EFWj1gEvAOfsSegRYCAzDkrIc%2F4eA%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca235778905884bd2176b08d9cba39b09%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764725816031277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fM4fOObgJfiCKEJuz%2Foi6ls6TZh68knU6q%2Be1DJ7Qd0%3D&reserved=0>.

**Comment by lordfolken** [comment]
Double tap on screen->config-config->file manager->add->ire_highres.xcm then go to config->system -> site files map database ire... 

We have a general quickstart guide here
https://xcsoar.org/discover/manual.html

**Comment by pby51** [comment]
Thanks it works

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Philipp Wollschlegel ***@***.***>
Verzonden: Thursday, December 30, 2021 5:21:30 PM
Aan: XCSoar/XCSoar ***@***.***>
CC: pby51 ***@***.***>; State change ***@***.***>
Onderwerp: Re: [XCSoar/XCSoar] cannot load (Issue #817)


Double tap on screen->config-config->file manager->add->ire_highres.xcm then go to config->system -> site files map database ire...

We have a general quickstart guide here
https://xcsoar.org/discover/manual.html<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fxcsoar.org%2Fdiscover%2Fmanual.html&data=04%7C01%7C%7Ca73943e99e3e4138860408d9cbb07088%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764780920571335%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MUCxRQjbJCcMBadnuXq1nSoZiTYhkkeeSxVB5H0Gp5A%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FXCSoar%2FXCSoar%2Fissues%2F817%23issuecomment-1003095820&data=04%7C01%7C%7Ca73943e99e3e4138860408d9cbb07088%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764780920581324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xHMGamVvPhryqUk4eZSruLpBpqR2WlwS5ofqSEHE0VE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXCNG7FINSSWTS3DGSTAUEDUTSBIVANCNFSM5K4K3ITA&data=04%7C01%7C%7Ca73943e99e3e4138860408d9cbb07088%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764780920581324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BPFo4BVVt%2BbZcUuzjTimmiCEJcvZU5fY52YI%2Fq%2BtYdY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca73943e99e3e4138860408d9cbb07088%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764780920591321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sNrYklImAFhkWK9h1J99Dw5zBaDQBo%2FCBq4sdDjoLfQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca73943e99e3e4138860408d9cbb07088%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637764780920591321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TY13Oz0MKDobAjYjjrzFDfVeuxzdVUWiHWktOsj9ziQ%3D&reserved=0>.
