### ISSUE TITLE
Implementing RC Electronics driver for Fenix unit

### ISSUE THREAD

**Issue by andrejvrecer** [XCSoar/XCSoar#834]
XCSoar version 7.21
--------------

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------
New driver support for communication with Fenix unit from RC Electronics.
Currently unit already supports data output of GPS NMEA data (GPGGA, GPRMC, GPRMB), Flarm data  ( if Flarm unit is conencted to it) and LXWPx data

In specification which can be found on website: https://www.rc-electronics.eu/downloads-gliding/manuals-gliding/ There is RCDT (data transfers) needed to be implemented so different data can be transferred from XCSoar to Fenix unit and vice versa if needed. Specially TASK declaration with zone shapes and pilot information.

Unit can communicate over wired port caled Data 1 port or via integrated BT (not BLE) modul.

Demo unit needed for development can be provided.

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

**Comment by lordfolken** [comment]
Are you the manufacturer? Ideally the manufacturer implements **and  maintains** the driver in XCSoar. That way  compatibility with for example firmware upgrades, is ensured.

**Comment by lordfolken** [comment]
No reaction. Closing this issue.
