### ISSUE TITLE
Dark text background on Debian 11 compiled KOBO version 7.22

### ISSUE THREAD

**Issue by fraktal-sb** [XCSoar/XCSoar#839]
XCSoar versions having and not having the problem
-------------------------------------------------

Which XCSoar version are you using when seeing the problem?

v7.22 compiled at Debian 11 (see screenshots)

![IMG0001](https://user-images.githubusercontent.com/69430537/149625919-e5b4de76-0aef-487c-9fe1-37c9004c5c15.png)
![IMG0002](https://user-images.githubusercontent.com/69430537/149625921-1113dff0-db1b-4e53-89c3-63826bc664b1.png)

Which XCSoar version is the last one you know that did not show the problem?

v7.21 is OK and the KOBO version from XCSoar homepage does not have this behavior

Expected behavior
-----------------

Texts should not have a dark background

Actual behavior
---------------

Texts have a dark background; this is unreadable; make clean and recompile did not help

Steps to reproduce the behavior
-------------------------------

use standard Debian 11 and compile with "make TARGET=KOBO DEBUG=n"

Do you have any idea what may have caused this?
-----------------------------------------------

no

Do you have an idea how to solve the issue?
-------------------------------------------

no

**Comment by ulipo** [comment]
Same here, compiled on Docker image, and same also with KoboRoot.tgz downloaded form official site.
![photo_2022-01-15_18-46-42](https://user-images.githubusercontent.com/32038266/149632649-45fd2840-b7f6-4aa2-8917-c8afb7c50375.jpg)

**Comment by MaxKellermann** [comment]
cd175cbf7d018dd44e7cb6c32b43f61e37293214 is the first bad commit
