### ISSUE TITLE
Latest Commit failed to run on Linux

### ISSUE THREAD

**Issue by August2111** [XCSoar/XCSoar#858]
With latest commit  5a1d779 the start of xcsoar is failing with error message on terminal
```
...
xcsoar: src/event/Loop.cxx:278: void EventLoop::Run(): Zusicherung »busy« nicht erfüllt.
Abgebrochen (Speicherabzug geschrieben)

```
in this line I found an assert function...
System: Ubuntu 21.10
On Win and on OV linux it starts like expected

XCSoar versions having and not having the problem
-------------------------------------------------

Switching one commit back to d91177152 it works well!

Expected behavior
-----------------

Starts...

Steps to reproduce the behavior
-------------------------------

Complete make on the linux subsystem

Do you have any idea what may have caused this?
-----------------------------------------------

No

Do you have an idea how to solve the issue?
-------------------------------------------

No

**Comment by lordfolken** [comment]
Samething here. reverting 5a1d7797892d4729f916495924dc60a4681dbac0 works.
