### ISSUE TITLE
Swap "Details" and "Settings" buttons" on "Map elements at this position" page

### ISSUE THREAD

**Issue by MikeBravo15** [XCSoar/XCSoar#864]
XCSoar version
--------------

7.23

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

Same as #856 but for the "Details" and "Settings" buttons on the "Map elements at this position" page. Thank you

**Comment by lordfolken** [comment]
https://github.com/XCSoar/XCSoar/commit/7e1b8a377ffdb5f9e7bd9c68b6a0437d34745510
