### ISSUE TITLE
WndForm runs into assertion in Windows when closing with ESC key (keyboard)

### ISSUE THREAD

**Issue by volkmarnissen** [XCSoar/XCSoar#901]
XCSoar versions having and not having the problem
-------------------------------------------------
XCSoar main branch run on windows.

Expected behavior
-----------------
Open the checklist dialog
Press ESC **key** (The button on the screen works properly)
Expectation: The dialog should close (but nothing happens)
Press the key again
You get multiple assertions because hidden windows are going to be hidden

Actual behavior
---------------
The dialog doesn't close when pressing ESC key on the keyboard
Nothing happens
If you press ESC again, you get assertions.

Steps to reproduce the behavior
-------------------------------
See above. It is reproducible.

Do you have any idea what may have caused this?
-----------------------------------------------
In the code "Form/Form.cpp", there is some #ifndef WIN_USER (line 396) part which might be part of the problem.
However, I am not so deep into it, that I can fix it.
My version of Form.cpp has a small modification, but I don't think, that it causes the issue, because it doesn't apply to the ESC key.
If you are not able to reproduce, just close the issue. I will look into it.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

**Comment by lordfolken** [comment]
You're right. 
Even on wine64 i can at least crash it when hitting esc.

**Comment by lordfolken** [comment]
The Assertion
![image](https://user-images.githubusercontent.com/407371/168471424-12d2a6a8-812d-410c-ad48-f8656bffc658.png)

**Comment by lordfolken** [comment]
Please test.
