### ISSUE TITLE
Messages appears too short

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#904]
I find that the messages on the screen, such as airspace warnings, are much too short. I almost never get to read the message before it's gone. Others I've talked to would also like a little longer. It might also be a good idea to be able to set the time yourself in the setup.

**Comment by lordfolken** [comment]
I agree

**Comment by lordfolken** [comment]
@Blaubart can you vreview the changes please?

**Comment by Blaubart** [comment]
I think 2.5s is enough. Thanks a lot!!!
