### ISSUE TITLE
Unable to download flights from Flarm

### ISSUE THREAD

**Issue by Blaubart** [XCSoar/XCSoar#906]
I don't know exactly if it's a bug, but today I couldn't download flights from Flarm on various airplanes with the OPenVario with XCSoar 7.24.

**Comment by Scumi** [comment]
Observed the same today.

**Comment by lordfolken** [comment]
Declaration didn't work for me either.

**Comment by August2111** [comment]
I didn't look to the declaration of a task - but maybe  this is the same issue - and I will check it!

**Comment by lordfolken** [comment]
duplicate #822

**Comment by lordfolken** [comment]
Closing this as #822 contains more info.
