### ISSUE TITLE
Wind arrow infobox not updating according to heading variations

### ISSUE THREAD

**Issue by ulipo** [XCSoar/XCSoar#914]
XCSoar versions having and not having the problem
-------------------------------------------------
7.12 and newer (tested on Kobo Touch and WIN64).
Works as expected on 7.11 and older.

Expected behavior
-----------------
When the aircraft changes heading, the wind arrow infobox should update to show the relative wind direction (with aircraft nose pointing to the top of the screen)

Actual behavior
---------------
The arrow always stays in the same position, even if the numerical values may change; the arrow direction changes only when you touch/interact with the infobox.

Steps to reproduce the behavior
-------------------------------
Start a SIM flight, set some values for wind (I used 5 Kt and 90°), make the aircraft do some turning and see the wind arrow remaining the same.
Touch the infobox to see that the arrow direction updates correctly once.
Rinse and repeat.

Do you have any idea what may have caused this?
-----------------------------------------------
I thought it could have something to do with this lines in the changelog:
 Kobo
    throttle sensor-triggered screen updates
    improve performance of graphical InfoBoxes

but it does the same also on windows version, so I have no clue...

Do you have an idea how to solve the issue?
-------------------------------------------
No idea :-(
IANAC but I can try to do my best if someone point me in the right direction...

**Comment by scls19fr** [comment]
Wind arrow is updated when clicking on info box and when wind is changing but not at fixed time interval (like Next arrow)
