### ISSUE TITLE
Raspberry Pi4 XCSoar v7.24 crahes with floating point exception on startup

### ISSUE THREAD

**Issue by phintenaus** [XCSoar/XCSoar#948]
XCSoar versions having and not having the problem
-------------------------------------------------

v7.24, freshly built from sources

Expected behavior
-----------------

XCSoar should display startup screen

Actual behavior
---------------

XCSoar crashes with floating point exception. It reports 
EGL vendor: Mesa Project
EGL version: 1.4
EGL extensions: ...
GL vendor: Broadcom
GL version: OpenGL ES 3.1 Mesa 20.3.5
GL renderer: V3D 4.2
GL extensions: ...

Steps to reproduce the behavior
-------------------------------

Pulled sources from GitHub. Did 
cd XCSoar
make
cd output/UNIX/bin
./xcsoar

Do you have any idea what may have caused this?
-----------------------------------------------

no, not really...

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by lordfolken** [comment]
Can you specifiy which git commit you took? and can you add more log lines?
Potentially can you start with 
```strace -fff -o mycrashlog.txt xcsoar```
and attach the log?

**Comment by bomilkar** [comment]
Did you try to start xcsoar with explicit DPI argument?
`xcsoar -dpi=168x177`
Does it still produce the exception?

**Comment by lordfolken** [comment]
No info since 2 months. closing.
