### ISSUE TITLE
Reproduce and rebuild Kobo Kernel and Modules

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#963]
The Kernel and Modules in http://download.xcsoar.org/contrib/kobo/kernel/ are built without a clear way of building them. 
We need a system that reproduces these images. we already have the kernel configuration in 
XCSoar's source tree:
https://github.com/XCSoar/XCSoar/tree/master/kobo/kernel

**Comment by lordfolken** [comment]
CC: @GeekGoneOld

**Comment by lordfolken** [comment]
Also the kobo nia is missing.

**Comment by GeekGoneOld** [comment]
When I built the kernel for Clara HD (actually, for the drivers for OTG mode), I step-by-step documented both how I set up the development environment and how I did the rebuild.  Is there somewhere you would like this?  An appendix to a manual?

**Comment by lordfolken** [comment]
I'd like to make the docker container be able to build the kernels. There is already a cross build toolchain for the kobo in there so it would be easy to add a script.

**Comment by MaxKellermann** [comment]
This should be solved since 15dc8667f1ff5d84833fce89c73f1705cdbc5182 (the most recent change on that file).
What is still missing is Nia kernels; please open a separate issue for that. I have no idea how to build those Nia kernel modules.
