### ISSUE TITLE
FT232 Dual Channel Support

### ISSUE THREAD

**Issue by XCNav** [XCSoar/XCSoar#966]
XCSoar version
--------------

7.2.2

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------

If connecting 2 FT232 Serial to USB converters XCSOAR only recognises one in the NMEA list of devices. As they both have the same VID/PID XCSOAR seems to see them as one device.
Please describe the feature you'd like us to add/change. The D2xx driver allows to distinguish between 2 devices with same vid/pid via openByindex. Please index for multiple chanel operation.

What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------
connecting 2 serial devices in parallel operation on designated android device
parallel input of 2 serial datastreams

**Comment by lordfolken** [comment]
This should be a bug. As this is unpredictable. Platform is android i assume?

**Comment by lordfolken** [comment]
Also what version are you using? Can you add screenshots? And xcsoar.log?

**Comment by lyusupov** [comment]
@XCNav XCSoar had inherited "_USB for Android_" support from LK8000 last year.
Thus, just like the LK8000 does, the XCSoar uses https://github.com/mik3y/usb-serial-for-android component to operate with USB-Serial devices.
The library is maintained by Kai Morich.. There is a reference application for Android that uses this library: - https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal - it was created by the same author.

You can test first if the reference app can handle multiple connections to FT232 devices at the same time. If it doesn't - it reduces the chances of having this feature in XCSoar.

**Comment by lyusupov** [comment]
Inspect if your issue report duplicates this one: https://github.com/mik3y/usb-serial-for-android/issues/428

**Comment by XCNav** [comment]
No, it does not exactly, as I have acces to both ports simultaneously. 
I am no software guy and dont work on a console and at the present I have no access to the device and will add Screenshots later. I can run both ft232 in parallel on the device using the usb serial monitor as above plus another serial monitor in splitscreen mode, both running different varios(xcvario and LXEra), both sending NMEA datastream.
I had the same issure running LK8000   
After communicating with Bruno from LK8000 he changed the way the driver identifies the 232. Now I can run both ports in parallel on LK8000.

**Comment by lyusupov** [comment]
> After communicating with Bruno from LK8000 he changed the way the driver identifies the 232.

If would supply commit ID of the LK8000 patch - it will ease for XCSoar developers to track and resolve the issue.

**Comment by brunotl** [comment]
LK8000 patch : commit  [d8cdbbd](https://github.com/LK8000/LK8000/commit/d8cdbbde75fe543957e7a2377b473890a35a0875)

**Comment by XCNav** [comment]
As brunotl submitted the patch, is there any plan or progress?

**Comment by hjr** [comment]
Have the same issue with XCSoar 7.23. Described it in a comment to #968

**Comment by XCNav** [comment]
Is there more information needed than the patch? Should i open it as pull request?

**Comment by lordfolken** [comment]
Please make a PR @XCNav will discuss in there.

**Comment by MaxKellermann** [comment]
I thought the LK8000 code isn't good, so I implemented my own version of the feature, after refactoring the hell out of class UsbSerialHelper. It's now much more robust than before, and supports multiple ports per device, and multiple devices of the same kind.

**Comment by XCNav** [comment]
Perfect! Thank you!

**Comment by XCNav** [comment]
![20220824_224242](https://user-images.githubusercontent.com/78668199/186519715-ba9e7e2c-52bd-45d0-a62f-5395acf2ea53.jpg)
Works perfect! Thank you Max!

**Comment by hjr** [comment]
![IMG_2226](https://user-images.githubusercontent.com/415029/186888276-38f5fbf1-31a9-4228-a110-20bf320fce5c.JPG)
![IMG_2227](https://user-images.githubusercontent.com/415029/186888314-2071d86d-1a54-462c-a45d-e6f0318662bf.JPG)
Unfortunately it does not work for those CP2102 serial bridges. I get the connect popup when I plug each of them, but the device enumeration shows only one. Selecting it a second time at least shows the consequent "already occupied" message.

**Comment by lyusupov** [comment]
```
$ lsusb -v -d 10c4:ea60

Bus 001 Device 053: ID 10c4:ea60 Cygnal Integrated Products, Inc. CP210x UART Bridge / myAVR mySmartUSB light
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x10c4 Cygnal Integrated Products, Inc.
  idProduct          0xea60 CP210x UART Bridge / myAVR mySmartUSB light
  bcdDevice            1.00
  iManufacturer           1 Silicon Labs
  iProduct                2 CP2102 USB to UART Bridge Controller
  iSerial                 3 0001
  bNumConfigurations      1
...

```

'Serial Number' (**iSerial** field above) of the CP210x device has to be a unique identifier across all other CP210X devices you plug into the XCSoar Android box.

One may alter the serial number by this utility: https://github.com/VCTLabs/cp210x-program

**Comment by hjr** [comment]
Thx
