### ISSUE TITLE
Pagination Incorrect

### ISSUE THREAD

**Issue by thomasvdv** [XCSoar/XCSoar#997]
Entering a multi-page menu lists the incorrect page number. The first page is listed as 2/3.
![Screenshot_20220818-214430](https://user-images.githubusercontent.com/828655/185524608-f93f445b-164c-44c0-bac8-6161bc0aa649.png)

**Comment by lordfolken** [comment]
Hi, we changed this recently. See the discussion in #927 and the linked bug report. 
When you click on it you get to page 2/3, as you are currently viewing page 1/3. 
This is a button that creates an action and  shouldn't be a page title.

**Comment by lordfolken** [comment]
https://github.com/XCSoar/XCSoar/pull/913#issuecomment-1111055564

**Comment by thomasvdv** [comment]
I think this may be confusing to many users. There were five members on our club's mailing list who thought this was a bug. You're mixing state display and action buttons. Showing a button with the label of the next page state is unintuitive in my opinion. Do you have examples of this pattern elsewhere? Users are used to seeing pagination labels (1/3, 1 of 3, etc.) as a representation of the current page state. Adding this labeling to a button is something most users will be confused by IMHO. You have to either separate the pagination label from the action button or keep it as-is, even though it may technically be debatable - from a user perspective it's much more intuitive.

**Comment by styblope** [comment]
Although one gets used to the specifics of the UI, I think a simple "Next >>" or similar action label would be pretty intuitive and sufficient. As there are typically no more than 3 pages (and no way to go back) it is not that useful to show which page out of how many we are moving to. Note, it is particularly easy to redefine the default labels via a custom `.xci` events file, see [here](https://xcsoar.readthedocs.io/en/latest/input_events.html).

**Comment by lordfolken** [comment]
As no one came forward with a proposal, im closing this
